### ISSUE TITLE
Usar más de 1 línea de WhatsApp API

### ISSUE THREAD

**Issue by waraujo30** [Vinix-Code-Dev/curso-api-whatsapp-frontend#10]
Como administrar varias líneas de WhatsApp API?

**Comment by vinixcode** [comment]
Hola Walter.
Básicamente es el mismo proceso que se hace en el curso, pero en este caso no podrías usar variables de entorno sino que debes almacenar la información de cada cuenta y negocio en la base de datos.

También por ejemplo puedes generar una URL dinámica para el webhook, según el ID del teléfono que hayas almacenado en la base de datos.

En resumen, encárgate de que todo lo guardes en la BD y no quede en el código, y así podrás agregar tantos números como quieras.

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.

**Comment by waraujo30** [comment]
Puedes hacer sólo 1 ejemplo, porque le he dado vuelta pero no encuentro la forma?
