### ISSUE TITLE
Error en clase 13

### ISSUE THREAD

**Issue by RAGUDIG** [Vinix-Code-Dev/curso-api-whatsapp-frontend#11]
Estimado Juan, al trabajar ya con la base de datos y mostar los mensajes me da este error en sobre la funcion sesponse, dera que dedo de usar algo en especial.
![image](https://user-images.githubusercontent.com/44486594/205497015-f27e83a1-4938-4810-924e-0f48ced9dc36.png)

al hacer la prueba de http://localhost:8000/api/messages me da 404 NOT FOUND

pero tengo agregado correctamente la ruta

![image](https://user-images.githubusercontent.com/44486594/205497323-c6511aa5-580e-4c1e-b415-f356dcca3e32.png)

**Comment by RAGUDIG** [comment]
> Estimado Juan, al trabajar ya con la base de datos y mostar los mensajes me da este error en sobre la funcion sesponse, dera que dedo de usar algo en especial. ![image](https://user-images.githubusercontent.com/44486594/205497015-f27e83a1-4938-4810-924e-0f48ced9dc36.png)
> 
> al hacer la prueba de http://localhost:8000/api/messages me da 404 NOT FOUND
> 
> pero tengo agregado correctamente la ruta
> 
> ![image](https://user-images.githubusercontent.com/44486594/205497323-c6511aa5-580e-4c1e-b415-f356dcca3e32.png)

solucionado, tube que borrar cache con php artisan optimize:clear

**Comment by vinixcode** [comment]
Gracias por informarnos de la solucion, Rodulio!
