### ISSUE TITLE
Capturar eventos de llamadas de accion

### ISSUE THREAD

**Issue by gchirinos** [Vinix-Code-Dev/curso-api-whatsapp-frontend#12]
Hola a todos! necesito saber por favor si es posible capturar de alguna manera en el WebHook cuando el cliente interactua con los botons de llamada de accion, como por ejemplo los botones que rediriguen a una URL. No he encontrado forma de hacerlo pero no se si exista la posibilidad de capturar por medio del WebHook que el usuario le espichó al botón de llamada de acción.

Agradezco me puedan ayudar y estoy realizando el curso y solo tengo comentarios positivos, muy didactivo y con practicas interesantes.

Saludos.

**Comment by RAGUDIG** [comment]
> Hola a todos! necesito saber por favor si es posible capturar de alguna manera en el WebHook cuando el cliente interactua con los botons de llamada de accion, como por ejemplo los botones que rediriguen a una URL. No he encontrado forma de hacerlo pero no se si exista la posibilidad de capturar por medio del WebHook que el usuario le espichó al botón de llamada de acción.
> 
> Agradezco me puedan ayudar y estoy realizando el curso y solo tengo comentarios positivos, muy didactivo y con practicas interesantes.
> 
> Saludos.

Hola saludos, a ver si te comprendo, te refieres a los botones que ya estan establecidos por whatsapp o a links agregados por tu cuenta?

o si colocas algun ejemplo de captura por aqui.

**Comment by gchirinos** [comment]
Hola, muchas gracias por responder. Claro que si mira.

![image](https://user-images.githubusercontent.com/27529130/206217505-0585cbd8-468a-42da-a750-b12360ce477e.png)

![image](https://user-images.githubusercontent.com/27529130/206239634-3a9f3eea-2587-4474-8827-2ee70d28ccb1.png)

Me refiero a ese botón que uno configura.

¿Habrá la manera de poder capturar cuando alguien espiche ese botón desde el WebHook?

Saludos.

**Comment by vinixcode** [comment]
Hola @gchirinos ! 

Te cuento que la API de WhatsApp propiamente no te envia ninguna notificacion cuando hacen click en un boton. Sin embargo, tu mismo puedes usar algun servicio como por ejemplo bit.ly (o similares) para generar enlaces personalizados y configurar un webhook que te notifique cada vez que alguien visite un enlace.

Tambien puedes crear enlaces individuales para cada persona, de manera que puedas leer la URL que se visito y basado en eso saber que usuario fue el que visito el link.

Aqui puedes ver por ejemplo como hacerlo con bit.ly AUNQUE existen muchas mas soluciones: https://dev.bitly.com/docs/tutorials/create-a-webhook/

Gracias por tus comentarios y gracias @RAGUDIG por tu ayuda siempre!
