### ISSUE TITLE
ngrok

### ISSUE THREAD

**Issue by quimrp** [Vinix-Code-Dev/curso-api-whatsapp-frontend#14]
Hello
 I'm Quim from Spain
I have a problem with the ngrok security warning before accessing the webhook url
Does anyone know how to remove that?
thanks for your help

<img width="1559" alt="Captura de pantalla 2022-12-10 a las 21 18 04" src="https://user-images.githubusercontent.com/99123455/206873806-d7b0becb-4573-4db4-979a-ac394ec1b7a7.png">

**Comment by vinixcode** [comment]
Hi Quim,
Here's the solution! https://ngrok.com/docs/integrations/whatsapp/webhooks

**Comment by quimrp** [comment]
this is a paid solution

Isn't there a free way to do it??

**Comment by ysernah** [comment]
> this is a paid solution
> 
> Isn't there a free way to do it??

Exacto la solucion segun vi tienes que pagar

**Comment by ysernah** [comment]
> Hello I'm Quim from Spain I have a problem with the ngrok security warning before accessing the webhook url Does anyone know how to remove that? thanks for your help
> 
> <img alt="Captura de pantalla 2022-12-10 a las 21 18 04" width="1559" src="https://user-images.githubusercontent.com/99123455/206873806-d7b0becb-4573-4db4-979a-ac394ec1b7a7.png">

a mi tambien me salio ese mensaje solo tienes que darle en visit site

**Comment by skarpov** [comment]
> Hello I'm Quim from Spain I have a problem with the ngrok security warning before accessing the webhook url Does anyone know how to remove that? thanks for your help
> 
> <img alt="Captura de pantalla 2022-12-10 a las 21 18 04" width="1559" src="https://user-images.githubusercontent.com/99123455/206873806-d7b0becb-4573-4db4-979a-ac394ec1b7a7.png">

Hola.
A mi tambien me pasa lo mismo. Al probar el Webhook en navegador me sale esto. Puede ser esto lo que no me permite verificar el Webhook en facebook? Al poner el url de grok en facebook para verificar me sale error "No se ha podido validar la URL de devolución de llamada ni el identificador de verificación. Comprueba la información proporcionada o vuelve a intentarlo más tarde". Que puedo hacer?

**Comment by ysernah** [comment]
> 



> > Hello I'm Quim from Spain I have a problem with the ngrok security warning before accessing the webhook url Does anyone know how to remove that? thanks for your help
> > <img alt="Captura de pantalla 2022-12-10 a las 21 18 04" width="1559" src="https://user-images.githubusercontent.com/99123455/206873806-d7b0becb-4573-4db4-979a-ac394ec1b7a7.png">
> 
> Hola. A mi tambien me pasa lo mismo. Al probar el Webhook en navegador me sale esto. Puede ser esto lo que no me permite verificar el Webhook en facebook? Al poner el url de grok en facebook para verificar me sale error "No se ha podido validar la URL de devolución de llamada ni el identificador de verificación. Comprueba la información proporcionada o vuelve a intentarlo más tarde". Que puedo hacer?

Puedes enviar una imagen del error  porque tambien tengo ese problema no e podido validar con ngrok  el webhook en facebok lo que hice es adquirir dominio y hosting ahi si me valida

**Comment by skarpov** [comment]
![webhook](https://user-images.githubusercontent.com/1853301/207813058-ce86d1f5-60dc-4e7c-a097-8b3e6cb8d9da.jpg)
Este error me sale

**Comment by ysernah** [comment]
> ![webhook](https://user-images.githubusercontent.com/1853301/207813058-ce86d1f5-60dc-4e7c-a097-8b3e6cb8d9da.jpg) Este error me sale

has verificado que la ruta esta bien y este en web.php
![image](https://user-images.githubusercontent.com/43530180/207870611-a8d8df82-c69d-46f2-98d6-5c432f353fff.png)

**Comment by quimrp** [comment]
No es ningun error
Ngrok ha implementado este aviso para las cuentas gratuitas 
La unica solucion es pagar un subscripcion

**Comment by ysernah** [comment]
> No es ningun error Ngrok ha implementado este aviso para las cuentas gratuitas La unica solucion es pagar un subscripcion
entonces otra alternativa a ngrok?

**Comment by skarpov** [comment]
> > ![webhook](https://user-images.githubusercontent.com/1853301/207813058-ce86d1f5-60dc-4e7c-a097-8b3e6cb8d9da.jpg) Este error me sale
> 
> has verificado que la ruta esta bien y este en web.php ![image](https://user-images.githubusercontent.com/43530180/207870611-a8d8df82-c69d-46f2-98d6-5c432f353fff.png)

Yo no lo hago en Laravel. Lo hago con Apache Tomcat y Java. He creado un RESTful webservice de tipo get que devuelve el parametro hub.challenge. Y funcciona accedendo desde local y desde fuera. Pero no pasa la verificacion en Facebook. 
Esto es el codigo. Se devuelve lo que necesita el Facebook:
	@GET
	@Path("/whatsapp-webhook")
	@Produces(MediaType.TEXT_PLAIN)
	public String verifyWebhook(
								@QueryParam("hub.challenge") int challenge,
								@QueryParam("hub.mode") String mode,
								@QueryParam("hub.verify_token") String verify_token) {
		try {
			String VerifyToken = "MiToken";
		}catch(Exception e) {
		}
		return String.valueOf(challenge);
	}


@vinixcode Ayuda porfa.

**Comment by ysernah** [comment]
Pero la imagen que mandaste estas llendo a la ruta   /webhook  la ruta es /whatsapp-webhook claro eso depende como lo hayas escrito en tu api

**Comment by skarpov** [comment]
> Pero la imagen que mandaste estas llendo a la ruta /webhook la ruta es /whatsapp-webhook claro eso depende como lo hayas escrito en tu api

No no. La imagen es de ayer y la ruta la tenia  /webhook. Hoy la he cambiado a /whatsapp-webhook pero el error sigue igual

**Comment by quimrp** [comment]
no es un error de codigo
lo que sucede es que antes de acceder a la url correcta ngrok muestra el aviso y facebook lo interpreta como una url equivocada

**Comment by skarpov** [comment]
> no es un error de codigo lo que sucede es que antes de acceder a la url correcta ngrok muestra el aviso y facebook lo interpreta como una url equivocada

Pues eso. Entonces ngrok no sirve para nada en la version gratuita. No sé como esta la cosa en la version de pago.

**Comment by vinixcode** [comment]
Caballeros, es cierto que ngrok recientemente introdujo esos cambios pero ngrok no es la unica opcion.

Pueden ver por ejemplo este enlace: https://www.softwaretestinghelp.com/ngrok-alternatives/ (Localtunnel es una opcion que yo he usado y recomiendo, pero existen mas opciones).

**Comment by ysernah** [comment]
Acabo de probar con localtunnel y me sigue saliendo el mismo error
![image](https://user-images.githubusercontent.com/43530180/208198659-272a24d5-b819-4c07-b943-770ece18b96d.png)

**Comment by quimrp** [comment]
Localtunel da el mismo error
@vinixcode  podrias buscar una solucion definitiva y hacer un video de como configurarla???

**Comment by ysernah** [comment]
> Localtunel da el mismo error @vinixcode podrias buscar una solucion definitiva y hacer un video de como configurarla???

Ya me valido con ngrok con este comando al parecer es la region prueba ngrok http 8000 --region us

**Comment by vinixcode** [comment]
Gracias @ysernah !

@skarpov @quimrp Podrían intentar por favor con el comando que @ysernah publicó en el último comentario?

Gracias

**Comment by skarpov** [comment]
No ha cambiado nada. Sigue saliendo el aviso

**Comment by skarpov** [comment]
Pero si que ha validado el Facebook mi webhook. Arreglado

**Comment by zemanuel** [comment]
Buenas tardes, gracias a agregar --region us me anduvo la validación de Facebook, pero notificaciones no me llegan, alguien sabe que se puede hacer? Cuando pruebo la suscripción sí funciona el webhook. Muchas gracias

Actualizo 24/12/2022 en el sitio de ayuda de Ngrok dice lo siguiente:
Note: This integration requires an ngrok Pro or Enterprise license because Facebook validates your ngrok domain and certificate.

**Comment by quimrp** [comment]
Hola 
puedo confirmar que utilizando la region us funciona

ngrok http 8000 --region us

**Comment by vinixcode** [comment]
Para futuras personas que tengan este problema, la solución es la que @ysernah nos reporto, correr el comando con la region US:

`ngrok http 8000 --region us`
