### ISSUE TITLE
no guarda image en storage ni en la base de datos

### ISSUE THREAD

**Issue by darkcam** [Vinix-Code-Dev/curso-api-whatsapp-frontend#15]
Buena tarde comunidad

estoy realizando el video # 20 del curso y hago los pasos pero no me guarda en el storage ni en la base de datos aca les envio el codigo para ver que error puedo tener.

funcion downloadMedia -> Whatsapp.php

![WhatsApp Image 2022-12-13 at 3 13 28 PM](https://user-images.githubusercontent.com/7487937/207434803-3ac713b4-24b2-41d1-ad31-6d114b4319d0.jpeg)

funcion processWebhook -> MessageController.php

![WhatsApp Image 2022-12-13 at2 3 13 28 PM](https://user-images.githubusercontent.com/7487937/207434917-9d2c75bd-ab01-44e2-808e-7932f416c3ea.jpeg)

PS D:\Documentos\projects\whatsapp\api-whatsapp> php artisan storage:link
The [D:\Documentos\projects\whatsapp\api-whatsapp\public\storage] link has been connected to 
       [D:\Documentos\projects\whatsapp\api-whatsapp\storage\app/public].
The links have been created.

**Comment by darkcam** [comment]
ya pude solucionar el problema

**Comment by vinixcode** [comment]
Perfecto @darkcam - cerrare el ticket.
