### ISSUE TITLE
ERROR CLASE 5 (LARAVEL)

### ISSUE THREAD

**Issue by juansastoque** [Vinix-Code-Dev/curso-api-whatsapp-frontend#16]
Buenos dias, disculpe tengo un problema con la instalacion de laravel, ya descargue composer, xampp las cosas que necesita laravel para poder utilizar e instalar tengo una imac del 2009 que no soporta el big sur, no es mala maquina pero no lo soporta, no hay forma de poder trabajar con ese equipo?, porque por los videos que he buscvado se necesita el big sur. Por fa necesito ayuda porque si he hecho todo al pie de la letra pero no se he podido avanzar

**Comment by vinixcode** [comment]
Juan, entiendo tu situacion. Te sugiero que instales docker y asi podras tener un contenedor con los programas que necesitas.
Mira Laravel Sail que te permite hacer esto: https://laravel.com/docs/8.x/sail
