### ISSUE TITLE
Cannot set properties of null (setting 'header') video # 25

### ISSUE THREAD

**Issue by darkcam** [Vinix-Code-Dev/curso-api-whatsapp-frontend#17]
me da este error a la hora de hacer la validacion de la seleccion de la plantialla si estan aprovadas  me dice que no puede estar nulo en header.

Cannot set properties of null (setting 'header')

![WhatsApp Image 2022-12-14 at 4 28 00 PM](https://user-images.githubusercontent.com/7487937/207718955-c7c37548-6c02-49b9-a083-2df7b2a7ece7.jpeg)

codigo del error

![WhatsApp Image 2022-12-14 at 4 31 21 PM](https://user-images.githubusercontent.com/7487937/207719182-748ee30a-1d54-44a4-a2ab-a6a4951b4f41.jpeg)

**Comment by vinixcode** [comment]
@darkcam podrias compartir todo el codigo del archivo?

Igual aqui te comparto el codigo final de ese archivo en el curso para que mires que te puede faltar: https://gist.github.com/vinixcode/a4b352b85f95d56ec8251943a946ae87
