### ISSUE TITLE
seccion de chatbot

### ISSUE THREAD

**Issue by darkcam** [Vinix-Code-Dev/curso-api-whatsapp-frontend#18]
Buena tarde

me gusto mucho el contenido de chatbot del curso si me gustaria que hiciera una seccion haciendo la integracion con el frontend para ver la funcionalidad del bandend en la un entorno de usuario final para le menajo de arbol hacia se solo para texto 

graias por su atencion .

**Comment by vinixcode** [comment]
@darkcam La verdad es que crear un frontend para el chatbot como el de Wasapi requiere muchísimo trabajo y no lo cubrimos en el curso debido a que no está relacionado directamente con la API de WhatsApp, sino que ya es programación en VueJS y está fuera del alcance del curso.

Sin embargo, te invito a que intentes hacer tu propia integración usando alguna librería de drag-and-drop (arrastrar y soltar) como por ejemplo esta https://github.com/SortableJS/Vue.Draggable
