### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by JoseManuelSandona** [Vinix-Code-Dev/curso-api-whatsapp-frontend#19]
Estimados espero se encuentren bien, necesito comunicarme con ustedes ya que compre el codigo, pero no logro la comunicacion por mail, por cual otro canal de comunicacion puedo hablar con ustedes?

**Comment by vinixcode** [comment]
Hola Jose! Te enviamos un correo con la informacion de acceso al codigo.

¿Podrías verificar por favor? Gracias!

**Comment by JoseManuelSandona** [comment]
Excelente! Gracias por todas las soluciones! un exito tener su respuesta!
