### ISSUE TITLE
Envio mensajes tipo audio no llegan

### ISSUE THREAD

**Issue by pcarvajalr** [Vinix-Code-Dev/curso-api-whatsapp-frontend#2]
estoy subiendo los audios al cloud y generando el id_media, pero cuando envio el mensaje tipo audio con ese id_media no llegan, si los envio tipo document si llegan, lo mismo me pasa si los envio con url.  Los he grabado en todos los formatos y nada. estoy grabando con RecordRTC.
alguna libreria para angular para grabar? u otra manera de poder enviar audios?

**Comment by vinixcode** [comment]
Te sugiero que empieces inicialmente a enviar audios pre-grabados - archivos. Aqui puedes ver los formatos soportados: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media#supported-media-types

Debe ser uno de esos, sino el archivo no se enviara.
