### ISSUE TITLE
ngrok does't work

### ISSUE THREAD

**Issue by zemanuel** [Vinix-Code-Dev/curso-api-whatsapp-frontend#20]
Buenas tardes, gracias a agregar --region us me anduvo la validación de Facebook, pero notificaciones no me llegan, alguien sabe que se puede hacer? Cuando pruebo la suscripción sí funciona el webhook. Muchas gracias

Actualizo 24/12/2022 en el sitio de ayuda de Ngrok dice lo siguiente:
Note: This integration requires an ngrok Pro or Enterprise license because Facebook validates your ngrok domain and certificate.

**Comment by ysernah** [comment]
> Note: This integration requires an ngrok Pro or Enterprise license because Facebook validates your ngrok domain and certificate.
yo he probado y todo normal donde te aparece ese mensaje manda foto

**Comment by vinixcode** [comment]
Hola @zemanuel estas utilizando un numero de telefono de produccion o uno de prueba?
Lo mas seguro es que tu problema sea este, y apenas empezo a ocurrir hace un par de semanas a raiz de un cambio de Facebook:

https://youtu.be/SRbq5yWKyfA

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
