### ISSUE TITLE
Catalogos

### ISSUE THREAD

**Issue by Surferg** [Vinix-Code-Dev/curso-api-whatsapp-frontend#22]
Hola, compré el curso para acceder a información avanzada pero no encuentro nada relacionado a cómo integrar un catálogo de meta a la api whatsapp. Por favor, necesito me expliques cómo realizarlo. En la documentación encontré los json a enviar para mensaje type catalog, donde pide el catalog_id y el product_retailer_id pero he probado de muchas formas y no logro que funcione. Me tira error de catalog_id.  Muchas gracias

**Comment by vinixcode** [comment]
Hola @Surferg ! En el plan de contenido del curso no teníamos contemplado hablar sobre la integración e-commerce de la API de WhatsApp (es decir los catálogos) pero la verdad nos encanta la idea de hablar sobre ese tema!

Estaremos trabajando en esto en las próximas semanas y te notificaremos cuando la lección esté disponible. Gracias por la sugerencia!

**Comment by Surferg** [comment]
Ok, muchas gracias! Estamos en contacto. Buen año.
Saludos

**Comment by vinixcode** [comment]
Cerrando ticket. Sera notificado una vez esta leccion este disponible en el curso.
