### ISSUE TITLE
Enviar Video de Youtube

### ISSUE THREAD

**Issue by Surferg** [Vinix-Code-Dev/curso-api-whatsapp-frontend#23]
Hola Juan Esteban, cómo estás? Quisiera consultarte en el caso de querer enviar videos de youtube por la api de whatsapp, cómo se hace. No logré hacerlo. Hasta ahora sólo lo pude hacer sólo como enlace, pero no queda embebido sino simplemente como enlace. He leído en la documentación que, para enviar video, habría que enviar el tipo de video:
"When we request the media asset from your server you must indicate the media's MIME type by including the Content-Type HTTP header. For example: Content-Type: video/mp4". Eso no sé como hacerlo en este tipo de requests.
Te copio fragmentos de mi código, el cuerpo de la petición y el post con http que está dentro de la clase que realiza el envío del mensaje. Muchas gracias.

if($mesgType == 'video'){
    $messageToSend = [
        'messaging_product' => 'whatsapp',
        'recipient_type' => 'individual',
        'to' => ''.$recipient_phone.'',
        'type' => 'video',
        'video' => [
            "link" => $messageArray[1],
          ]
    ];
}

#=======

$message = Http::withToken($token)->post('https://graph.facebook.com/'.$version.'/'.$phone_id.'/messages', $messageToSend)->throw()->json();

**Comment by vinixcode** [comment]
Hola @Surferg no es posible enviar un video de youtube por WhatsApp y que quede embebido, a menos de que descargues el video (por ejemplo en formato mp4) y directamente lo envies por WhatsApp como un archivo normal. Si envias el enlace, WhatsApp siempre lo mostrara como un link externo.

Asegurate tambien de no exceder los limites de tamaño por archivo que tiene la API (esto lo mencionamos en el curso).
