### ISSUE TITLE
Content-Type	text/html; charset=UTF-8

### ISSUE THREAD

**Issue by quimrp** [Vinix-Code-Dev/curso-api-whatsapp-frontend#24]
hola,
al  recibir un mensaje la api me da un error 500 y al momento el solo me hace otra peticion y me da 200 ok
la unica diferencia que veo en el inspector es que

 en el error 500 me aparece en headers  "Content-Type | text/html; charset=UTF-8"
en la siguiente peticion me da 200 ok  y en headers "Content-Type | application/json"
la segunda peticion me llega automaticamente en unos milisegundos sin hacer nada 
![Sin título](https://user-images.githubusercontent.com/99123455/210544535-02018140-ba1f-4051-8b59-7f6bbefda0aa.jpg)
![api_error2](https://user-images.githubusercontent.com/99123455/210544574-b73ded99-153e-465e-9453-a21ee2db90e0.jpg)

**Comment by vinixcode** [comment]
@quimrp podrias mostrar por favor la parte donde dice Summary en la peticion con el error 500? Es para ver cual es el error que arroja Laravel y que esta causando este 500.

**Comment by quimrp** [comment]
claro, parece que paso toda la informacion correctamente, yo diria que es identica a la peticion 200
adjunto captura
![Captura de pantalla 2023-01-04 a las 14 04 37](https://user-images.githubusercontent.com/99123455/210561295-c64dde29-d16c-4f3a-9809-fe4c6e975ac3.png)


esta es la captura del a segunda peticion con el codigo 200
![Captura de pantalla 2023-01-04 a las 14 04 45](https://user-images.githubusercontent.com/99123455/210561509-70bb06d2-4354-4552-bd2f-a27e5de93278.png)

la segunda petición que viene ok la hace facebook supongo al no poder procesar la primera lo reintente y la segunda viene con código 200 por lo que en mi código no hay ninguna modificación

**Comment by vinixcode** [comment]
@quimrp me referia a la pestaña "Summary" de la respuesta del servidor, en vez de la petición. Es decir a la pestaña Summary que aparece debajo de "500 Internal Server Error

<img width="400" alt="image" src="https://user-images.githubusercontent.com/63106073/211021708-2cb10bbf-f0c5-4f3d-9dd8-92004522d4a2.png">

Disculpa la confusion!

**Comment by quimrp** [comment]
ok @vinixcode , ya lo pense pero no pude adjuntarlo porque el codigo es demasiado largo
te lo paso como adjunto

**Comment by vinixcode** [comment]
Quedo atento a recibir el archivo adjunto @quimrp

**Comment by vinixcode** [comment]
Cerrando por inactividad.
