### ISSUE TITLE
No me aparece el contenido en POSTMAN

### ISSUE THREAD

**Issue by juansastoque** [Vinix-Code-Dev/curso-api-whatsapp-frontend#25]
Hola buen dia bro que tal?, bro veras ya logre instalar el laravel y ya instale el postman tambien pero en el menu de ¨enviroment¨ no me sale el contenido y ya busque tambien que pasa porque no me aparece pero no lo logro,  de pronto vos no me podes ayudar con una llamada zoom o algo para poder explicarte mejor la situacion?

**Comment by vinixcode** [comment]
Hola @juansastoque podrias por favor publicar un video grabando tu pantalla y explicando exactamente el problema? No estoy seguro de entender exactamente a que te refieres. Gracias!
