### ISSUE TITLE
formatear código respuesta del servidor

### ISSUE THREAD

**Issue by quimrp** [Vinix-Code-Dev/curso-api-whatsapp-frontend#26]
Hola, buenos dias
alguien me puede decir como puedo darle un formato más visual al código respuesta del servidor??
adjunto pantallazo de como me aparece en chrome

<img width="1680" alt="Captura de pantalla 2023-01-05 a las 9 34 37" src="https://user-images.githubusercontent.com/99123455/210736428-1125dac9-0163-4ef5-8155-f9195f2fcaa1.png">

así es como aparece en el video de la clase 13
<img width="1680" alt="Captura de pantalla 2023-01-05 a las 9 36 55" src="https://user-images.githubusercontent.com/99123455/210737047-2e95a434-6395-411d-aced-003bb7ef3e5a.png">

¿como se formatea para verlo así? 
¿es alguna extensión del navegador?

seguro que es una chorrada pero no se como configurarlo
gracias por la ayuda!!!

**Comment by vinixcode** [comment]
Hola @quimrp 

Si, yo uso una extension llamada JSON Viewer para Chrome (https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh). Solo tienes que instalarla y ya! Saludos!
