### ISSUE TITLE
Clase 13 - error "Type is not supported"

### ISSUE THREAD

**Issue by ChrisMP05** [Vinix-Code-Dev/curso-api-whatsapp-frontend#27]
Buenas mirando el video 13 aparece asi, estoy usando la base de datos postgredsql

![image](https://user-images.githubusercontent.com/113645264/211065694-9bf97235-0f5d-40a9-bdee-c727f2ee05fd.png)
 pero a mi, me aparece ese error:

![image](https://user-images.githubusercontent.com/113645264/211065776-52943468-8326-4021-8bc8-ff38c5098098.png)

codigo:

![image](https://user-images.githubusercontent.com/113645264/211065917-47fff7b8-ab41-43ca-95dd-d195a9fa5e00.png)

alguna ayuda @vinixcode

**Comment by vinixcode** [comment]
@ChrisMP05 personalmente no tengo mucho conocimento de PostgreSQL así que lamentablemente no te podría ayudar! Te sugiero buscar en Google, pero parece ser algo incompatible con el query que se está haciendo.

**Comment by ChrisMP05** [comment]
ok gracias

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
