### ISSUE TITLE
 Recibir los posts de los webhooks de notificación

### ISSUE THREAD

**Issue by Surferg** [Vinix-Code-Dev/curso-api-whatsapp-frontend#28]
Hola, espero que estés muy bien. tengo la siguiente consulta. Quiero hacerlo en php puro (no con Laravel), y me falta un único eslabón para poder continuar avanzando. Cómo hago para recibir los posts de los webhooks de notificación. Pude hacer la función de verificación correctamente del modo que copio a continuación, pero me desorienta bastante el obtener los datos de los webhooks. Agradezco mucho tu respuesta.
if ($_SERVER['REQUEST_METHOD'] == "GET") {
  $verifyToken = 'webhook';
  $mode = $_GET['hub_mode'];
  $token = $_GET['hub_verify_token'];
  $challenge = $_GET['hub_challenge'];
  if ($mode && $token) {
    if ($mode == 'subscribe' && $token == $verifyToken) {
      header("HTTP/1.1 200 OK");
      header('Content-Type', 'text/plain');
      echo $challenge;
    }
  }
  
}

**Comment by vinixcode** [comment]
@Surferg debes leer también el cuerpo de la petición. En PHP puro lo podrías hacer así: 

`$body = file_get_contents('php://input');`

Pero como el cuerpo viene codificado en JSON, debes descodificarlo. Por ejemplo con:

`$body = json_decode($body);`

Espero te sirva, saludos.

**Comment by Surferg** [comment]
Hola, pero al llegar el webhook no entra dentro de un if
($_SERVER["REQUEST_METHOD"] == "POST")  No lo entiendo.




 controlplagas.com.ar




*Antes de imprimir este mensaje, por favor, compruebe que es necesario
hacerlo. Una tonelada de papel implica la tala de 15 árboles y el consumo
de 250.000 litros de agua.  *

*El medio ambiente es cuestión de todos.*

**Comment by Surferg** [comment]
Perdón, no dije nada, ya lo resolví. Era un error mío de escritura. Gracias!



 controlplagas.com.ar




*Antes de imprimir este mensaje, por favor, compruebe que es necesario
hacerlo. Una tonelada de papel implica la tala de 15 árboles y el consumo
de 250.000 litros de agua.  *

*El medio ambiente es cuestión de todos.*
