### ISSUE TITLE
webhook error CLASE N° 7

### ISSUE THREAD

**Issue by ysernah** [Vinix-Code-Dev/curso-api-whatsapp-frontend#3]
Buenos dias 

Tengo un error al hacer peticion con mi url al webhook
https://miurl/whatsapp-webhook

me retorna indefinido hub_mode

{"success":false,"error":"Undefined array key \"hub_mode\""}

**Comment by vinixcode** [comment]
Este campo hub_mode unicamente se pasa al momento de verificar el endpoint del webhook, cuando uno pone la URL en Facebook. Asegurate de que tengas bien configurado el endpoint para las peticiones GET y las peticiones POST.

Vuelve a ver el video por favor, de ser necesario.

**Comment by ysernah** [comment]
Gracias realice de nuevo y tambien en las peticiones post y get me sale esto
{
    "success": false,
    "error": "Trying to access array offset on value of type null"
}

**Comment by ysernah** [comment]
Gracias la validacion del token y ruta si acepto en facebook pero no recibo datos del webhook como el 
subscribe el numero de challenge y el token me sigue saliendo el mismo error cuando hago el post me sale esto estoy utilizando Laravel v9.39.0 (PHP v8.0.25)
**{
    "success": false,
    "error": "Trying to access array offset on value of type null"
}**
y en el get me sale esto

**{
    "success": false,
    "error": "Undefined array key \"hub_mode\""
}**


**Esta es mi ruta** 
Route::post('/whatsapp-webhook',[TestController::class,'processWebhook']);
**Este es mi controlador**

 public function processWebhook(Request $request)
        {
            try{
                $bodyContent =json_decode($request->getContent(),true);
        
                $value =$bodyContent['entry'][0]['changes'][0]['value'];
        
                if(!empty($value['messages'])){
                 if($value['messages'][0]['type']=='text'){
                    $body=$value['messages'][0]['text']['body'];
                 }
                }
                return response()->json([
                    'success'=> true,
                    'data' => $body,
                    ],200);
            }
        
            catch (Exception $e){
                return response()->json([
                    'success'=> false,
                    'error' => $e->getMessage(),
                    ],500);
            }
        }

**Comment by vinixcode** [comment]
Por favor intenta instalar XDebug en tu instalacion de PHP y en VS Code. Asi podras revisar linea por linea y ver donde esta el error. Tambien pega aqui el controlador completo por favor para mirar el codigo.

El error consiste en que estas intentando acceder a un indice que no existe dentro del array.

**Comment by RAGUDIG** [comment]
> Por favor intenta instalar XDebug en tu instalacion de PHP y en VS Code. Asi podras revisar linea por linea y ver donde esta el error. Tambien pega aqui el controlador completo por favor para mirar el codigo.
> 
> El error consiste en que estas intentando acceder a un indice que no existe dentro del array.

Tengo el mimso error en el verifyWebhook

mi codigo:
public function verifyWebhook(Request $request)
    {
        try {

            $verifyToken = 'seodigwhatsapp2022!';
            $query = $request->query();

            $mode = $query['hub_mode'];
            $token = $query['hub_verify_token'];
            $challenge = $query['hub_challenge'];

            if ($mode && $token){
                if($mode === 'subscribe' && $token == $verifyToken){
                  return response($challenge, 200)->header('Content-Type', 'text/plain');  
                }
            }

            throw new Exception('Invalid request');

        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

Route::get('/whatsapp-webhook', [TestController::class, 'verifyWebhook']);
![Captura](https://user-images.githubusercontent.com/44486594/202860139-4f2dfd7e-d943-4299-889d-8043f61f099f.PNG)

**Comment by RAGUDIG** [comment]
> Buenos dias
> 
> Tengo un error al hacer peticion con mi url al webhook https://miurl/whatsapp-webhook
> 
> me retorna indefinido hub_mode
> 
> {"success":false,"error":"Undefined array key "hub_mode""}

veo que lo solucionestes, cual era tu error?

**Comment by ysernah** [comment]
Todavia no lo he solucionado como dijo el profesor voy a intalar  XDebug

**Comment by vinixcode** [comment]
Lograron solucionar el problema?

**Comment by ysernah** [comment]
Profesor no pude resolver me sale ese mensaje pense que era ngrok porque tambien lo probe con un dominio y hosting y me sigue saliendo ese mensaje 
{
"success": false,
"error": "Undefined array key "hub_mode""
}

**Comment by RAGUDIG** [comment]
> Lograron solucionar el problema?

aun nada estimado, si pudieras dar alguna idea

**Comment by RAGUDIG** [comment]
> Contributor

![image](https://user-images.githubusercontent.com/44486594/203175405-da788f96-4142-4c23-aad5-68717a9a51e8.png)
el dd($query); me lo debuelve vacio

**Comment by RAGUDIG** [comment]
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\Console;
use Illuminate\Support\Facades\Log;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        //
    }


    public function sendMessages()
    {
        try {
            $token = 'EAAL5ooFh2ZC4BAGezCf6NoAEwoOwMncnqT1hBJNFZAfAzZAmQEphRmAUZAnER52XEYi8xQ2zB2EJPnJXL0QbG2Hpe4a5M91Us3AvcEGOFdHj2wbRz3WThRHyL3JtZB9aJ9vEFwowJan8k5p79BFBWIMDsPX2tJfPTaN8HKkAzsxt2filVO5vD7UJVgSxWiRZAtEcz0rE1QxQZDZD';

            $idphone = '103212882583619';
            $version = 'v15.0';

            $payload = [
                /*"messaging_product" => "whatsapp",
                "to" => "50496721569",
                "type" => "template",
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]**/  

                "messaging_product" => 'whatsapp',
                "to" => '50496721569',
                "type" => 'template',
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]
            ];


            $message = Http::withToken($token)->post('https://graph.facebook.com/' . $version . '/' . $idphone . '/messages', $payload)->throw()->json();
            dd($message);
            return response()->json([
                'success' => true,
                'data' => $message,
            ], 200);
        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'data' => $e->getMessage(),
            ], 500);
        }
    }

    public function verifyWebhook(Request $request)
    {
        try {

            $verifyToken = 'seodigwhatsapp2022!';
            $query = $request->query();
            #dd($query);

            $mode = $query['hub_mode'];
            $token = $query['hub_verify_token'];
            $challenge = $query['hub_challenge'];

            if ($mode && $token){
                if($mode === 'subscribe' && $token == $verifyToken){
                  return response($challenge, 200)->header('Content-Type', 'text/plain'); 
                }
            }


            throw new Exception('Invalid request');

        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    
    public function processWebhook(Request $request)
    {
        try {
            $bodyContent = json_decode($request->getContent(), true);
            $value = $bodyContent['entry'][0]['changes'][0]['value']; 

            if (!empty($value['messages'])){
                $exists = Message::where('wam_id', $value['messages'][0]['id']->first());

                if(empty($exists->id)){
                    if($value['messages'][0]['type'] == 'text'){
                        $message = $this->_saveMessage(
                            $value['messages'][0]['text']['body'],'text',
                            $value['messages'][0]['from'],
                            $value['messages'][0]['id'],
                            $value['messages'][0]['timestamp']
                        );
                    }else {
                        $type = $value['messages'][0]['type'];
                        if (!empty($value['messages'][0][$type])){
                            $message = $this->_saveMessage(
                        "($type): \n _" . serialize($value['messages'][0][$type]) . "_", 'other',
                                $value['messages'][0]['from'],
                                $value['messages'][0]['id'],
                                $value['messages'][0]['timestamp']
                            );
                        }
                    }
                }
            } 

            return response()->json([
                'success' => true,
            ], 200);

        } 
        catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    private function _saveMessage($message, $messageType, $waid, $wamid, $timestamp = null, $caption = null, $data = ''){

        $wam = new Message();
        $wam ->body = $message;
        $wam ->outgoing = false;
        $wam ->type = $messageType;
        $wam ->wa_id = $waid;
        $wam ->wam_id = $wamid;
        $wam ->status = 'sent';
        $wam ->caption = $caption;
        $wam ->data = $data;

        if (!is_null($timestamp)){
            $wam->created_at = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
            $wam->updated = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
        }

        $wam->save();

        return $wam;
    }
}

**Comment by RAGUDIG** [comment]
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\Console;
use Illuminate\Support\Facades\Log;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        //
    }


    public function sendMessages()
    {
        try {
            $token = 'EAAL5ooFh2ZC4BAGezCf6NoAEwoOwMncnqT1hBJNFZAfAzZAmQEphRmAUZAnER52XEYi8xQ2zB2EJPnJXL0QbG2Hpe4a5M91Us3AvcEGOFdHj2wbRz3WThRHyL3JtZB9aJ9vEFwowJan8k5p79BFBWIMDsPX2tJfPTaN8HKkAzsxt2filVO5vD7UJVgSxWiRZAtEcz0rE1QxQZDZD';

            $idphone = '103212882583619';
            $version = 'v15.0';

            $payload = [
                /*"messaging_product" => "whatsapp",
                "to" => "50496721569",
                "type" => "template",
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]**/  

                "messaging_product" => 'whatsapp',
                "to" => '50496721569',
                "type" => 'template',
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]
            ];


            $message = Http::withToken($token)->post('https://graph.facebook.com/' . $version . '/' . $idphone . '/messages', $payload)->throw()->json();
            dd($message);
            return response()->json([
                'success' => true,
                'data' => $message,
            ], 200);
        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'data' => $e->getMessage(),
            ], 500);
        }
    }

    public function verifyWebhook(Request $request)
    {
        try {

            $verifyToken = 'seodigwhatsapp2022!';
            $query = $request->query();
            #dd($query);

            $mode = $query['hub_mode'];
            $token = $query['hub_verify_token'];
            $challenge = $query['hub_challenge'];

            if ($mode && $token){
                if($mode === 'subscribe' && $token == $verifyToken){
                  return response($challenge, 200)->header('Content-Type', 'text/plain'); 
                }
            }


            throw new Exception('Invalid request');

        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    
    public function processWebhook(Request $request)
    {
        try {
            $bodyContent = json_decode($request->getContent(), true);
            $value = $bodyContent['entry'][0]['changes'][0]['value']; 

            if (!empty($value['messages'])){
                $exists = Message::where('wam_id', $value['messages'][0]['id']->first());

                if(empty($exists->id)){
                    if($value['messages'][0]['type'] == 'text'){
                        $message = $this->_saveMessage(
                            $value['messages'][0]['text']['body'],'text',
                            $value['messages'][0]['from'],
                            $value['messages'][0]['id'],
                            $value['messages'][0]['timestamp']
                        );
                    }else {
                        $type = $value['messages'][0]['type'];
                        if (!empty($value['messages'][0][$type])){
                            $message = $this->_saveMessage(
                        "($type): \n _" . serialize($value['messages'][0][$type]) . "_", 'other',
                                $value['messages'][0]['from'],
                                $value['messages'][0]['id'],
                                $value['messages'][0]['timestamp']
                            );
                        }
                    }
                }
            } 

            return response()->json([
                'success' => true,
            ], 200);

        } 
        catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    private function _saveMessage($message, $messageType, $waid, $wamid, $timestamp = null, $caption = null, $data = ''){

        $wam = new Message();
        $wam ->body = $message;
        $wam ->outgoing = false;
        $wam ->type = $messageType;
        $wam ->wa_id = $waid;
        $wam ->wam_id = $wamid;
        $wam ->status = 'sent';
        $wam ->caption = $caption;
        $wam ->data = $data;

        if (!is_null($timestamp)){
            $wam->created_at = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
            $wam->updated = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
        }

        $wam->save();

        return $wam;
    }
}

**Comment by RAGUDIG** [comment]
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Http\Controllers\Console;
use Illuminate\Support\Facades\Log;

class MessageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function show(Message $message)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        //
    }


    public function sendMessages()
    {
        try {
            $token = 'EAAL5ooFh2ZC4BAGezCf6NoAEwoOwMncnqT1hBJNFZAfAzZAmQEphRmAUZAnER52XEYi8xQ2zB2EJPnJXL0QbG2Hpe4a5M91Us3AvcEGOFdHj2wbRz3';

            $idphone = '10321288258361x';
            $version = 'v15.0';

            $payload = [
                /*"messaging_product" => "whatsapp",
                "to" => "50496721500",
                "type" => "template",
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]**/  

                "messaging_product" => 'whatsapp',
                "to" => '50496721500',
                "type" => 'template',
                "template" => [
                    "name" => "hello_world",
                    "language" => [
                        "code" => "en_US"
                    ]
                ]
            ];


            $message = Http::withToken($token)->post('https://graph.facebook.com/' . $version . '/' . $idphone . '/messages', $payload)->throw()->json();
            dd($message);
            return response()->json([
                'success' => true,
                'data' => $message,
            ], 200);
        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'data' => $e->getMessage(),
            ], 500);
        }
    }

    public function verifyWebhook(Request $request)
    {
        try {

            $verifyToken = 'seodigwhatsapp2022!';
            $query = $request->query();
            #dd($query);

            $mode = $query['hub_mode'];
            $token = $query['hub_verify_token'];
            $challenge = $query['hub_challenge'];

            if ($mode && $token){
                if($mode === 'subscribe' && $token == $verifyToken){
                  return response($challenge, 200)->header('Content-Type', 'text/plain'); 
                }
            }


            throw new Exception('Invalid request');

        } catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    
    public function processWebhook(Request $request)
    {
        try {
            $bodyContent = json_decode($request->getContent(), true);
            $value = $bodyContent['entry'][0]['changes'][0]['value']; 

            if (!empty($value['messages'])){
                $exists = Message::where('wam_id', $value['messages'][0]['id']->first());

                if(empty($exists->id)){
                    if($value['messages'][0]['type'] == 'text'){
                        $message = $this->_saveMessage(
                            $value['messages'][0]['text']['body'],'text',
                            $value['messages'][0]['from'],
                            $value['messages'][0]['id'],
                            $value['messages'][0]['timestamp']
                        );
                    }else {
                        $type = $value['messages'][0]['type'];
                        if (!empty($value['messages'][0][$type])){
                            $message = $this->_saveMessage(
                        "($type): \n _" . serialize($value['messages'][0][$type]) . "_", 'other',
                                $value['messages'][0]['from'],
                                $value['messages'][0]['id'],
                                $value['messages'][0]['timestamp']
                            );
                        }
                    }
                }
            } 

            return response()->json([
                'success' => true,
            ], 200);

        } 
        catch (Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    private function _saveMessage($message, $messageType, $waid, $wamid, $timestamp = null, $caption = null, $data = ''){

        $wam = new Message();
        $wam ->body = $message;
        $wam ->outgoing = false;
        $wam ->type = $messageType;
        $wam ->wa_id = $waid;
        $wam ->wam_id = $wamid;
        $wam ->status = 'sent';
        $wam ->caption = $caption;
        $wam ->data = $data;

        if (!is_null($timestamp)){
            $wam->created_at = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
            $wam->updated = Carbon::createFramTimestamp($timestamp)->toDateTimeString();
        }

        $wam->save();

        return $wam;
    }
}

**Comment by ysernah** [comment]
Cambie de version a laravel 8 y php 7 y tambien me sigue saliendo ese error

**Comment by vinixcode** [comment]
Caballeros, estaba de viaje y por fin he vuelto al modo trabajo!
@ysernah podrias por favor grabar un video de exactamente que es lo que estas haciendo para determinar cual es el error?

No se preocupen que este problema lo solucionaremos cueste lo que cueste. Asi nos toque hacer una llamada en vivo y depurar esto juntos!

**Comment by vinixcode** [comment]
Señores revisen este video que grabé para ustedes por favor y revisen si con esto resuelven el problema!
https://vimeo.com/773951222/2b5003ce13

**Comment by vinixcode** [comment]
Acabo de actualizar el video para mencionar algo que puede estar causando problemas con ngrok. Se habla a partir del minuto 10:14. Revisenlo por favor (es el mismo enlace anterior).

**Comment by ysernah** [comment]
gracias profesor lo revisare y le respondere pero una nota cabe precisar que nunca pude verificar el token con ngrok por eso lo hice con domino y hosting ahi si me verifica pero como le decia me salia indefinido  "hub_mode""
voy a ver el video y le aviso

**Comment by RAGUDIG** [comment]
> Acabo de actualizar el video para mencionar algo que puede estar causando problemas con ngrok. Se habla a partir del minuto 10:14. Revisenlo por favor (es el mismo enlace anterior).

yo lo tengo con cuenta estimado, desde un principio y sigo con el mismo problema "hub_mode"".

**Comment by c0rtex** [comment]
Caballeros, si el problema lo está causando ngrok, simplemente usen otra solución que les permita crear túneles al exterior desde sus locales. Aquí hay algunas alternativas: https://www.softwaretestinghelp.com/ngrok-alternatives/

**Comment by RAGUDIG** [comment]
> Caballeros, si el problema lo está causando ngrok, simplemente usen otra solución que les permita crear túneles al exterior desde sus locales. Aquí hay algunas alternativas: https://www.softwaretestinghelp.com/ngrok-alternatives/

no creo sea ngrok

**Comment by ysernah** [comment]
Yo utilice sin ngrok lo hice con un dominio y hosting y me sigue saliendo con ese problema

**Comment by ysernah** [comment]
> Caballeros, si el problema lo está causando ngrok, simplemente usen otra solución que les permita crear túneles al exterior desde sus locales. Aquí hay algunas alternativas: https://www.softwaretestinghelp.com/ngrok-alternatives/

Amigo a ti no te sale ese problema??

**Comment by ysernah** [comment]
Profesor podria crear un grupo de whatsapp o telegram del curso para poder apoyarnos entre todos gracias

**Comment by c0rtex** [comment]
A mi personalmente no me ocurre. Yo sugeriria probar al menos con otra solucion distinta a ngrok y mirar si se soluciona el problema (es muy probable que se solucione).

Gracias @ysernah me gusta la idea! Lo voy a revisar.

**Comment by RAGUDIG** [comment]
o no se si se podria crear entre nosotros, claro si el profesor lo permite, por que pasariamos el link por aqui.

**Comment by ysernah** [comment]
Profesor en el video veo que recibe la peticion pero yo solo resibo esto
![Captura](https://user-images.githubusercontent.com/43530180/203649560-33543e3f-dcc4-4b56-9c58-d144c815267a.PNG)

**Comment by RAGUDIG** [comment]
> Profesor en el video veo que recibe la peticion pero yo solo resibo esto ![Captura](https://user-images.githubusercontent.com/43530180/203649560-33543e3f-dcc4-4b56-9c58-d144c815267a.PNG)

si en el video debuelve true

**Comment by c0rtex** [comment]
Señores tengo disponibilidad para que nos reunamos este lunes 28 de Noviembre a las 4pm hora de Colombia. ¿Les queda bien ese día para que resolvamos las dudas a través de una llamada?

**Comment by RAGUDIG** [comment]
> Señores tengo disponibilidad para que nos reunamos este lunes 28 de Noviembre a las 4pm hora de Colombia. ¿Les queda bien ese día para que resolvamos las dudas a través de una llamada?

Buen dia estimado Juan, me parece bien a esa hora.

Con tu permiso dejo aqui el link de un grupo de whatsapp https://chat.whatsapp.com/Hqtu5KzKk5Y2ocKdiy1gUF para darnos una ayudita entre nosotros.  (si no te parece correcto lo elimino 😬)

**Comment by ysernah** [comment]
Profesor le envio el error que me genera con ngrok no me funciona con mi dominio si me funciona la validacion pero sigue saliendo indefinido

https://user-images.githubusercontent.com/43530180/204660315-771c6777-fd4c-4207-96af-5853a191f36e.mp4

**Comment by vinixcode** [comment]
@ysernah, Pablo Peralta logró solucionar exactamente tu mismo problema siguiendo la documentación oficial de ngrok. Por favor revisa este enlace para ver cómo arreglarlo:

https://ngrok.com/docs/integrations/whatsapp/webhooks

**Comment by vinixcode** [comment]
@RAGUDIG @ysernah con respecto a la reunión del lunes, pensaba realizarla pero solo confirmó @RAGUDIG y hubiera querido que se hubiera sumado más personas para resolver más dudas.

**Comment by ysernah** [comment]
> @ysernah, Pablo Peralta logró solucionar exactamente tu mismo problema siguiendo la documentación oficial de ngrok. Por favor revisa este enlace para ver cómo arreglarlo:
> 
> https://ngrok.com/docs/integrations/whatsapp/webhooks

Profesor pero no utilizo ngrok estoy utilizando dominio y hosting igual me sale indefinido hub mode
![image](https://user-images.githubusercontent.com/43530180/204922084-b2c5acb8-28b1-41b5-b77e-9b2d45d86c76.png)

**Comment by vinixcode** [comment]
@ysernah es imposible para mi diagnosticar el problema de esta manera. Solo es posible hacerlo a través de una llamada en vivo, con acceso remoto al equipo por TeamViewer para poder revisar con tu ayuda que es lo que ocurre.

Es posible realizar mañana la llamada a las 7am de Colombia? O el viernes a las 11am de Colombia.

Ese error es perfectamente normal, y siempre te debe salir si accedes directamente a la URL. La unica manera de saber si funciona o no, es haciendo la peticion directamente desde FB, usando el botón de verificar.

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
