### ISSUE TITLE
Explicación - Actualización en tiempo real (Modulo Chats)

### ISSUE THREAD

**Issue by andresperalta1550** [Vinix-Code-Dev/curso-api-whatsapp-frontend#30]
Hola Juan !! 

Antes que nada agradecerte por el curso tan valioso que has realizado, sin embargo, considero que esta haciendo falta algo muy importante que tiene que ver mucho con este curso, te pido por favor sea explicado, me refiero al como se actualiza en tiempo real la zona de chats que se encuentra ubicada en la izquierda.

Quedo atento, 

<img width="1512" alt="Captura de pantalla 2023-01-12 a la(s) 5 58 55 a m" src="https://user-images.githubusercontent.com/113928825/212051869-b4a1dc5b-63ba-4871-bade-8b77d9511097.png">

**Comment by vinixcode** [comment]
Andrés, gracias por la sugerencia! Lo tendré en cuenta para incluir esta lección adicional próximamente.

De todos modos te invito a que lo intentes hacer tu mismo: ya tenemos Pusher corriendo y nos llega una notificación cada vez que entra un nuevo mensaje. Podemos aprovechar eso, para ejecutar y recargar la función de la sección izquierda que nos muestra la lista de mensajes recibidos.

Buena suerte con ese experimento!
