### ISSUE TITLE
Problema en Clase 12

### ISSUE THREAD

**Issue by luisfernando2022** [Vinix-Code-Dev/curso-api-whatsapp-frontend#31]
Llevo todos los pasos correctos hasta donde se pone el comando npm run dev, me sale el siguiente error:
![image](https://user-images.githubusercontent.com/119472003/212449152-7a910490-4e22-41aa-9dbc-715fc8ad9ff6.png)
¿Alguien tendrá alguna idea para resolverlo?

**Comment by luisfernando2022** [comment]
La solución la encontré en la pagina web https://appdividend.com/2022/12/23/error-03000086-digital-envelope-routines-initialization/.
Para windows se agrega el comando: set NODE_OPTIONS=--openssl-legacy-provider
a continuación se lanza nuevamente el comando "npm run dev" y el programa se ejecuta sin problema.

**Comment by vinixcode** [comment]
Gracias por confirmar @luisfernando2022 !
