### ISSUE TITLE
guardar respuesto

### ISSUE THREAD

**Issue by quimrp** [Vinix-Code-Dev/curso-api-whatsapp-frontend#32]
Hola,
necesito guardar algunas de las respuestas de los clientes en una variable.
cuando utilizo botones de respuesta rapida o listas lo puedo hacer sin problema

¿como puedo hacerlo cuando envio un mensaje normal?

ejemplo:
envío el mensaje" introduce tu código postal"
me gustaria verificar que la respuesta sea un numero y guardarla en una variable

el problema es como vincular la pregunta a la respuesta del usuario, no se si hay algun id o forma de identificarlas
supongo que se puede hacer ya que en manychat lo hago sin ningun problema

gracias por la ayuda

**Comment by vinixcode** [comment]
Hola @quimrp cada mensaje tiene un ID específico, y cuando uno responde a un mensaje referenciando un mensaje anterior, ese ID se pasa via WhatsApp. Me refiero a un mensaje de este tipo:

![IMG_5CADF6B144A8-1](https://user-images.githubusercontent.com/63106073/213068904-f989fb21-04e0-466a-bb01-baef81acaad2.jpeg)

Sino, tienes que enviar el mensaje y suponer que el siguiente mensaje que recibas, es la respuesta a la pregunta que hiciste.
