### ISSUE TITLE
Download media files

### ISSUE THREAD

**Issue by Surferg** [Vinix-Code-Dev/curso-api-whatsapp-frontend#33]
Hola, tengo un problema al tratar de obtener la data multimedia. Te copio mi código, (es en php y curl). La primer request es correcta, trae la response en Json con los datos del archivo y la url, pero en la segunda request trae  html de una pantalla de error. Lo copio debajo de todo. Muchas gracias

    function CurlReq($url, $token){
        $curl = curl_init();
        curl_setopt_array($curl, array(
          CURLOPT_URL => $url,
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'GET',
          CURLOPT_POSTFIELDS =>'{
            "status": "read"
        }',
          CURLOPT_HTTPHEADER => array(
            'Content-Type: application/json',
            'Authorization: Bearer '.$token.''
          ),
        ));
        $response = curl_exec($curl);
        curl_close($curl);
        return $response;
    }
    
$token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

$mediaId = "485784710424235";
$url= 'https://graph.facebook.com/v15.0/'.$mediaId;

$media= CurlReq($url, $token);

if(!empty($media['url'])){
     $conten= CurlReq($media['url'], $token);
     //también probé  json_decode( CurlReq($media['url'], $token), true ); 
     $ext= mimeExt( $media['mime_type'] );
     $file_name= rand(1, 9999999).'-'.time();
 
      file_put_contents($file_name, $conten);
};
#===============================

La response es :

<body>
    <div id="header">
      <a href="//www.facebook.com/">
        <img id="icon" src="//static.facebook.com/images/logos/facebook_2x.png" />
      </a>
    </div>
    <div id="core">
      <h1 id="sorry">**Sorry, something went wrong**.</h1>
      <p id="promise">
        We're working on it and we'll get it fixed as soon as we can.
      </p>
      <p id="back-link">
        <a id="back" href="//www.facebook.com/">Go Back</a>
      </p>
      <div id="footer">
        Facebook
        <span id="copyright">
          &copy; 2022
        </span>
        <span id="help-link">
          &#183;
          <a id="help" href="//www.facebook.com/help/">Help Center</a>
        </span>
      </div>
    </div>

**Comment by Surferg** [comment]
El json_decode lo probé en la segunda request, no en la primera. En $conten.

**Comment by vinixcode** [comment]
Hola @Surferg disculpa la demora para responder - recientemente nació mi segundo hijo y estuve unas semanas lejos de las pantallas!

El error que reportas parecer ser porque no estás pasando el token incluso en la segunda petición. Asegúrate de que en cada petición pases el token para cargar la imagen.

Saludo

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
