### ISSUE TITLE
Clase 18

### ISSUE THREAD

**Issue by AlexanderGoi** [Vinix-Code-Dev/curso-api-whatsapp-frontend#34]
Hola que tal, antes que nada felicitarte por el excelente curso y que gracias a este me he adentrado más en php y laravel.
Tengo un problema a la ahora de probar si funciona la parte de pusher, en la pagina web no se ve nda en el debug, pero por que tengo el error desde el backend, inicio con el queue:work y se ve lo siguiente  a la hora de refrescar la pagina donde se ven las caracteristicas de laravel.

![Imagen 5](https://user-images.githubusercontent.com/58536439/217361423-815fa119-f541-4ce4-9b10-c8e962f16239.png)

![imagen](https://user-images.githubusercontent.com/58536439/217361983-a5b64619-dc4c-4caa-a570-944126e4e2c5.png)

Ya también estuve viendo por mi cuenta, que era por tema de versiones, recomendaban la 7.2.1 del pusher pero sigue sin procesar, falla algo, incluso ya me vi varias veces los videos y cree todo desde cero por si algo le habia movido demás, pero sigo con este problema.

**Comment by vinixcode** [comment]
Hola @AlexanderGoi gracias por tus palabras! Me encanta saber que el curso ha sido de valor para ti.

Podrias revisar el log de Laravel a ver que error te esta dando? Normalmente vas a encontrar el log en el archivo storage/logs/laravel.log (dentro del proyecto de Laravel).

Estare atento, gracias!

**Comment by AlexanderGoi** [comment]
Muchas gracias por la rapida atención.

Tambien me falto mencionar esto

![imagen](https://user-images.githubusercontent.com/58536439/217604442-6eab772f-f70f-4014-9e59-19e122a6e56b.png)

Al final me marca algo de seguridad, no se si también pudiera ser el problema

Este es el log

[2023-02-08 16:58:18] local.ERROR: Pusher error: Timestamp expired: Given timestamp (2023-02-08T16:58:17Z) not within 600s of server time (2023-02-08T17:14:37Z)
. {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: Timestamp expired: Given timestamp (2023-02-08T16:58:17Z) not within 600s of server time (2023-02-08T17:14:37Z)
. at C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster.php:128)
[stacktrace]
#0 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Broadcasting\\BroadcastEvent.php(77): Illuminate\\Broadcasting\\Broadcasters\\PusherBroadcaster->broadcast(Array, 'App\\\\Events\\\\Webh...', Array)
#1 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Broadcasting\\BroadcastEvent->handle(Object(Illuminate\\Broadcasting\\BroadcastManager))
#2 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#4 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(128): Illuminate\\Container\\Container->call(Array)
#7 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#8 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#9 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Bus\\Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Broadcasting\\BroadcastEvent), false)
#11 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#12 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Broadcasting\\BroadcastEvent))
#13 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Broadcasting\\BroadcastEvent))
#15 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Jobs\\Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Array)
#16 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#17 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(378): Illuminate\\Queue\\Worker->process('database', Object(Illuminate\\Queue\\Jobs\\DatabaseJob), Object(Illuminate\\Queue\\WorkerOptions))
#18 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(172): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\DatabaseJob), 'database', Object(Illuminate\\Queue\\WorkerOptions))
#19 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#20 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#21 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#22 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#23 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#24 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#27 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\symfony\\console\\Command\\Command.php(298): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\symfony\\console\\Application.php(1040): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\symfony\\console\\Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(94): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 C:\\xampp\\htdocs\\api_whatsapp\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 C:\\xampp\\htdocs\\api_whatsapp\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

**Comment by AlexanderGoi** [comment]
Creo que es por la diferente hora entre el cluster a la de mi servidor, intentare actualizar la hora del servidor.

**Comment by AlexanderGoi** [comment]
Si era eso, lamentablemente en mi empresa no se puede sincronizar mediante las páginas que tiene el sistema de windows la hora exacta tiempo México (Saludos...!!) debido a un problema que tienen con otros servidores.
Pero ya me puse a calcularle la hora exactamente y ya se ejecuto bien.
Muchas gracias.

**Comment by vinixcode** [comment]
Saludos, me alegra saber que pudiste solucionarlo hace algunos dias.
