### ISSUE TITLE
descarga de archivos multimedia en node

### ISSUE THREAD

**Issue by TiagoRendon** [Vinix-Code-Dev/curso-api-whatsapp-frontend#35]
Saludos:

Tienes conocimiento de la manera como se debe tratar el binario en Nodejs? estoytratando de realizar la descarga y el archivo siempre llega corrupto, agradezco tu atencion.

**Comment by vinixcode** [comment]
Hola @TiagoRendon que sistema operativo usas?

Te recomiendo usar nvm para manejar los binarios e instalacion de versiones: https://github.com/nvm-sh/nvm

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.

**Comment by TiagoRendon** [comment]
buen dia, pude lograr descargar el binario, fue una búsqueda extensa pero
por fin se logró, muchas gracias y disculpe no haber dado respuesta a
tiempo.
