### ISSUE TITLE
problemas ngrok

### ISSUE THREAD

**Issue by rricolas** [Vinix-Code-Dev/curso-api-whatsapp-frontend#36]
ngrok no es aceptado por facebook, cual es la solución ahora?

**Comment by rricolas** [comment]
solución pagar......

**Comment by vinixcode** [comment]
@rricolas ya intentaste correr ngrok con la version gratuita usando este comando especifico:

ngrok --region us http 8000

Intenta si te funciona por favor! Gracias.
