### ISSUE TITLE
Error ejecutando ngrok http 8000

### ISSUE THREAD

**Issue by BCIPRIANR** [Vinix-Code-Dev/curso-api-whatsapp-frontend#37]
Buen diia en la terminal del VSC cuando ingreso el comando negrok http 800 me arroja el siguiente error 

ngrok : El término 'ngrok' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso,
compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ ngrok http 8000
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (ngrok:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by BCIPRIANR** [comment]
![Captura de pantalla 2023-02-18 091107](https://user-images.githubusercontent.com/124621666/219870444-c9f766bb-3e4c-4f73-bf1c-e1d8a24518b3.png)

**Comment by BCIPRIANR** [comment]
Buen dia compañeros logre solucionar el problema por si alguien le pase mi .S.O es windows instale el negrok con ejecutable luego en la consola del mismo puse a correr el negrok con el puerto 8000 y ya

**Comment by vinixcode** [comment]
Perfecto! Gracias por confirmar que lo solucionaste @BCIPRIANR
