### ISSUE TITLE
Error en envio de plantilla de texto

### ISSUE THREAD

**Issue by melvingomez** [Vinix-Code-Dev/curso-api-whatsapp-frontend#38]
`{`
    "messaging_product": "whatsapp",
    "type": "template",
    "template": {
        "name": "hello_world",
        "language": {
            "code": "en_US"
        },
        "components": [
            {
                "type": "header",
                "parameters": [
                    {
                        "type": "text",
                        "text": "Hello World"
                    }
                ]
            },
            {
                "type": "body",
                "parameters": [
                    {
                        "type": "text",
                        "text": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us."
                    }
                ]
            },
            {
                "type": "footer",
                "parameters": [
                    {
                        "type": "text",
                        "text": "WhatsApp Business Platform sample message"
                    }
                ]
            }
        ]
    },
    "to": "50374142510"
}

**Comment by vinixcode** [comment]
@melvingomez ocurre que el payload es incorrecto, y estás pasando más datos de los que son.

Intenta con este:

```
{
    "messaging_product": "whatsapp",
    "to": "50374142510",
    "type": "template",
    "template": {
        "name": "hello_world",
        "language": {
            "code": "en_US"
        }
    }
}
```

Saludos!

**Comment by melvingomez** [comment]
Entendido los mensajes de las plantillas no se pueden modificar entonces

**Comment by vinixcode** [comment]
Así es. Las plantillas no admiten modificación al momento de enviarlas, a menos que estés pasando una parámetro adicional a la plantilla.

Espero que tu duda esté resuelta - cerraré el ticket.

Gracias.
