### ISSUE TITLE
Error en front 

### ISSUE THREAD

**Issue by BCIPRIANR** [Vinix-Code-Dev/curso-api-whatsapp-frontend#39]
![image](https://user-images.githubusercontent.com/124621666/220189634-513e4f3b-a585-4d31-831d-54cdb2c0489b.png)

buen dia al instalar el npm no tengo problema pero cuando ejecuto el comando npm run dev me genera error que adjunto he buscado en foros y dice que es la version del node la cual es v18.14.1 pero no se como hacerle un degrado  ayuda

**Comment by BCIPRIANR** [comment]
Hola

**Comment by BCIPRIANR** [comment]
![image](https://user-images.githubusercontent.com/124621666/220346983-1f0afa1e-62a7-40f1-9f59-a4099c35a275.png)

la verdad lo he intentado todo y nada quedo atento a la ayuda

**Comment by vinixcode** [comment]
@BCIPRIANR lo mas seguro es que el problema sea la version de Node. Idealmente debes usar la version 16.x (por ejemplo yo tengo la v16.19.0 y funciona).

No tienes que hacer downgrade a la version actual. Puedes usar nvm que te permite tener varias versiones de Node y NPM en el mismo sistema. 

Esta es la página de nvm: https://github.com/nvm-sh/nvm

Intenta y nos cuentas por favor.

**Comment by BCIPRIANR** [comment]
Muchas gracias por la guia es correcto lo que hice fue en este reposotiro  https://github.com/coreybutler/nvm-windows 
encontre el instalador para windows luego a través del power shell instale la version que me mencionaste y fluyo todo gracias 
![image](https://user-images.githubusercontent.com/124621666/220397042-a598ca9c-d533-4809-9d02-8545151835c8.png)

**Comment by BCIPRIANR** [comment]
Gracias
