### ISSUE TITLE
Adjuntar nombre de archivo en medios con template

### ISSUE THREAD

**Issue by bkamiche** [Vinix-Code-Dev/curso-api-whatsapp-frontend#42]
Al enviar un archivo como parte de un template hay forma de indicarle al aPI (De wasapi) el nombre con el que debera aparecer el archivo adjunto?

En el api de whatsapp se puede realizar, pero no encuentro un equivalente en wasapi.

**Comment by vinixcode** [comment]
@bkamiche actualmente Wasapi usa el nombre que tu le pongas al archivo, y no es posible modificarlo. Lo tendré presente para compartirlo al equipo de desarrollo para agregar un parámetro para esto.

**Comment by bkamiche** [comment]
Cuando envias un archivo, digamos un PDF asociado a un template, no importa el nombre que tenga el archivo (nombre fisico real), siempre asume el nombre "file", al menos en las pruebas que he realizado.

Cuando se envia un archivo como mensaje (attachment end point) ahi si respeta el nombre que le pase como parametro.

**Comment by vinixcode** [comment]
@bkamiche te recomiendo reportar este comportamiento directamente por la linea de soporte de Wasapi: https://wa.me/19549477419

Gracias.
