### ISSUE TITLE
curso de 0 a experto problemas con mac os sierra

### ISSUE THREAD

**Issue by sastoquejulian** [Vinix-Code-Dev/curso-api-whatsapp-frontend#43]
he intentado instalar laravel y la version  de composer en mac os high sierra y no lo logro ayuda muchas gracias

**Comment by vinixcode** [comment]
Hola. Por favor compártenos más información sobre los errores y problemas que estás teniendo, para determinar como ayudarte. Saludos.

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.

**Comment by sastoquejulian** [comment]
hola saludos despues de ver los tutoriales ,ejecute el codigo para instalar laravel en mac os high sierra , pero no me aparece instalado .
primero instale composer y si me aparace instalado 
![Captura de pantalla 2023-03-06 a la(s) 23 35 12](https://user-images.githubusercontent.com/126121824/223323273-b180d32d-b55a-427a-91b0-823951084d5e.png)
luego ejecute el codigo para instalar laravel  pero no me aparece 

![Captura de pantalla 2023-03-06 a la(s) 23 44 04](https://user-images.githubusercontent.com/126121824/223323494-942bde17-b990-439e-ae75-fc202e88268d.png)
entonces por esta razon no he podido continuar 
gracias por la ayuda
