### ISSUE TITLE
php artisan migrate

### ISSUE THREAD

**Issue by BCIPRIANR** [Vinix-Code-Dev/curso-api-whatsapp-frontend#45]
![image](https://user-images.githubusercontent.com/124621666/220915707-a00bce1a-8994-4a60-9269-72c8805274a2.png)
Hola mira que la base de datos que cree le puse usuario root clave root verifique en el .env tambien pero a la hora de hacer la migracion me generaba este error lo que hice fue dejar en el archivo .env sin clave root y si corrio pero quisiera saber donde esta el error o donde debo poner la clave del usuario root

**Comment by vinixcode** [comment]
@BCIPRIANR Si no te funcionó con esa clave, es porque el usuario no tiene clave (como ya comprobaste). Debes cambiar la contraseña del usuario root, en Google vas a encontrar información amplia sobre como actualizar la contraseña del usuario root en MySQL. Saludos.
