### ISSUE TITLE
Como se obtiene la certificación si ya finalice el curso.

### ISSUE THREAD

**Issue by AlexanderGoi** [Vinix-Code-Dev/curso-api-whatsapp-frontend#47]
Ya finalice el curso, y como todo he ido realizando más pruebas y pruebas, para ir incormporando lo que haga vaya completando más la aplicación.
Y si no mal recuerdo, para obtener un certificación el proyecto final debe funcionar para obtenerla.

Cual es el procedimiento..??

**Comment by vinixcode** [comment]
Por supuesto @AlexanderGoi ! Felicidades por completar el curso, y con gusto te ayudaremos a obtener tu respectiva certificación.

Para solicitarla, lo único que te pedimos es que grabes un video de tu pantalla mostrando por favor el software en funcionamiento, y mostrando brevemente el código que escribiste.

También envíanos tu nombre completo, país, teléfono, y número de identificación para el certificado.

Todo esto envíalo a info@vinixcode.com y ya nosotros te contactaremos con los siguientes pasos!
Gracias
