### ISSUE TITLE
Clase rutas para cargar mensajes Backend

### ISSUE THREAD

**Issue by BCIPRIANR** [Vinix-Code-Dev/curso-api-whatsapp-frontend#48]
![image](https://user-images.githubusercontent.com/124621666/221249894-c11457e6-9507-44df-b89f-a232174f6f76.png)

Hola mira que estoy corriendo la consulta en el Backend como en el SQL y solo me muestra el primer resultado no me muestra el segundo en el local host aparece igual asi  
![image](https://user-images.githubusercontent.com/124621666/221250454-bf380087-4271-491f-beae-913c33b4d976.png)

**Comment by AlexanderGoi** [comment]
Hola @BCIPRIANR 
Podrías mandar un Select * from messages para ver todos los registros

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
