### ISSUE TITLE
Como utilizar mi aplicación para una empresa

### ISSUE THREAD

**Issue by AlexanderGoi** [Vinix-Code-Dev/curso-api-whatsapp-frontend#49]
Hola que tal.

Ya tengo mi aplicación funcionando, solo que este desarrollo es para una empresa llamada FIDE que ya se encuentra verificada ante META, lo que quiero hacer, es que la utilice dicha empresa (trabajo ahí)
Ya me brindaron acceso como admin de la pagina, pero no se como pasar el desarrollo aqui o que necesito para que el número que estoy agregando tome la verificación que ya se tiene.

No se que debo hacer, no viene como un apartado sobre este tema.??
O en el peor de los casos, es necesario quien realizo la verificación de FIDE, lo vuelva hacer pero donde tengo la app..

**Comment by vinixcode** [comment]
@AlexanderGoi buena pregunta.

Basicamente debes hacer toda la configuracion de la aplicacion y el numero de telefono en esta nueva cuenta.

Yo te recomiendo ver este video que grabamos para Wasapi, pero que te sera igual de funcional para tu aplicacion (simplemente ignora los cambios en Wasapi, pero el resto sera completamente igual):

https://vimeo.com/738412209

Saludos,
-Juan

**Comment by AlexanderGoi** [comment]
Muchas gracias, ya lo pude pasar a la empresa el desarrollo, solo que tengo ahora otro inconveniente.
Antes que nada movi todo a la cuenta negocio de FIDE y ya de ahi pude pasar todo, es todo un mundo también lo de facebook.

Ya agregue todo tal cual, el unico es que al agregar el número de producción me marca esto
![imagen](https://user-images.githubusercontent.com/58536439/222830069-4dcc38e5-adbb-4d2a-a95c-4d97d40d97d8.png)
Le doy en el enlace y me manda ahi
![imagen](https://user-images.githubusercontent.com/58536439/222830272-7094aa1d-d110-4acb-836a-01588281bb62.png)
No veo ninguna alerta ahi, no se que haga falta más, o si es necesario algún tiempo de espera para que se apliquen los cambios.

Saludos..!!!

**Comment by vinixcode** [comment]
Ignora la alerta @AlexanderGoi - es muy común ver esa alerta a pesar que todo funciona perfectamente.
