### ISSUE TITLE
Funcion _mime2ext no encontrada

### ISSUE THREAD

**Issue by amurillo12** [Vinix-Code-Dev/curso-api-whatsapp-frontend#5]
Buen día.

En la lección numero 20 del curso se menciona que habrá una función la cual se podrá copiar pero dicha función no la encuentro en la lección y no se si solo a mi no me aparece.

**Comment by vinixcode** [comment]
Gracias por reportarlo! Aqui te comparto el enlace y pondremos el enlace en el curso: https://bit.ly/gistMime2Ext

**Comment by amurillo12** [comment]
Gracias a ti!
