### ISSUE TITLE
Clase 14 - No muestra info en el index.vue del front-end

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#50]
Buena tarde, por más que revise el código no encuentro el error. Lo comparo con el tutorial y lo veo igual. Pueden ayudarme en que parte he cometido el error.
Cuando pongo el resultado por consola me muestra la data, pero al asignárselo a la variable ítems, no muestra ningún dato. Solo estoy mostrando por ahora los datos de la barra izquierda que sería el número de móvil y lo último que escribió el usuario.
Por consola muestra:

![consola0](https://user-images.githubusercontent.com/123026405/223225700-29b2f234-de7f-4c0b-bafd-10410f8f4018.JPG)

![consola](https://user-images.githubusercontent.com/123026405/223225737-1e002864-407c-4f82-a9d8-6b746ab68bb7.JPG)

Ahora pongo para lo muestre en la variable items y no muestra info:

![consola3](https://user-images.githubusercontent.com/123026405/223226053-b681d9b5-5760-4216-9192-7808c3756601.JPG)

![consola4](https://user-images.githubusercontent.com/123026405/223226359-53f38f72-1d24-4786-b126-cadabf035930.JPG)

no se si tiene que ver este mensaje de error que sale en el código (cuando puse el front end solo puse el comando que ustedes explicaron que era npm install. No se si pone una version de vue actual y por eso el mensaje de error):

![consola5](https://user-images.githubusercontent.com/123026405/223227120-b8075e24-0e70-4450-bd49-f32668f72314.JPG)

Que parte hice mal, alguien puede darme una copia de esa fuente del index.vue para comparar. Gracias.

**Comment by leandrogr21** [comment]
Este es mi version de node y npm
![image](https://user-images.githubusercontent.com/123026405/223228724-11a7771a-9805-4e42-8e63-1e56086d9eba.png)

**Comment by leandrogr21** [comment]
![image](https://user-images.githubusercontent.com/123026405/223234366-a5fe39a8-1b64-4fb6-8be3-4b0e52493971.png)

**Comment by vinixcode** [comment]
@leandrogr21 podrias por favor pegar todo el código del archivo index.vue por favor. Gracias.

**Comment by leandrogr21** [comment]
<template>
  <v-row>
    
    <v-col sm="3">
      <v-card elevation="7" class="chat-list">
        <v-card class="pa-2" color="#424242" dark>Chats</v-card>
        <v-list class="py-0" two-line>
          <v-list-item-group v-model="selected" active-class="green--text">
            <template v-for="(item, index) in items">
              <v-list-item :key="item.wa_id">
                <template>
                  <v-list-item-content>
                    <v-list-item-title v-text="item.wa_id"></v-list-item-title>
                    <v-list-item-subtitle v-text="item.body"></v-list-item-subtitle>
                  </v-list-item-content>
                </template>
              </v-list-item>
              <v-divider v-if="index < items.length - 1" :key="index" ></v-divider>
            </template>
          </v-list-item-group>
        </v-list>
      </v-card>
    </v-col>

    
    <v-col md="9">
      <v-card elevation="7">
        <v-card class="chat-box wpp-bg" color="#efeae2">
          <v-card class="pa-2" color="#424242" dark>Ali Connors</v-card>
          <div
            v-for="(message, index) in messages"
            :key="index"
            :class="[
              'pa-1',
              'd-flex',
              { 'justify-start': !message.outgoing },
              { 'justify-end': message.outgoing },
            ]"
          >
            <v-card
              class="pa-2 ma-2 message-card"
              :color="message.outgoing ? 'green accent-1' : 'white'"
            >
              <div>
                <div>{{ message.body }}</div>
                <p class="text-right text-subtitle-2 font-italic">
                  {{ message.created_at }}
                  <v-icon
                    v-bind="attrs"
                    :color="formatReadStatus(message.status).color"
                    small
                    v-on="on"
                    >{{ formatReadStatus(message.status).icon }}</v-icon
                  >
                </p>
              </div>
            </v-card>
          </div>
        </v-card>
        <v-divider></v-divider>
        <div class="pa-3">
          <v-text-field
            v-model="message"
            dense
            outlined
            background-color="white"
            :append-outer-icon="'mdi-send'"
            filled
            clear-icon="mdi-close-circle"
            clearable
            label="Type a message..."
            type="text"
            class="message-box"
            @click:append-outer="sendMessage"
            @keydown.enter.exact.prevent="sendMessage"
          ></v-text-field>
        </div>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
export default {
  data: () => ({
    selected: [2],
    items: [
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors2',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors3',
      },
    ],
    messages: [
      {
        outgoing: false,
        body: 'Nunc tellus magna, volutpat vel orci eu, venenatis vestibulum magna. Morbi fermentum, purus laoreet egestas maximus, metus ex bibendum nulla, in posuere nunc neque id nulla.',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'read',
      },
      {
        outgoing: false,
        body: 'Nulla id eros consequat purus interdum iaculis quis ut orci. Mauris dapibus turpis sit amet egestas consectetur. ',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'delivered',
      },
    ],
    message: '',
  }),
  created() {
    this.loadMessages()
  },
  methods: {
    loadMessages(){
      this.$axios.get('http://localhost:8000/api/messages').then((data) => {
        this.items = data.data
      })
    },
    sendMessage() {
      this.messages.push({
        outgoing: true,
        body: this.message,
        created_at: this.$moment().format('L'),
        status: 'sent',
      })
      this.message = ''
    },
    formatReadStatus(status) {
      const statuses = {
        read: {
          color: 'blue',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgDelivered'),
          tooltip: 'Read',
        },
        delivered: {
          color: 'grey',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgRead'),
          tooltip: 'Delivered',
        },
        sent: {
          color: 'grey',
          icon: 'mdi-check',
          // tooltip: $t('chat.msgSent'),
          tooltip: 'Sent',
        },
        failed: {
          color: 'red',
          icon: 'mdi-alert-circle',
          // tooltip: $t('chat.msgFailed'),
          tooltip: 'Failed',
        },
      }

      if (statuses?.[status]) {
        return statuses[status]
      } else {
        return {
          color: 'grey',
          icon: 'mdi-cards-diamond-outline',
          tooltip: '',
        }
      }
    },
  },
}
</script>

<style>
.message-box .v-text-field__details {
  display: none;
}
.chat-box {
  height: 80vh;
  overflow-y: scroll;
}
.message-card {
  max-width: 60%;
}
.chat-list {
  height: 85vh;
}
.wpp-bg {
  background-image: url('/bg-whatsapp.png');
  background-repeat: repeat;
  border-color: #efeae2;
}
</style>

**Comment by leandrogr21** [comment]
`<template>
  <v-row>
    
    <v-col sm="3">
      <v-card elevation="7" class="chat-list">
        <v-card class="pa-2" color="#424242" dark>Chats</v-card>
        <v-list class="py-0" two-line>
          <v-list-item-group v-model="selected" active-class="green--text">
            <template v-for="(item, index) in items">
              <v-list-item :key="item.wa_id">
                <template>
                  <v-list-item-content>
                    <v-list-item-title v-text="item.wa_id"></v-list-item-title>
                    <v-list-item-subtitle v-text="item.body"></v-list-item-subtitle>
                  </v-list-item-content>
                </template>
              </v-list-item>
              <v-divider v-if="index < items.length - 1" :key="index" ></v-divider>
            </template>
          </v-list-item-group>
        </v-list>
      </v-card>
    </v-col>

    
    <v-col md="9">
      <v-card elevation="7">
        <v-card class="chat-box wpp-bg" color="#efeae2">
          <v-card class="pa-2" color="#424242" dark>Ali Connors</v-card>
          <div
            v-for="(message, index) in messages"
            :key="index"
            :class="[
              'pa-1',
              'd-flex',
              { 'justify-start': !message.outgoing },
              { 'justify-end': message.outgoing },
            ]"
          >
            <v-card
              class="pa-2 ma-2 message-card"
              :color="message.outgoing ? 'green accent-1' : 'white'"
            >
              <div>
                <div>{{ message.body }}</div>
                <p class="text-right text-subtitle-2 font-italic">
                  {{ message.created_at }}
                  <v-icon
                    v-bind="attrs"
                    :color="formatReadStatus(message.status).color"
                    small
                    v-on="on"
                    >{{ formatReadStatus(message.status).icon }}</v-icon
                  >
                </p>
              </div>
            </v-card>
          </div>
        </v-card>
        <v-divider></v-divider>
        <div class="pa-3">
          <v-text-field
            v-model="message"
            dense
            outlined
            background-color="white"
            :append-outer-icon="'mdi-send'"
            filled
            clear-icon="mdi-close-circle"
            clearable
            label="Type a message..."
            type="text"
            class="message-box"
            @click:append-outer="sendMessage"
            @keydown.enter.exact.prevent="sendMessage"
          ></v-text-field>
        </div>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
export default {
  data: () => ({
    selected: [2],
    items: [
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors2',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors3',
      },
    ],
    messages: [
      {
        outgoing: false,
        body: 'Nunc tellus magna, volutpat vel orci eu, venenatis vestibulum magna. Morbi fermentum, purus laoreet egestas maximus, metus ex bibendum nulla, in posuere nunc neque id nulla.',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'read',
      },
      {
        outgoing: false,
        body: 'Nulla id eros consequat purus interdum iaculis quis ut orci. Mauris dapibus turpis sit amet egestas consectetur. ',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'delivered',
      },
    ],
    message: '',
  }),
  created() {
    this.loadMessages()
  },
  methods: {
    loadMessages(){
      this.$axios.get('http://localhost:8000/api/messages').then((data) => {
        this.items = data.data
      })
    },
    sendMessage() {
      this.messages.push({
        outgoing: true,
        body: this.message,
        created_at: this.$moment().format('L'),
        status: 'sent',
      })
      this.message = ''
    },
    formatReadStatus(status) {
      const statuses = {
        read: {
          color: 'blue',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgDelivered'),
          tooltip: 'Read',
        },
        delivered: {
          color: 'grey',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgRead'),
          tooltip: 'Delivered',
        },
        sent: {
          color: 'grey',
          icon: 'mdi-check',
          // tooltip: $t('chat.msgSent'),
          tooltip: 'Sent',
        },
        failed: {
          color: 'red',
          icon: 'mdi-alert-circle',
          // tooltip: $t('chat.msgFailed'),
          tooltip: 'Failed',
        },
      }

      if (statuses?.[status]) {
        return statuses[status]
      } else {
        return {
          color: 'grey',
          icon: 'mdi-cards-diamond-outline',
          tooltip: '',
        }
      }
    },
  },
}
</script>

<style>
.message-box .v-text-field__details {
  display: none;
}
.chat-box {
  height: 80vh;
  overflow-y: scroll;
}
.message-card {
  max-width: 60%;
}
.chat-list {
  height: 85vh;
}
.wpp-bg {
  background-image: url('/bg-whatsapp.png');
  background-repeat: repeat;
  border-color: #efeae2;
}
</style>`

**Comment by leandrogr21** [comment]
<template>
  <v-row>
    
    <v-col sm="3">
      <v-card elevation="7" class="chat-list">
        <v-card class="pa-2" color="#424242" dark>Chats</v-card>
        <v-list class="py-0" two-line>
          <v-list-item-group v-model="selected" active-class="green--text">
            <template v-for="(item, index) in items">
              <v-list-item :key="item.wa_id">
                <template>
                  <v-list-item-content>
                    <v-list-item-title v-text="item.wa_id"></v-list-item-title>
                    <v-list-item-subtitle v-text="item.body"></v-list-item-subtitle>
                  </v-list-item-content>
                </template>
              </v-list-item>
              <v-divider v-if="index < items.length - 1" :key="index" ></v-divider>
            </template>
          </v-list-item-group>
        </v-list>
      </v-card>
    </v-col>

    
    <v-col md="9">
      <v-card elevation="7">
        <v-card class="chat-box wpp-bg" color="#efeae2">
          <v-card class="pa-2" color="#424242" dark>Ali Connors</v-card>
          <div
            v-for="(message, index) in messages"
            :key="index"
            :class="[
              'pa-1',
              'd-flex',
              { 'justify-start': !message.outgoing },
              { 'justify-end': message.outgoing },
            ]"
          >
            <v-card
              class="pa-2 ma-2 message-card"
              :color="message.outgoing ? 'green accent-1' : 'white'"
            >
              <div>
                <div>{{ message.body }}</div>
                <p class="text-right text-subtitle-2 font-italic">
                  {{ message.created_at }}
                  <v-icon
                    v-bind="attrs"
                    :color="formatReadStatus(message.status).color"
                    small
                    v-on="on"
                    >{{ formatReadStatus(message.status).icon }}</v-icon
                  >
                </p>
              </div>
            </v-card>
          </div>
        </v-card>
        <v-divider></v-divider>
        <div class="pa-3">
          <v-text-field
            v-model="message"
            dense
            outlined
            background-color="white"
            :append-outer-icon="'mdi-send'"
            filled
            clear-icon="mdi-close-circle"
            clearable
            label="Type a message..."
            type="text"
            class="message-box"
            @click:append-outer="sendMessage"
            @keydown.enter.exact.prevent="sendMessage"
          ></v-text-field>
        </div>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
export default {
  data: () => ({
    selected: [2],
    items: [
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors2',
      },
      {
        body: `I'll be in your neighborhood doing errands this weekend. Do you want to hang out?`,
        wa_id: 'Ali Connors3',
      },
    ],
    messages: [
      {
        outgoing: false,
        body: 'Nunc tellus magna, volutpat vel orci eu, venenatis vestibulum magna. Morbi fermentum, purus laoreet egestas maximus, metus ex bibendum nulla, in posuere nunc neque id nulla.',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'read',
      },
      {
        outgoing: false,
        body: 'Nulla id eros consequat purus interdum iaculis quis ut orci. Mauris dapibus turpis sit amet egestas consectetur. ',
        created_at: '05/02/2022',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'estibulum pellentesque maximus lacus, quis viverra justo pharetra sed. Curabitur tempus consequat dolor, ut gravida dui pulvinar eget.',
        created_at: '05/02/2022',
        status: 'delivered',
      },
    ],
    message: '',
  }),
  created() {
    this.loadMessages()
  },
  methods: {
    loadMessages(){
      this.$axios.get('http://localhost:8000/api/messages').then((data) => {
        this.items = data.data
      })
    },
    sendMessage() {
      this.messages.push({
        outgoing: true,
        body: this.message,
        created_at: this.$moment().format('L'),
        status: 'sent',
      })
      this.message = ''
    },
    formatReadStatus(status) {
      const statuses = {
        read: {
          color: 'blue',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgDelivered'),
          tooltip: 'Read',
        },
        delivered: {
          color: 'grey',
          icon: 'mdi-check-all',
          // tooltip: $t('chat.msgRead'),
          tooltip: 'Delivered',
        },
        sent: {
          color: 'grey',
          icon: 'mdi-check',
          // tooltip: $t('chat.msgSent'),
          tooltip: 'Sent',
        },
        failed: {
          color: 'red',
          icon: 'mdi-alert-circle',
          // tooltip: $t('chat.msgFailed'),
          tooltip: 'Failed',
        },
      }

      if (statuses?.[status]) {
        return statuses[status]
      } else {
        return {
          color: 'grey',
          icon: 'mdi-cards-diamond-outline',
          tooltip: '',
        }
      }
    },
  },
}
</script>

<style>
.message-box .v-text-field__details {
  display: none;
}
.chat-box {
  height: 80vh;
  overflow-y: scroll;
}
.message-card {
  max-width: 60%;
}
.chat-list {
  height: 85vh;
}
.wpp-bg {
  background-image: url('/bg-whatsapp.png');
  background-repeat: repeat;
  border-color: #efeae2;
}
</style>

**Comment by leandrogr21** [comment]
![image](https://user-images.githubusercontent.com/123026405/223316950-4c46a7c8-72fc-4758-b2c9-53f639f6e13e.png)
![image](https://user-images.githubusercontent.com/123026405/223317041-c25e3104-7a32-4d70-a5e4-b0a02ed13782.png)
![image](https://user-images.githubusercontent.com/123026405/223317130-cd05e2c9-cb1f-4a1a-9cbe-17345ed84d24.png)
![image](https://user-images.githubusercontent.com/123026405/223317234-9380fc29-20fc-4bff-9137-5a81ada94af8.png)
![image](https://user-images.githubusercontent.com/123026405/223317320-9c9bbcea-cdb7-432f-9085-9b0dcf4d9774.png)
![image](https://user-images.githubusercontent.com/123026405/223317409-69d9091a-60f7-43f0-87f9-92cac3889bf2.png)
![image](https://user-images.githubusercontent.com/123026405/223317495-c56cd581-f9ed-4c20-aa0c-792470abe439.png)
![image](https://user-images.githubusercontent.com/123026405/223317536-e070999b-b495-4072-af4d-776a44fbc675.png)

**Comment by leandrogr21** [comment]
Hola, necesito ayuda para seguir avanzando. Por favor no demoren tanto en responder. Gracias

**Comment by leandrogr21** [comment]
Ya resolví el inconveniente. La data que me envía la sentencia:
this.$axios.get('http://localhost:8000/api/messages').then((data) => {
        this.items = data.data
      })

resulta que esa data así, viene con otra data que es donde están los datos, al agregarle la otra data ya quedó bien.
this.$axios.get('http://localhost:8000/api/messages').then((data) => {
        this.items = data.data.data
      })

**Comment by vinixcode** [comment]
Excelente trabajo, @leandrogr21 !

**Comment by TomasS-R** [comment]
Hola me encontre con este problema, y era algo similar la solucion, la comento por si alguno le pasa.

En mi caso estaba siguiendo los videos y en el momento juan realizo esta modificacion a mi no me fucnionaba:

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/55171526/b48206bf-027d-4316-a47a-66e083feac0e)

Por lo que conclui lo que decia leandro, y pude ver como se estaba almacenando mi informacion, y para mi fortuna lo pude solucionar de esta forma:

`const messages = data.data.rows;`
 `this.items = messages;`

En vez de solo `this.items = data;` como menciona juan en las clases.

Pd: mi backend lo tengo en fly.io y la base de datos en supabase no se si eso afectara en algo en como se muestra la data en cada caso

**Comment by vinixcode** [comment]
Gracias por compartir @TomasS-R ! Excelente.
