### ISSUE TITLE
Clase 15 - No se envía el mensaje de texto

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#51]
Buena noche, estoy en la parte donde envío el mensaje de texto. Pongo en la url para enviar el texto

http://localhost:8000/api/send-message

y según la página se envió correctamente pero no me llega el mensaje al whatsapp.  Esto es lo que muestra:

{
  "success":true,"
  data":{
    "messaging_product":"whatsapp",
    "contacts":[{
       "input":"573162283451",
       "wa_id":"573162283451"
     }],
     "messages":[{
        "id":"wamid.HBgMNTczMTYyMjgzNDUxFQIAERgSOEQxRTUyQUFFNzdBMjRGRTQ0AA=="
     }]
  }
}

Que puede estar pasando? debo habilitar algo en la configuración de la app en Facebook?

Dejo el código como lo tenía antes y llega el mensaje. Lo pongo con la nueva librería y no llega, pero si sale el mensaje de enviado.
Si maneja el template llega de una, si manejo el texto no.

gracias por su ayuda

**Comment by vinixcode** [comment]
@leandrogr21 recuerda que para enviar un mensaje de texto normal, primero debes recibir una respuesta del usuario (despues de iniciar la conversacion con un mensaje plantilla) ya que basicamente esa es la manera en la que el usuario acepta seguir recibiendo comunicacion de tu parte.

Por cierto, los webhooks tambien te muestran si el mensaje realmente fue entregado o no.

**Comment by leandrogr21** [comment]
Que pena no tuve en cuenta eso, ya lo probé y funciona bien. Gracias.

**Comment by vinixcode** [comment]
Maravilloso @leandrogr21 . Cerrando ticket.
