### ISSUE TITLE
Consulta 

### ISSUE THREAD

**Issue by MikeYaya** [Vinix-Code-Dev/curso-api-whatsapp-frontend#52]
Buenas tardes 

Mi pregunta es la siguiente: inicialmente, solo tenía un número asociado al API de Whatsapp, pero actualmente estoy realizando pruebas con otro número adicional. El problema es que todas las solicitudes y mensajes de Whatsapp no están llegando al proyecto que se está ejecutando en Visual Studio Code, estos mensajes están llegando directamente a Wasapi. Sin embargo, este nuevo número es totalmente diferente al que tengo en Wasapi. He verificado el archivo .env del proyecto local que tengo en mi equipo, pero aún no logro resolver el problema.

Agradecería mucho si pudieras brindarme alguna orientación o sugerencia para solucionar este problema.

**Comment by vinixcode** [comment]
@MikeYaya seguramente lo que ocurre es que tienes ambas líneas bajo un mismo negocio en Facebook Business, y si ese es el caso solo puedes tener 1 webhook para todas las líneas que tengas en ese negocio (el cual debe ser el que está apuntando a Wasapi, probablemente).

Te recomiendo simplemente usar una cuenta de FB Business distinta. Cuando crees la app en FB asegúrate de hacer que apunte a un negocio distinto, no al que tienes actualmente con Wasapi.

**Comment by MikeYaya** [comment]
Perfecto muchas gracias
