### ISSUE TITLE
contacto

### ISSUE THREAD

**Issue by BCIPRIANR** [Vinix-Code-Dev/curso-api-whatsapp-frontend#53]
Hola vinix voy por la mitad del curso la verdad tengo una pregunta es que quiero iniciar la produccion rapido en la empresa que trabajo podria ponerme en contacto contigo para unos desarrollos adicionales

**Comment by vinixcode** [comment]
Hola @BCIPRIANR por favor escribenos a nuestra línea de Wasapi y por ahí podremos estudiar mejor tus necesidades y mirar si te podemos servir: https://wa.me/19549477419

Saludos!
