### ISSUE TITLE
Clase 18 - No muestra actividad en el socket

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#54]
Hola, estoy en el proceso de recibir actividad con el pusher pero me dice que falló
![image](https://user-images.githubusercontent.com/123026405/224360360-022f52c0-316c-4be8-af64-14afe6bd7c75.png)

Hice lo que dijeron:
* composer require pusher/pusher-php-server

* En el .env puse las variables del pusher (las que me arrojó cuando me inscribí y creé el canal) 
![image](https://user-images.githubusercontent.com/123026405/224362458-579a6e57-74db-4cf2-812a-39c532ba94b6.png)

* php artisan make:event Webhook
 
* edite el webhook:
![image](https://user-images.githubusercontent.com/123026405/224361398-fc8ca6e1-37fd-4b3a-aa09-21080e60c83e.png)

* php artisan queue:table

* php artisan migrate

* Edite el web.php
![image](https://user-images.githubusercontent.com/123026405/224363229-59d69520-2b3a-43a6-ad2b-3b46791d380c.png)

* ejecuté:
![image](https://user-images.githubusercontent.com/123026405/224364437-7b6459cd-9bd9-43f8-86de-f325eb81db69.png)

* entre en la web y refresqué la url del localhost:8000 para ejecutar el proceso y me mestra este error:
![image](https://user-images.githubusercontent.com/123026405/224364766-c3db8c71-be0e-46d1-90b8-0bff759037e5.png)

* Si voy a la pagina del pusher no muestra nada (refresqué la página varias veces y nada)
![image](https://user-images.githubusercontent.com/123026405/224364945-b6bbedbe-b6ad-4a1a-833d-bc9486e71f13.png)

Esos son pasos sencillos y no veo porque no responde ese proceso como a vos.

Ojalá sea rápida la respuesta ya que demoran mucho para dar una respuesta, espero que lo que dije no lo tomen a mal pero estamos en un curso y necesitamos avanzar en el proceso.

Gracias por la ayuda.

**Comment by vinixcode** [comment]
Hola @leandrogr21 gracias por la explicacion.

Por favor revisa este issue en el que otro alumno tuvo un problema similar en esa clase: https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/issues/34#issuecomment-1422800803

Te recomiendo revisar el log de Laravel, y compartirlo aquí en caso de que no logres solucionarlo, para seguirte ayudando.

Saludos

**Comment by leandrogr21** [comment]
definitivamente no pude con eso de los webhooks, he buscado info en internet y no he podido solucionarlo. Me toco saltarme esas dos clases para poder continuar

**Comment by vinixcode** [comment]
@leandrogr21 nuestro deseo es que le puedas sacar el máximo provecho al curso.

¿Podrías por favor compartirnos el log de errores que ves? Creo que así podremos ayudarte a diagnosticar la causa más fácil. Incluso puedes grabar un video de tu pantalla compartiendo lo que estás haciendo, para nosotros ver que puede estar saliendo mal.

Esta parte de los websockets es bien importante ya que te permite tener comunicación en tiempo real, así que fuera muy bueno intentar solucionarlo.

Saludos

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
