### ISSUE TITLE
clase 24 - Genera error Uncaught (in promise) TypeError: data.data.map is not a function

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#55]
Hola. Estoy en el archivo send.vue y estoy en methods creando la funcion loadTemplates.
Este es mi codigo;
![image](https://user-images.githubusercontent.com/123026405/224861131-25803866-8610-426b-b575-d8eaf835c781.png)

Los datos los veo, como se muestra en la imagen:
![image](https://user-images.githubusercontent.com/123026405/224862426-423e5b75-74ed-425d-a9ad-e41048d55cf7.png)

pero no son asignados a la variable items, me genera este error:
![image](https://user-images.githubusercontent.com/123026405/224861554-2383b1a5-43e4-4185-8eaf-b09ed0af598c.png)

Y si le doy clic sobre (send.vue?23ac:33:1), muestra el error:
![image](https://user-images.githubusercontent.com/123026405/224862756-4d5fddce-d992-4ddd-9b6d-c90df5fcc353.png)

No he podido continuar, he buscado en internet por horas y no logro resolverlo. necesito ayuda.

Gracias

**Comment by vinixcode** [comment]
@leandrogr21 Lo más probable es que la respuesta que estás recibiendo del servidor, no contiene la información de las plantillas.

Podrías poner un console.log(data); antes de la linea 34 para mirar que estás recibiendo como respuesta por parte del servidor.

También te comparto aquí el código completo del send.vue para que puedas compararlo (aunque te recomiendo que lo sigas haciendo paso a paso, para maximizar tu aprendizaje):

https://gist.github.com/vinixcode/1438904b86dada38f2d5df50e56b9df6

**Comment by leandrogr21** [comment]
Hola, gracias por responder.
En el código puse le console.log(data)
![image](https://user-images.githubusercontent.com/123026405/225111856-7de84c32-4ac6-4eee-93b2-1fbf25d883a5.png)

y este es el resultado de consola, como puedes ver tengo tres plantillas "iniciosiicsa", "bienvenida_siicsa" y "hello_world"
![image](https://user-images.githubusercontent.com/123026405/225112080-6ea4f0b3-0143-4f9c-8cca-1b3256a1cf32.png)

Espero que sirva.  Gracias

**Comment by vinixcode** [comment]
Segun la respuesta que veo de tu servidor, creo que tienes que cambiar el data.data.map por: data.data.data.map

Prueba y me cuentas por favor.

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
