### ISSUE TITLE
Error al obtener los templates

### ISSUE THREAD

**Issue by AlexanderGoi** [Vinix-Code-Dev/curso-api-whatsapp-frontend#56]
Buen día.

Ya cargaban los templates correctamente, solo que ahora me muestra mensaje

{
    "success": false,
    "error": "HTTP request returned status code 400:\n{\"error\":{\"message\":\"Unsupported get request. Object with ID 'message_templates' does not exist, cannot be loaded due to (truncated...)\n"
}

Ya servía todo, lo único con lo que estaba jugando era el acceso mediante accestoken y agregar el módulo de inicio de sesión, no se a que se deba el error, es como si el token permanente se le hayan quitado permisos, lo único que se me ocurre hacer drásticamente es borrar la app y volverla a generar

**Comment by AlexanderGoi** [comment]
Ya vi que es, pero no se como solucionarlo.
No esta leyendo correctamente los datos de las variables de entorno (.env)
No se a que se deba :(

**Comment by AlexanderGoi** [comment]
Por más que busque y busque, no encontre nada relacionado con este error, a lo mucho vi un refresh sobre el cache para que tomaran los cambios del .env pero seguia sin servir. Opte por hacer de nuevo toda la parte del BackEnd, y solo asi volvio a funcionar. 
De todas formas guarde el proyecto que tenia el error, por si existe alguna solución.

**Comment by vinixcode** [comment]
@AlexanderGoi entiendo lo que dices. Por que concluyes que no te funciona el .env?

Te sugiero que ejecutes los siguientes comandos y nos digas si te funciona:

```
php artisan cache:clear 
php artisan route:clear
php artisan config:clear
php artisan view:clear
```

Con eso deberias de limpiar la cache de Laravel y probablemente te vuelva a funcionar el archivo .env

Estare atento a tus comentarios!

**Comment by c0rtex** [comment]
@AlexanderGoi ¿pudiste solucionar el problema? Supongo que sí así que cerraré este ticket.

Sino, por favor reabrelo y con gusto te ayudamos! Saludos.
