### ISSUE TITLE
Traer a la conversación otro numero

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#57]
Buenas tardes, termine el curso y está bien, solo tengo una pregunta por si de pronto me puedes dar una luz.
Con mi Bot llega hasta un punto y de ahí e adelante necesita la ayuda de un humano, como hace uno para poder agregar en la misma conversación otra persona para que termine la llamada.
Ejemplo, Claro empieza el Bot y después te pone un asesor en línea en la misma conversación del Bot para seguir ayudando el cliente con la solución de lo que necesite.
En donde puedo encontrar información, para poder meter e esa misma conversa un tercero? no sé si se pueda o no, para hacerlo en el mismo código que nos ayudaste a crear durante el curso, o si es que se necesita un api o una librería externa para adjuntar la otra persona.
Gracias por tu respuesta

**Comment by vinixcode** [comment]
Hola @leandrogr21 

Realmente no es necesario ninguna integración externa y existen varias maneras de hacerlo. Una manera es simplemente implementando por ejemplo un sistema de etiquetado de conversación de tal manera que si el usuario llega a cierto punto del bot, le asigne una etiqueta (o algún tipo de "flag" al chat) y que sea visible en la lista de chats, para que el agente humano sepa que esa es una conversación que necesita atención.

También te recomiendo agregar un botón que permita deshabilitar el chat en cualquier momento, en caso de que un usuario decida responder. O también la opción de que el bot se desactive automáticamente si el agente humano envía algún mensaje.

En nuestro software Wasapi lo hacemos de una forma más avanzada: 

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/63106073/230073291-a2070957-4199-47bc-9267-25b92ebe6f89.png">

Cuando el usuario acepta una conversación, el bot se desactiva automáticamente y ya de ahí en adelante queda así hasta el que el agente cierre la conversación.

En resumen, no es necesario ninguna librería externa sino más bien buscar la forma de resaltar en el frontend, los chats que ya haya trabajando el bot y ahora requieran intervención humana.

Espero se entienda! Sino, escríbeme por favor.

**Comment by vinixcode** [comment]
Cerrando ticket.
