### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by caviva** [Vinix-Code-Dev/curso-api-whatsapp-frontend#59]
Hola Juan, muchas gracias por el curso, he aprendido bastante.

Intenté desplegar el backend en un servidor y me funciona todo (registra los mensajes enviados en la BD, consulta los mensajes y demás) excepto que no procesa los webhooks que llegan, no registra los mensajes entrantes en la BD ni cambia los estados de los mismos. 

En local lo hace perfecto pero en el servidor en producción no, sabes que podría estar pasando?

Muchas gracias

**Comment by vinixcode** [comment]
Hola @caviva 

Gracias por tus palabras!

Podrias por favor ampliar un poco más de información sobre el servidor? Hosting? Configuración? Esto será útil para ayudarte a diagnosticar tu problema.

Sin embargo, estoy casi seguro que el problema tiene que ver con el servidor que procesa las colas (el comando `php artisan queue:work` )

**Comment by caviva** [comment]
Gracias @vinixcode por tu respuesta, te puedo comentar que el servidor en donde se ha intentado desplegar es uno compartido que se administra por CPanel. Ya estoy revisando el tema de las colas y su integración en dicho servidor, aunque en ese tipo de servidores compartidos no es viable.

**Comment by vinixcode** [comment]
Entiendo. Nosotros tenemos una guía completa de como subir la aplicación a Amazon Web Services, en caso de que luego la desees adquirir.

En cualquier caso, escribenos por favor cualquier duda que tengas. Saludos!

**Comment by caviva** [comment]
Me interesa lo de la guía.

**Comment by vinixcode** [comment]
@caviva si ingresar al área del curso, vas a ver que la última sección se llama "Guía de Hosting en AWS". Ahí encontrarás la información.

Cerraré este ticket, pero por favor reabrelo si tienes algún comentario o duda adicional.
