### ISSUE TITLE
Error al verificar webhook utilizando ngrok

### ISSUE THREAD

**Issue by pperatta** [Vinix-Code-Dev/curso-api-whatsapp-frontend#6]
Buenas tardes,
Al verificar la URL de devolución de llamada,recibo el mensaje :

"No se ha podido validar la URL de devolución de llamada ni el identificador de verificación. Comprueba la información proporcionada o vuelve a intentarlo más tarde."

LLuego de utilizar la herramienta ngrok, realizo el procedimineto que se puede ver en el video.
1) Pruebo localhost la ruta verifywebhook
2) Luego la pruebo en la url sumnistrada por ngrok
3) Y por último intento verificarla en en el servidor de Meta

![image](https://user-images.githubusercontent.com/47986283/203403716-b8e26177-1dd5-44ce-8ea1-cf89694e76a9.png)

https://user-images.githubusercontent.com/47986283/203403791-9c40a306-b9ac-4714-b06b-a36ced578c03.mp4

**Comment by vinixcode** [comment]
Pablo, gracias por el video. Podrias por favor hacer click en el boton de "Verificar y guardar" y luego mostrar en ngrok el log de la peticion que se hizo. Gracias.

**Comment by pperatta** [comment]
No llega ninguna notificación luego del error

**Comment by pperatta** [comment]
https://user-images.githubusercontent.com/47986283/203406438-d37c73e7-695e-42ba-95e5-e432bb6b8d5a.mp4

**Comment by vinixcode** [comment]
Pablo, revisa este nuevo video que grabé sobre este problema y mira si con esto puedes resolverlo!
https://vimeo.com/773951222/2b5003ce13

**Comment by vinixcode** [comment]
Pablo, acabo de actualizar el video para mencionar algo que puede estar causando problemas con ngrok. Se habla a partir del minuto 10:14. Revisalo por favor (es el mismo enlace anterior).

**Comment by pperatta** [comment]
Gracias Juan, pero ya estaba registrado con un plan free.

**Comment by c0rtex** [comment]
Pablo, si el problema lo está causando ngrok, simplemente usa una alternativa que te permite crear túneles al exterior desde tu local. Aquí hay algunas alternativas: https://www.softwaretestinghelp.com/ngrok-alternatives/

**Comment by pperatta** [comment]
Gracias Juan, esa era la idea para hoy, igualmente seguí avanzando pero
trabajando en glitch.

**Comment by RAGUDIG** [comment]
> Pablo, si el problema lo está causando ngrok, simplemente usa una alternativa que te permite crear túneles al exterior desde tu local. Aquí hay algunas alternativas: https://www.softwaretestinghelp.com/ngrok-alternatives/

he probado con localtunnel y sigue dando el error

**Comment by c0rtex** [comment]
Señores es difícil la verdad resolver este problema sin ver en funcionamiento todo. Estoy pensando que será mejor realizar una llamada en la que podamos estar todos y resolver estas y otras dudas en tiempo real. Tendrá que ser para la próxima semana ya que esta semana me es imposible. Por correo les estaré enviando más información ya que realmente deseo que puedan avanzar y sacarle provecho al curso.

Saludos.

**Comment by pperatta** [comment]
Estimado Juan, no hay problema estoy de acuerdo, aunque en mi caso
particular el problema es con ngrok.
Intente usar Localtunnel, ya que mi sistema operativo es windows, y la url
que expone no funciona.
De alguna forma se me están terminando las alternativas para evitar este
inconveniente, claro dentro de mis conocimientos.
Por favor si se te ocurre alguna otra idea para poder avanzar, será
bienvenida.

Saludos Pablo

**Comment by ysernah** [comment]
Yo tambien tengo ese problema con ngrok no valida  por eso lo hice con dominio y hosting ahi si valida pero igual tengo el problema que webhook no me devuelve nada me retorna indefinido hub_mode

{"success":false,"error":"Undefined array key "hub_mode""}

**Comment by c0rtex** [comment]
Señores tengo disponibilidad para que nos reunamos este lunes 28 de Noviembre a las 4pm hora de Colombia. ¿Les queda bien ese día para que resolvamos las dudas a través de una llamada?

**Comment by pperatta** [comment]
Estimado Juan, en principio no tendria problemas, siempre y cuando haya una alternativa a ngrok.

**Comment by RAGUDIG** [comment]
> Señores tengo disponibilidad para que nos reunamos este lunes 28 de Noviembre a las 4pm hora de Colombia. ¿Les queda bien ese día para que resolvamos las dudas a través de una llamada?

Buenas tardes estimado, por donde sera la reunion, por aqui pasarias el link supongo.

**Comment by pperatta** [comment]
Para aquellos que tienen problemas con la url expuesta por ngrok, les dejo la solución

https://ngrok.com/docs/integrations/whatsapp/webhooks

**Comment by ysernah** [comment]
> Para aquellos que tienen problemas con la url expuesta por ngrok, les dejo la solución
> 
> https://ngrok.com/docs/integrations/whatsapp/webhooks

Gracias amigo probare para ver si se soluciona

**Comment by RAGUDIG** [comment]
> Para aquellos que tienen problemas con la url expuesta por ngrok, les dejo la solución
> 
> https://ngrok.com/docs/integrations/whatsapp/webhooks

a que problmea te refieres?

al que debuelve {"success":false,"error":"Undefined array key "hub_mode""}

**Comment by vinixcode** [comment]
Pablo, gracias por compartir la solución al problema con ngrok! No conocía el link y veo que con esto se soluciona el problema que existe. Cerraré este issue, y continuaré con la conversación con @RAGUDIG y @ysernah en el otro ticket.
