### ISSUE TITLE
No logro Instalar Larval, me da error por la diferencia de versiones 

### ISSUE THREAD

**Issue by Harbeilinibarguen** [Vinix-Code-Dev/curso-api-whatsapp-frontend#60]
No he podido instalar Laravel con componer, ya que ahora hay versiones actualizadas, he tratado de instalar otras versiones pero me da error

https://snipboard.io/9AXbxp.jpg

**Comment by vinixcode** [comment]
Hola @Harbeilinibarguen es importante que utilices PHP 7 ya que es un requerimiento de Laravel 8.x. Sin embargo, tambien puedes seguir el curso si quisieras con PHP 8 e instalar Laravel 9.x

**Comment by vinixcode** [comment]
Cerraré este ticket, pero por favor reabrir en caso de que haya alguna duda adicional.
