### ISSUE TITLE
Existe una manera de identificar si un número tiene WhatsApp válido?

### ISSUE THREAD

**Issue by andresperalta1550** [Vinix-Code-Dev/curso-api-whatsapp-frontend#63]
Hola !!

Si quiero escribirle a un número de WhatsApp, ¿como puedo validar si existe ese número?, al enviar un mensaje mediante la API, me genera el siguiente error:

{
    "error": {
        "message": "(#100) Invalid parameter",
        "type": "OAuthException",
        "code": 100,
        "error_data": {
            "messaging_product": "whatsapp",
            "details": "Invalid parameter"
        },
        "fbtrace_id": "AS3rrySA_w5jjt5bXAE4yxT"
    }
}

Por el contrario cuando envío un mensaje a un número válido si sale perfectamente.

**Comment by vinixcode** [comment]
Hola Andrés,

No es posible, como lo puedes ver en la documentación: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages es necesario que intentes enviar el mensaje y si te arroja error, es porque no existe:

"With the Cloud API, there is no longer a way to explicitly check if a phone number has a WhatsApp ID. To send someone a message using the Cloud API, just send it directly to the customer's phone number —after they have [opted-in](https://developers.facebook.com/docs/whatsapp/overview/getting-opt-in). See [Reference, Messages](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#examples) for examples."
