### ISSUE TITLE
Ayuda con subida front end en azure

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#64]
Buenas tardes, Juan tengo el backend del proyecto ya montado y funcionando en azure, pero el fronted no he podido configurarlo. Tu de pronto has hecho ese montaje del front a un app services en azure? si es asi te agradeceria por alguna información. Gracias

**Comment by c0rtex** [comment]
Leandro, buenas tardes.

Lastimosamente no cuento con experiencia de Azure así que no te podría ayudar.

Disculpa el inconveniente!
