### ISSUE TITLE
It doesn't run

### ISSUE THREAD

**Issue by jjaimes** [Vinix-Code-Dev/curso-api-whatsapp-frontend#65]
Hi Vinix,

Great curse.

Now, I am facing this issue when execute the command npm run dev. Please, see the attachment.

What am I missing?

![01_Error_npm_run_dev](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/15263362/24810260-3ef6-4419-b0ab-16db4641576d)

**Comment by c0rtex** [comment]
Hi @jjaimes 

I can see that you installed Nuxt 3.x instead of version 2.x. Please make sure that you install specifically version 2.x, using the instructions provided in this link: https://nuxtjs.org/docs/get-started/installation/

**Comment by jjaimes** [comment]
Thanks for your reply. 

You can close this ticket.

Cool hat!

**Comment by c0rtex** [comment]
That photo is at least 7 years old. lol. Thanks though.

Closing ticket.
