### ISSUE TITLE
error de mensaje interactivo

### ISSUE THREAD

**Issue by melvingomez** [Vinix-Code-Dev/curso-api-whatsapp-frontend#67]
Estoy enviado un mensaje interactivo de prueba pero me devuelve un error al enviar este tipo mensaje
mi estructura es la siguiente
Array
(
    [messaging_product] => whatsapp
    [recipient_type] => individual
    [to] => 50374142510
    [type] => interactive
    [interactive] => Array
        (
            [type] => button
            [body] => Array
                (
                    [text] => Welcome to wapisell the best tool to 
                )

            [action] => Array
                (
                    [buttons] => Array
                        (
                            [0] => Array
                                (
                                    [type] => reply
                                    [reply] => Array
                                        (
                                            [id] => wpbtn_1684681564
                                            [title] => Español
                                        )

                                )

                            [1] => Array
                                (
                                    [type] => reply
                                    [reply] => Array
                                        (
                                            [id] => wpbtn_1684681564
                                            [title] => English
                                        )

                                )

                        )

                )

        )

)

erro dice esto : Parameter value is not valid

**Comment by vinixcode** [comment]
@melvingomez buenas tardes. Puedes apoyarte en la documentación, en la que te dan ejemplos de la petición que debes hacer: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#interactive-messages

Por ejemplo:

`{
  "messaging_product": "whatsapp",
  "recipient_type": "individual",
  "to": "PHONE_NUMBER",
  "type": "interactive",
  "interactive": {
    "type": "button",
    "body": {
      "text": "BUTTON_TEXT"
    },
    "action": {
      "buttons": [
        {
          "type": "reply",
          "reply": {
            "id": "UNIQUE_BUTTON_ID_1",
            "title": "BUTTON_TITLE_1"
          }
        },
        {
          "type": "reply",
          "reply": {
            "id": "UNIQUE_BUTTON_ID_2",
            "title": "BUTTON_TITLE_2"
          }
        }
      ]
    }
  }
}`

**Comment by vinixcode** [comment]
<img width="1058" alt="image" src="https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/63106073/41b49bfd-a5ae-4091-8df2-2fdab7ce8c36">

**Comment by melvingomez** [comment]
Gracias por responder pude solucionarlo, leei la documentacion

**Comment by vinixcode** [comment]
Con gusto @melvingomez ! Cerraremos este ticket.
