### ISSUE TITLE
Clase 10 Error webhooks

### ISSUE THREAD

**Issue by lacotecnologia** [Vinix-Code-Dev/curso-api-whatsapp-frontend#68]
Hola Juanes ,primero darte las gracias por este gran curso .
bueno quisiera que me ayudaras para poder seguir ,no he podido identificar este error en esta clase 10 ,aclaro que no tuve errores con el webhook en la clase 7.
tengo conexión a la BD ,la migración se hizo correctamente.
el error generado del webhook dice que estoy devolviendo un booleano y el parametro espera un array.

aca mi codigo que es igual al del video
  public function verifyWebhook(Request $request)
    {
        try {

            $tokenVerify=env('WHATSAPP_VERIFY_TOKEN'); //variable que asigna el token ingresado en DF(developer Facebook)
            $query=$request->query();//Utilizamos la variable $query para extraer los parametros del webhooks

            $mode=$query['hub_mode'];   //Estas 3 variables son los querys params que devuelve el webhooks por medio de $query
            $token=$query['hub_verify_token'];
            $challenge=$query['hub_challenge'];

            if ($mode && $token){
                if($mode==='subscribe' && $token==$tokenVerify){
                    return response($challenge,200)->header('Content-Type','text/plain');
                }
            }
            throw new Exception('Invalid request');

        } catch (Exception $e) {
            return response()->json([
                'success'=> false,
                'error' => $e->getMessage(),   
            ],500);
        }
    }

    public function processWebhook(Request $request)
    {
        try {

            $bodyContent=json_decode($request->getContent(),true); //guardamos en forma de array el json obtenido del $request
                $body='';

            //Determina los valores que estan en el array
            $value=$bodyContent['entry'][0]['changes'][0]['value']; 
            

            if(!empty($value['messages'])) //Verificamos que sea un mensaje de texto
            {   
                $exist=Message::where('wam_id',$value['messages'][0]['id'])->first();
                
                if(empty($exist->id))
                {
                    if($value['messages'][0]['type'] == 'text')
                    {
                        
                        $message = $this->_saveMessage(
                            
                            $value['messages'][0]['text'],['body'],'text',
                            $value['messages'][0]['from'],
                            $value['messages'][0]['id'],
                            $value['messages'][0]['timestamp']
                        );var_dump($value);
                    }
                    else
                    {
                        $type=$value['messages'][0]['type'];
                        if(!empty($value['messages'][0][$type]))
                        {
                            $message = $this->_saveMessage(
                                "($type): \n _" . serialize($value['messages'][0][$type]) . "_",
                                'other',
                                 $value['messages'][0]['from'],
                                 $value['messages'][0]['id'],
                                 $value['messages'][0]['timestamp']
                            ); 
                        }
                    }
                }
 
            }    
            return response()->json([
                'success'=> true,
                'data' => $body,
            ],200);

        } catch (Exception $e) {
            return response()->json([
                'success'=> false,
                'error' => $e->getMessage(),   
            ],700);
        }
    }

    private function _saveMessage($message,$messageType,$waId,$wamId,$timestamp= null,$caption= null,$data = '')
    {
        $wam = new Message();
        $wam->body = $message;
        $wam->outgoing = false;
        $wam->type = $messageType;
        $wam->wa_id = $waId;
        $wam->wam_id = $wamId;
        $wam->status ='send';
        $wam->caption = $caption;
        $wam->data = $data;

        if(!is_null($timestamp))
        {
           $wam->created_at=Carbon::createFromTimestamp($timestamp)->toDateTimeString();
           $wam->updated_at=Carbon::createFromTimestamp($timestamp)->toDateTimeString();
        }
        $wam->save();

        return $wam;
    }

**Comment by vinixcode** [comment]
Hola @lacotecnologia podrias por favor mostrarme un pantallazo del error que estas recibiendo?

**Comment by lacotecnologia** [comment]
si claro 
<img width="617" alt="Captura de Pantalla 2023-05-30 a la(s) 10 26 48 a m" src="https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/61571743/37db2456-63e5-4fff-81a6-a4756afad7d6">
<img width="707" alt="Captura de Pantalla 2023-05-30 a la(s) 10 27 22 a m" src="https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/61571743/8002f549-fdf3-4d58-ae7c-cae627f5837a">

**Comment by vinixcode** [comment]
Hola @lacotecnologia según parece, la versión que estás utilizando de una de las librerías de Laravel, ya no es compatible con el código del curso. Sin embargo, es completamente solucionable. Te propongo una manera de solucionarlo:

1. Descarga todo el código del proyecto y copia el código de ese archivo en específico y verifica en donde puede haber una diferencia. El código está en el módulo "Código Completo del Curso", ahí tendrás el código del backend.
2. Asegúrate que copias también estos 2 archivos: composer.json y composer.lock. Y cuando los copies, borra la carpeta "vendor" de tu proyecto, y vuelve a correr `composer install` para que te instale las versiones específicas que utilizamos en el curso.

**Comment by vinixcode** [comment]
Hola @lacotecnologia pudiste hallar la solución?

**Comment by lacotecnologia** [comment]
Hola juanes ,el codigo sigue generando error he probado en postman ,creando un nuevo controlador he enviando un post con los valores seteados y funciona e inserta en la tabla sin problemas .y al revisar el codigo completo ya tienes el codigo diferente porque me imagino que mas adelante en el curso se mejoran las peticiones ,la verdad me gustaria entender el curso y llevarlo al pie de la letra ,si alguien mas sabe que puede estar pasando pido su colaboracion saludos .

**Comment by vinixcode** [comment]
@lacotecnologia pero entonces te funciona en Postman y no cuando la petición viene desde WhatsApp? Podrías por favor grabar un video de máximo 5 minutos mostrándome todo lo que estás haciendo para ver en dónde está fallando el código?

**Comment by vinixcode** [comment]
@lacotecnologia cómo te ha ido con el problema que tienes? Si tienes forma de grabar el video, te agradecería para poder revisar qué puede estar ocurriendo. Gracias!

**Comment by lacotecnologia** [comment]
Juanes gracias por el apoyo ,esta semana tuve que viajar retomo el curso el
próximo  lunes .muchas gracias

**Comment by vinixcode** [comment]
Estaré atento @lacotecnologia

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad. @lacotecnologia por favor reabre el ticket si aún requieres ayuda. Gracias!
