### ISSUE TITLE
Problemas creacion Plantillas

### ISSUE THREAD

**Issue by BigtronicaSAS** [Vinix-Code-Dev/curso-api-whatsapp-frontend#69]
Hola Juan, Dios te bendiga. Agradecerte por el curso esta muy bien explicado. Resulta que hace dias, estoy intentando crear plantillas pero siempre el estado es "Rechazado". He investigado y encontrado que hay parametros que se deben respetar por temas de politica. Pero, he intentado con las indicaciones en internet incluso con el ejemplo que creaste en el curso pero nada. ¿A que se debe el problema? Cree una cuenta nueva de facebook para no tener problemas. Quedo atento a tu respuesta. Bendiciones Camilo Alvarez.

**Comment by vinixcode** [comment]
@BigtronicaSAS amén, Dios te bendiga!
¿Estás usando un teléfono de prueba o un teléfono de producción? Te recomiendo usar exclusivamente un número de producción para poder hacer el envío de las plantillas.

**Comment by vinixcode** [comment]
@BigtronicaSAS estaré atento a cualquier novedad que tengas referente a esto.

**Comment by BigtronicaSAS** [comment]
Juan, estoy usando el numero de prueba que me da Facebook para enviar mensajes a mi numero de celular! ¿Para adquirir un numero en producción que debo de hacer? Debo pasar mi tarjeta de credito si o si?

**Comment by vinixcode** [comment]
@BigtronicaSAS Meta te regala 1,000 conversaciones si las inicia el usuario.

Entonces puedes agregar un numero de produccion (es decir un numero real), no tiene que tener una plan de telefonia o datos, no es necesario. Solo debes tener la forma de poder recibir un codigo, sea por voz o mensaje. **Ten presente que ese numero cuando lo migres a la API, NO podras luego usarlo en la app movil.**

Despues agregas un medio de pago, y te aseguro que podras hacer las pruebas que quieras sin gastarte ni un dolar.

Puedes mirar este video: https://vimeo.com/738412209?share=copy

**Comment by BigtronicaSAS** [comment]
Ah ya! Es decir que si o si se necesita el CRM. Es decir si pongo el numero oficial de la empresa a produccion no se puede abrir Whatsapp Web y tampoco el App de Whatsapp del numero en produccion. ¿Es correcto?

**Comment by BigtronicaSAS** [comment]
Juan Gracias hare eso hoy en la noche. Otro tunel que me recomiendes que no sea ngrok. No se por que estoy teniendo problemas con el. Cree la cuenta, hice el paso a paso y no me da el url publico del localhost.

**Comment by vinixcode** [comment]
@BigtronicaSAS Camilo, disculpa que he estado viajando y apenas pude responder.

1. Si migras el numero, no podras seguirlo usando en la version web ni la app movil.
2. Qué error te está dando ngrok? Podrías mostrarme? Te pregunto porque es la mejor opción para crear túneles.

**Comment by vinixcode** [comment]
@BigtronicaSAS estaré atento a tus comentarios.

**Comment by BigtronicaSAS** [comment]
Hola Juan, que Dios te bendiga. Lamento no haber respondido antes. Por fin pude resolver el problema en ngrok. Tuve que desinstalarlo debido a un conflicto con algunos permisos en mi PC. ¡Pero ya está solucionado! Por otro lado, hoy agregaré el número a producción para hacer pruebas y si tengo alguna duda, me comunicaré contigo.

Además, tengo una pregunta. Estoy considerando pagar por la clase de AWS Amazon del curso, pero tengo varias dudas. En primer lugar, me gustaría saber cuánto cuesta AWS Amazon para el proyecto. Somos una empresa de tráfico mediano que recibe alrededor de 100 clientes al día. No tengo experiencia previa con AWS, de hecho, lo adquiriré para iniciar mi aprendizaje. En nuestra empresa, tenemos nuestro comercio electrónico alojado en https://www.hostmonster.com/. ¿Es posible alojar el proyecto del curso en el hosting de HostMonster o debe ser en Amazon AWS? Al principio, no tuve en cuenta los costos en AWS y me preocupa que el gasto para la empresa sea una sorpresa significativa. En caso de ser posible con HostMonster, ¿existe algún costo adicional por recibir asesoría personalizada para implementarlo? Estoy dispuesto a pagar por la asesoría, si es posible. Agradezco mucho tu ayuda. Que Dios los bendiga.

**Comment by vinixcode** [comment]
@BigtronicaSAS me alegra que pudiste solucionar el problema con ngrok!

No es obligatorio usar AWS, pero si es recomendado. Con respecto a los costos, cuando tu creas una nueva cuenta en AWS ellos tienen algo llamado "free tier". Este "plan" es completamente gratuito en algunos servicios. Por ejemplo puedes crear una base de datos completamente gratis, un servidor completamente gratis, de tal manera que puedas seguir todo y poner a correr la aplicacion sin tener ningun gasto. Si tus necesidades aumentan y requieres mayor capacidad, puedes contratar algun otro servicio, pero los costos son muy favorables.

Tu puedes tener tranquilamente corriendo toda la aplicacion sin pagar mas de $10 dolares al mes (en caso de que no uses el plan pago). Ademas el servicio es pay-as-yo-go, es decir que solo pagas lo que consumas. Si por ejemplo pones a correr un servidor por 3 horas, solo te cobraran esas 3 horas.

No te preocupes por el tema de costos, en la guia de deployment a AWS se cubren varios de estos temas, para hacer uso eficiente de los recursos.

**Comment by BigtronicaSAS** [comment]
Gracias Juan, por tu informacion. Voy a pagar la clase. Dios te bendiga

**Comment by vinixcode** [comment]
Perfecto! Cerraré este ticket. Bendiciones.
