### ISSUE TITLE
Error en clase 10

### ISSUE THREAD

**Issue by miguelpda** [Vinix-Code-Dev/curso-api-whatsapp-frontend#7]
Cordial saludo, tengo un inconveniente con el curso ya que lo he seguido al pie de la letra pero me sale un error 500 y ya he creado 3 carpetas de la api, pensado que depronto me salte algún dato pero en todos los 3 proyectos de la api pasa lo mismo cuando llegó a ese punto en la clase #10 almacenando mensajes recibidos probé el túnel ngrok y ejecute /API/send-message y funciona sin problemas pero al momento de agregar el último código para guardar los me  sale  error 500 antes de eso va de maravilla, entonces pido ayuda para poder avanzar si es tan amable gracias 
Anexare las capturas

**Comment by c0rtex** [comment]
Miguel, claro que sí.

Por favor compártenos el código completo del controlador que te está tirando error, compártenos el error y de ser posible haz un video reproduciendo todo el error para ver que puede estar fallando. Gracias!

**Comment by miguelpda** [comment]
Buenas noches claro que sí mañana a primera hora lo hago

**Comment by miguelpda** [comment]
Buenas tardes

De acuerdo a lo hablado anteriormente acá comparto el video sobre mi error
https://drive.google.com/file/d/1FzGrf9wZyRhY5IENsO_GKly6Pf5IZJP5/view?usp=drivesdk

Espero tener una pronta respuesta para continuar con el proyecto o si
necesita algo más estaré atento
Cordialmente

Miguel Andrés Pérez

**Comment by ysernah** [comment]
Amigo pudiste validar webhook en facebook?

ademas facebook te envia datos asi como esto?

![image](https://user-images.githubusercontent.com/43530180/203864109-a91b1ce5-cb35-45ec-91d7-1b370581f6d2.png)

**Comment by miguelpda** [comment]
Hola si PS el webhook funciona a la perfección antes del último código que
compartes ena clase 10 después de eso me arroja el error

**Comment by ysernah** [comment]
Vi tu video a mi tambien me funciona el envio de mensajes normal pero al momento de verificar el webhook no me envia los datos por eso te decia y tambien no recibo mensajes

**Comment by miguelpda** [comment]
Entonces en ese caso que tendría que revisar en el webhook sin antes del
código que pasas funcionaba bien

**Comment by ysernah** [comment]
No soy el profesor amigo pero si prueba que webhook te envie los datos  asi como en la imagen para descartar que no sea eso
![203864109-a91b1ce5-cb35-45ec-91d7-1b370581f6d2](https://user-images.githubusercontent.com/43530180/203878072-6405f4f0-295d-4c4c-83c8-209ec219930b.png)

**Comment by c0rtex** [comment]
Miguel, revise el video y el problema es exactamente en la linea 155. Escribiste emty en vez de empty (te falta una p):

<img width="660" alt="image" src="https://user-images.githubusercontent.com/387958/203976831-644b7382-4857-4d6c-9785-aa11118aa867.png">

Deberia decir:

`
if (empty($exists->id)) {
`

Tambien es importante que observes que PHP siempre te dice porque te dio el error, incluso aparece en la respuesta en ngrok. Mira:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/387958/203977237-a0651bf3-de9f-4d37-b334-a563580d5a15.png">

Corrígelo y ya con esto te debería funcionar! Gracias por el video!

**Comment by c0rtex** [comment]
Gracias @ysernah por tus aportes 👍🏻

**Comment by miguelpda** [comment]
Hola buen día

Si eso también lo hice se me olvidó mostrarlo en el vídeo, pero si ponía
!emty o emty salía el mismo error y el webhook está funcionando bien la
conexión por qué al enviar mensajes aparece el request pero es que al
responder por Whatsapp no está guardando o no se está ejecutando lo que se
quiere en el tema de esa clase que es archivar el mensaje en la base de
datos

**Comment by vinixcode** [comment]
Miguel, el error es que no existe ninguna funcion llamada emty sino EMPTY (debe tener la p).

Si no esta bien escrito, te seguira tirando error 500.

**Comment by miguelpda** [comment]
Buenas de acuerdo voy a revisar pero en el vídeo aparece así y cuando lo
ejecuta PS funciona sin problema pero lo realizaré a ver qué tal gracias

**Comment by vinixcode** [comment]
@miguelpda lograste solucionar el problema?
Aquí te comparto el código completo del archivo MessageController.php para que lo tengas como referencia: https://gist.github.com/vinixcode/f5f4d5869fa2886f727caf94489b9cca

Ten presente que este es el archivo final así que tendrá mucho más código del que has visto hasta la lección #10.

**Comment by miguelpda** [comment]
Buenas si logré solucionar ese inconveniente pero ahora tengo otro y es
este el cual no me guarda los mensajes enviados

**Comment by vinixcode** [comment]
Miguel, recuerda por favor compartir los detalles del error, el codigo y demas datos utiles para saber cual es el problema especifico. Gracias!

**Comment by vinixcode** [comment]
Ya que el problema inicial en este ticket se soluciono, lo cerrare pero puedes abrir un ticket nuevo @miguelpda y explicar el problema de la base de datos.

**Comment by miguelpda** [comment]
Acá comparto un video donde subí el error

https://drive.google.com/file/d/1Gpyiww17GreaSnY3tu9casQpTFqnhWz2/view?usp=drivesdk

**Comment by miguelpda** [comment]
hola buenas como estas, el año pasado envie esta duda y aun no me dan
respuesta, espero puedan ver el video y me puedan ayudar gracias y feliz
año nuevo

**Comment by vinixcode** [comment]
Hola Miguel, la verdad se me escapó este mensaje debido a que el ticket ya estaba cerrado - lo acabo de reabrir.

Miguel, podrías por favor instalar XDebug en tu instalación de PHP para poder ir línea por línea y ver en dónde está el error?
También podrías asegurarte de tener el código tal cual como está en este archivo? https://gist.github.com/vinixcode/f5f4d5869fa2886f727caf94489b9cca

Quedo atento a tus comentarios, saludos.

**Comment by AlexanderGoi** [comment]
Hola que tal, por lo que ve amigo es el problema del Empty, y tienes en tu código emty, pero mencionas que pasa exactamente lo mismo.

![imagen](https://user-images.githubusercontent.com/58536439/217978108-bbc7f848-8608-454f-9d24-78f46f224f0e.png)

Intenta cambiarlo, más aparte detecte que tienes un error en la función _saveMessage, creo q con eso lo corriges, en tu video se ve asi $wa->dat = $data; y tu objeto de Message no contiene ningún dat como campo, es data
![imagen](https://user-images.githubusercontent.com/58536439/217979559-473ec1d6-2e61-464d-96d4-cab80f3ef631.png)

Espero que con esto ayude, y sigas con este curso tan interesante.
Saludos..!!

**Comment by miguelpda** [comment]
Ya revise todo el código en esas partes y están bien ya había corregido eso
antes pero igual sigue sin funcionar

**Comment by AlexanderGoi** [comment]
Crees que puedas compartir todo el código de tu MessageController

**Comment by miguelpda** [comment]
Claro que sí mañana a primera hora te lo paso

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.

**Comment by miguelpda** [comment]
buen dia
no había enviado porque el pc se me habia dañado y ya lo logre organizar,
ya esta funcionado asi que aproveche inmediatamente enviar lo que me
pidieron espero poder tener respuesta
gracias por su comprensión

**Comment by miguelpda** [comment]
Buenas tardes
Envié el archivo que me pidieron estoy atento a cualquier novedad para
continuar con el curso
Gracias

**Comment by vinixcode** [comment]
Hola @miguelpda 

Disculpa que no habia visto tu mensaje - la proxima vez recuerda por favor reabrir el ticket, ya que se habia cerrado y por eso no lo veiamos.

¿Dónde nos compartiste el archivo?
No lo vemos adjunto aquí en Github.

Estaremos atentos, gracias.

**Comment by miguelpda** [comment]
En un mensaje anterior lo envíe ya se los reenvío

**Comment by miguelpda** [comment]
Buenas
Este es el archivo controller que me solicitaron espero respuesta
Que tenga buen día

**Comment by vinixcode** [comment]
@miguelpda no hay ningun archivo. Por favor entra directamente a este link y sube el archivo: https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/issues/7

Gracias

**Comment by miguelpda** [comment]
Perfecto dale ya lo realizó

**Comment by miguelpda** [comment]
Buen día acá anexo el archivo solicitado 
[Message controller](https://drive.google.com/file/d/1P7EoHIPGL8gVsnLm5u8GM_S_wMSnIz7M/view?usp=drivesdk)

**Comment by vinixcode** [comment]
@miguelpda grabé un video para ti, mostrándote cómo podrías solucionar esto. Por favor míralo:

https://www.awesomescreenshot.com/video/15839812?key=8112af87094ef3c38fc8b57794481d28

Gracias

**Comment by c0rtex** [comment]
@miguelpda ¿pudiste revisar el video? Saludos

**Comment by miguelpda** [comment]
Buen día
Si ya estoy probando no me.habia llegado la notificación del vídeo gracias

**Comment by vinixcode** [comment]
@miguelpda cerraremos este ticket pero si tienes alguna duda adicional, por favor reabrelo!

Gracias

**Comment by miguelpda** [comment]
buen día como estas, por acá ando retomando las clases del curso nuevamente pero aun tengo fallas en esa parte de la clase donde me quede y ya he estado revisando pero no veo aun la falla del por que  no me guarda la informacion del mensaje en la base de datos
