### ISSUE TITLE
Clase 9. Bases de datos para WhatsApp

### ISSUE THREAD

**Issue by SebasMoreno145** [Vinix-Code-Dev/curso-api-whatsapp-frontend#70]
Hola! Muchas gracias por este curso. Estaré compartiendo por acá mis logros con esta excelente guía, por ahora me encuentro algo atascado en la Clase 9. He migrado de los Controladores de Prueba a los nuevos para el uso de la API y no logro verificar esta URL.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/d83e2d13-98be-4bcd-a677-26eb610de0dc)

Esto es lo que obtengo en ngrok.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/d584598b-e57a-4772-8885-1bb8cf7a47fd)

Tengo las variables de entorno correctamente configuradas.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/12b49114-2308-4330-a38a-e0c9a96cb6e6)

Y también he cambiado las rutas, en donde estarán disponibles estos métodos.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/78e2ff28-c99f-45c7-afd4-89380818b5b8)

Déjame saber si necesitar ver algo mas, discúlpame si no adjunto la información suficiente, es mi primer proyecto en Laravel, estaré intentando solucionar este error, en caso de encontrarlo, dejare aca la solución.

**Comment by SebasMoreno145** [comment]
ACTUALIZACION: He intentado volver la información de las variables, a sus métodos. Sin usar el .ENV y ha funcionado correctamente, ¿Hay algo en especial que deba de hacer para poder usar este archivo con variables globales? Muchas gracias.

**Comment by vinixcode** [comment]
@SebasMoreno145 lo más probable es que si modificaste el archivo .env debas limpiar la cache de Laravel:

Intenta correr estos comandos y probar de nuevo:

`php artisan config:clear
php artisan cache:clear
php artisan clear-compiled`

**Comment by SebasMoreno145** [comment]
Hola Juanes, he intentado seguir estos pasos y de momento no logro usar el archivo .env
Ejecute los comandos desde el VsCode y también desde la terminal sobre la carpeta, pero siempre debo usar las variables en los métodos a usar.  ¿Puede intentar algo mas?

**Comment by SebasMoreno145** [comment]
Hola Juanes. Muchas gracias por tu respuesta! Me ha funcionado perfectamente.

**Comment by vinixcode** [comment]
Maravilloso! Cerrando ticket.
