### ISSUE TITLE
Envio de mensajes desde WEB

### ISSUE THREAD

**Issue by SebasMoreno145** [Vinix-Code-Dev/curso-api-whatsapp-frontend#71]
Hola Juan, he estado intentado solucionar un problema, pero no veo que es lo que sucede.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/5006ff98-9ce7-4eb2-bfd0-269fefff60c1)

Esta es la respuesta que siempre tengo al intentar enviar un mensaje desde la web. 
He revisado mi código, incluso copie el que dejas al final del curso y no consigo esto. ¿Podrian ayudarme? Gracias

**Comment by SebasMoreno145** [comment]
Esta es la libreria, con la funcion de send text
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/44342548-195f-4348-828e-a20633c8f9d7)

Y desde aca se instancia.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/af50b69f-8a88-44af-b3fc-7a1ba15adfd7)

**Comment by SebasMoreno145** [comment]
Dejare un poco mas de informacion que puede ser util para la ayuda.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/ba3bfa6e-e277-4903-8c17-d07c075dc8ed)

Aca el error.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/f14590e2-31eb-4ea7-a23f-c0471bb5189f)

Decidí usar el código del curso para avanzar mas rápido, puesto que estoy implementando un caso real, pero obtengo el mismo error.
También he comprado la guia para desplegar en AWS, he intentado seguir esta para ver que tal se comporta, pero la guía no esta actualizada, las opciones de creación y versiones ya no están disponibles en AWS. ¿Podrías ayudarme con esto?

**Comment by SebasMoreno145** [comment]
Juan no he logrado resolver este error, tengo 2 escenarios. 

1. En el código que yo he construido, siguiendo el curso si me envían los mensajes, pero los que recepciono  también quedan a la derecha, como si fueran enviados desde la web.

2. Descargue y seguí la clase con todo el código listo, haciendo las modificaciones pertinentes y no logro que salgan los mensajes (Los entrantes llegan sin lio)

**Comment by vinixcode** [comment]
@SebasMoreno145 según el error, parece ser un problema con el token, o los IDs que estás utilizando.

Verifica que las variables de entorno contienen la información correcta:

WHATSAPP_API_TOKEN
WHATSAPPI_API_PHONE_ID
WHATSAPP_BUSINESS_ID

Una vez lo hagas, intenta de nuevo por favor y confírmame si te ha funcionado. Gracias!

**Comment by SebasMoreno145** [comment]
Hola Juan, muchas gracias por tu respuesta. Creo que no va por ahi el tema, por que de ser así los mensajes entrantes no llegarían a la web o estoy errado? ¿Puedes revisar también el tema de AWS? Muchas gracias.

**Comment by SebasMoreno145** [comment]
Hola Juan, sigo sin poder solventar este error. 
He realizado toda la configuracion con tu codigo, y este es el error que tengo al enviar mensajes.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/b6a43136-7bb6-4c32-88ba-8dd8cbeeb1f1)

De aca saque la info relacionada

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/c186a1ef-b949-41e1-9e69-b4fffcde3cee)

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/fc29a734-c3d1-41d7-93e4-ed8036f42af3)


Cabe resaltar, que los entrantes están funcionado sin lio. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/fac71923-8212-47da-a845-c44f88d9755e)

Tu ayuda, por favor

**Comment by vinixcode** [comment]
@SebasMoreno145 para determinar tu problema, podrias por favor revisar este video y seguir las instrucciones para el envio de mensajes desde Postman?

https://www.youtube.com/watch?v=ZDdSPLJUPKA

Si te funciona o no te funciona, escribeme aqui por favor y te dira como procedes.

Estare pendiente de tu mensaje para ayudarte en la mayor brevedad posible. Gracias Sebastian.

**Comment by SebasMoreno145** [comment]
Hola Juan, muchas gracias por tu ayuda.
Siguiendo el video, y aplicándolo a el código, me he encontrado con que POSTMAN me devuelve un 200 OK, pero este Template nunca llega, revisando un poco me he encontrado con esto.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/0c789237-eeeb-4806-bebf-1ad05e93bdac)

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/28d86073-1bb3-47f3-bf08-a0fd4291be2f)

Tratare de resolver esto, creando otra cuenta publicitaria y te cuento, además ¿Haz podido revisar el tutorial de despliegue en ASW? Creo que ha cambiado un poco el Setup inicial y no logro seguir la guia. 

Te estaré contando...

**Comment by vinixcode** [comment]
Perfecto @SebasMoreno145 si bloquearon tu cuenta, efectivamente no llegará ningún otro mensaje.

Voy a revisar la guía AWS y te estaré comentando.

**Comment by SebasMoreno145** [comment]
Juan! Muchas gracias era justamente eso ya lo he logrado. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/245a6a73-bfc0-4e8a-8739-2ec7e702836d)

Seguimos en este hilo para el tema del AWS? O genero uno nuevo para que sea mas visible para todos. 

Nuevamente gracias!!!!!
