### ISSUE TITLE
Cómo agrego el frontend y backend en CPanel

### ISSUE THREAD

**Issue by crivadron** [Vinix-Code-Dev/curso-api-whatsapp-frontend#72]
Hola Juan para subir el frontend y backend en CPanel como lo puedo hacer?

Subí los dos sitios en la misma carpeta de CPanel, pero no logro desplegar el frontend

Alguna sugerencia?

**Comment by vinixcode** [comment]
Hola @crivadron 

No he realizado el procedimiento en cPanel, pero basicamente ten en cuenta un par de cosas:

1. El frontend debes generarlo usando el comando `npm run generate` y esto te creará una carpeta llamada /dist . El contenido de esta carpeta es lo que debes subir al cPanel y funcionará como frontend (es un montón de archivos estáticos). Asegúrate de haber configurado también el nuxt.config.js con las respectivas variables de entorno, antes de ejecutar el comando. (Todo esto de las variables, se explica a lo largo del curso).
2. El backend es un proyecto Laravel, así que debes tener configurado PHP 7 u 8 para poder alojar el proyecto.

Te recomiendo que revises la guía de despliegue a AWS en la que se cubre cómo hacerlo en Amazon, y quizás te dará algo de idea de como hacerlo en cPanel.

**Comment by vinixcode** [comment]
Cerraré este ticket por inactividad.
