### ISSUE TITLE
Numero de twilio

### ISSUE THREAD

**Issue by crivadron** [Vinix-Code-Dev/curso-api-whatsapp-frontend#73]
Hola al comprar un numero de telefono en twilio se puede utilizar para whatsapp?
Ya que al revisar muestra que es local y no mobile

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/5227086/9f208039-e22f-4bc0-85a3-9f239ce49810)

**Comment by vinixcode** [comment]
Hola @crivadron si es posible hacerlo.

Puedes recibir ahi mensajes o llamadas (las puedes redirigir para que te lleguen a tu número personal).

**Comment by vinixcode** [comment]
Cerraré este ticket por inactividad.

**Comment by crivadron** [comment]
En twilio no hay mas numeros de otros estados... la mayoría on de IL?

Si ese numero de twlio lo puedo direccionar a mi telefono para contestar? tiene algun costo?
Siempe se paga $1.15 o hay mas costos?

**Comment by vinixcode** [comment]
Si haces envío de mensajes por Twilio, los costos aumentas. Si solo usas la línea para verificar WhatsApp, no tienes más costos adicionales.

Si hay otros números de otros estados, puedes filtrarlos por código de área (por ejemplo pon 954 en la búsqueda). En cualquier caso, no te sabría responder sobre la rotación de números que pueda hacer Twilio ya que depende de la disponibilidad que ellos tengan.
