### ISSUE TITLE
Frontend Vs Whatsapp Web

### ISSUE THREAD

**Issue by leomontano** [Vinix-Code-Dev/curso-api-whatsapp-frontend#74]
Disculpa la pregunta pero tengo esta duda:

En un ambiente de producción con el sistema funcionando al 100%,

 ¿ Cual sería la utilidad de usar el frontend para enviar mensajes Vs usar el web.whatsapp.com ?

**Comment by vinixcode** [comment]
Hola @leomontano esta es un excelente pregunta y de hecho es algo que yo mismo me pregunté en su momento.

Recuerda que la API de WhatsApp está diseñada para negocios que desean realizar uso personalizado y masivo de la API de WhatsApp.

* Deseas hacer envío de mensajes masivos? Usa la API
* Deseas utilizar inteligencia artificial? La API es ajusta para esto
* Deseas integrar tu CRM, o plataforma de citas, o hacer envío de mensajes de forma automatizada? La API es perfecta para esto
* Hay más usos, pero principalmente para cualquier caso en el que tu programaticamente quieras enviar mensajes WhatsApp (incluído chatbots y demás), la API es la opción más acertada

Ahora, suponiendo que según las necesidades que tienes decides que la API es tu mejor opción, entonces ten en cuenta lo siguiente:

1. Para hacer uso de la API de WhatsApp es absolutamente indispensable que construyas alguna especie de interfaz para poder chatear, ya que Meta no proporciona ninguna página de chat cuando usas la API.
2. Si bien esto puede ser mucho trabajo inicialmente, esta flexibilidad te permite construir una interfaz a tu medida, que por ejemplo te permita...:
* Tener multiples agentes (o humanos) en un solo chat, y saber que persona envió cada mensaje. Creeme que esto es algo que los negocios buscan todo el tiempo.
* Permitir transferir chats entre agentes, usando la misma interfaz.
* Practicamente cualquier caso de uso que tu quieras. Porque al ser tu el que crea la interfaz, la puedes hacer tan amigable como quieras, para que los negocios que usen tu chat puedan aumentar exponencialmente su productividad.

En resumen, todo se reduce a los casos de uso que tu tengas.

Reciemente grabe un nuevo video en el que explico esto en detalle y te recomiendo que lo veas ya que te permitirá aclarar muchas dudas sobre la API:

https://www.youtube.com/watch?v=vxQ09a-1AIo

**Comment by leomontano** [comment]
Hola, buenas noches

Creo que no expresé bien mi pregunta.

La pregunta se refería exclusivamente a la utilidad de usar el frontend para las respuestas manuales en vez del https://web.whatsapp.com/ 

De antemano te agradezco la respuesta tan amplia que me diste y eso lo entiendo bien y es por la razón que compré este curso.

Igual no hay problema, la respuesta que me has dado ha respondido mi duda y te comento que conforme avanzo en el curso voy viendo y entendiendo mas la utilidad.

Ta agradezco y sigo adelante.

Saludos

**Comment by vinixcode** [comment]
@leomontano es porque no es posible usar web.whatsapp.com para chatear *desde* un número vinculado a la API de WhatsApp.

**Comment by leomontano** [comment]
Enterado. eso responde mi duda. Muchas Gracias

**Comment by vinixcode** [comment]
Perfecto! Cerrando ticket.
