### ISSUE TITLE
Nodejs como backend, peticion POST

### ISSUE THREAD

**Issue by TomasS-R** [Vinix-Code-Dev/curso-api-whatsapp-frontend#75]
Estoy implementando el metodo POST de la clase 15, pero no logro concretar bien, el metodo get lo conseguí sin problema pero no puedo hacer post. Entiendo que el curso esta en php pero si alguien tiene conocimientos agradezco su ayuda debido que el backend lo tenia creado ya pero quise el curso mas que nada por la implementación del front-end.

Las rutas las tengo declaradas de la siguiente forma:
```
router
.get("/", whatsappController.VerifyToken)
.post("/", whatsappController.ReceivedMessage)
.get("/messages", whatsappController.getMessage)
.get("/messages/:phone", (req, res) => {
    const wa_id = req.params.phone;
    whatsappController.show(wa_id, req, res);
})
.post("/sendmessage", whatsappFrontResponse.sendTextFront);
```
Como veran tengo el metodo post para enviar los mensajes en /sendmessage, las demas rutas funcionan sin problema, pero esta no le llega la informacion la cual es la siguiente:

Luego tengo los datos para poder comunicarme con meta, lo cual lo tengo de esta forma:

```
function SendMessageFrontWA(data){

    const options = {
        host:"graph.facebook.com",
        // Change the ID of the phone for production or development
        path:`/v15.0/${config.IDPHONE}/messages`,
        method:"POST",
        body:data,
        headers: {
            "Content-Type":"application/json",
            Authorization: `Bearer ${config.TOKEN}`
        }
    };
    const req = https.request(options, res => {
        res.on("data", d=> {
            process.stdout.write(d);
        });
    });

    req.on("error", error => {
        console.error(error);
    });

    req.write(data);
    req.end();
}
```
Y en la funcion para enviar el mensaje es la siguiente:
```
function sendTextFront(textResponse, number){ 
    const data = JSON.stringify({
        "messaging_product": "whatsapp",    
        "recipient_type": "individual",
        "to": number,
        "type": "text",
        "text": {
            "preview_url": true,
            "body": textResponse
        }
    });
    SendMessageFrontWA(data);
    return(data);
}
```
Luego en el programa principal lo llamo:
```
waFront.sendTextFront("Esto es un test",541189566747);
```
(El numero lo cambie para este ejemplo) Igualmente no estoy haciendo que cuando accedo a la ruta que finaliza en /sendmessage se envie el mensaje a mi whatsapp.

Desde ya si alguno puede darme una mano se agradece.

**Comment by TomasS-R** [comment]
Debo aclarar que si envio un mensaje al numero este responde lo que le indique arriba en el codigo, pero si entro a la url mencionada esta al parecer no conecta la informacion. Entiendo que tengo una falla al conectar con el metodo post

**Comment by vinixcode** [comment]
@TomasS-R podrías compartirnos por favor el error que recibes al hacer el post?

**Comment by TomasS-R** [comment]
AxiosError: Request failed with status code 404

 gru [info] at settle (/app/node_modules/axios/dist/node/axios.cjs:1909:12)

 gru [info] at Unzip.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:2989:11)

 gru [info] at Unzip.emit (node:events:525:35)

 gru [info] at endReadableNT (node:internal/streams/readable:1359:12)

 gru [info] at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

 gru [info] code: 'ERR_BAD_REQUEST',

 gru [info] config: {

 gru [info] transitional: {

 gru [info] silentJSONParsing: true,

 gru [info] forcedJSONParsing: true,

 gru [info] clarifyTimeoutError: false

 gru [info] },

 gru [info] adapter: [ 'xhr', 'http' ],

 gru [info] transformRequest: [ [Function: transformRequest] ],

 gru [info] transformResponse: [ [Function: transformResponse] ],

 gru [info] timeout: 0,

 gru [info] xsrfCookieName: 'XSRF-TOKEN',

 gru [info] xsrfHeaderName: 'X-XSRF-TOKEN',

 gru [info] maxContentLength: -1,

 gru [info] maxBodyLength: Infinity,

 gru [info] env: { FormData: [Function], Blob: [class Blob] },

 gru [info] validateStatus: [Function: validateStatus],

 gru [info] headers: AxiosHeaders {

 gru [info] Accept: 'application/json, text/plain, */*',

 gru [info] 'Content-Type': 'application/json',

 gru [info] Authorization: 'Bearer ***',

 gru [info] 'User-Agent': 'axios/1.4.0',

 gru [info] 'Content-Length': '147',

 gru [info] 'Accept-Encoding': 'gzip, compress, deflate, br'

 gru [info] },

 gru [info] method: 'post',

 gru [info] url: 'https://apiwanodejs.fly.dev/whatsapp/sendmessage',

 gru [info] data: '{"messaging_product":"whatsapp","recipient_type":"individual","to":541156987301,"type":"text","text":{"preview_url":true,"body":"Esto es un test"}}'

 gru [info] },

 gru [info] request: <ref *1> ClientRequest {

 gru [info] _events: [Object: null prototype] {

 gru [info] abort: [Function (anonymous)],

 gru [info] aborted: [Function (anonymous)],

 gru [info] connect: [Function (anonymous)],

 gru [info] error: [Function (anonymous)],

 gru [info] socket: [Function (anonymous)],

 gru [info] timeout: [Function (anonymous)],

 gru [info] finish: [Function: requestOnFinish]

 gru [info] },

 gru [info] _eventsCount: 7,

 gru [info] _maxListeners: undefined,

 gru [info] outputData: [],

 gru [info] outputSize: 0,

 gru [info] writable: true,

 gru [info] destroyed: true,

 gru [info] _last: true,

 gru [info] chunkedEncoding: false,

 gru [info] shouldKeepAlive: false,

 gru [info] maxRequestsOnConnectionReached: false,

 gru [info] _defaultKeepAlive: true,

 gru [info] useChunkedEncodingByDefault: true,

 gru [info] sendDate: false,

 gru [info] _removedConnection: false,

 gru [info] _removedContLen: false,

 gru [info] _removedTE: false,

 gru [info] strictContentLength: false,

 gru [info] _contentLength: '147',

 gru [info] _hasBody: true,

 gru [info] _trailer: '',

 gru [info] finished: true,

 gru [info] _headerSent: true,

 gru [info] _closed: true,

 gru [info] socket: TLSSocket {

 gru [info] _tlsOptions: [Object],

 gru [info] _secureEstablished: true,

 gru [info] _securePending: false,

 gru [info] _newSessionPending: false,

 gru [info] _controlReleased: true,

 gru [info] secureConnecting: false,

 gru [info] _SNICallback: null,

 gru [info] servername: 'apiwanodejs.fly.dev',

 gru [info] alpnProtocol: false,

 gru [info] authorized: true,

 gru [info] authorizationError: null,

 gru [info] encrypted: true,

 gru [info] _events: [Object: null prototype],

 gru [info] _eventsCount: 9,

 gru [info] connecting: false,

 gru [info] _hadError: false,

 gru [info] _parent: null,

 gru [info] _host: 'apiwanodejs.fly.dev',

 gru [info] _closeAfterHandlingError: false,

 gru [info] _readableState: [ReadableState],

 gru [info] _maxListeners: undefined,

 gru [info] _writableState: [WritableState],

 gru [info] allowHalfOpen: false,

 gru [info] _sockname: null,

 gru [info] _pendingData: null,

 gru [info] _pendingEncoding: '',

 gru [info] server: undefined,

 gru [info] _server: null,

 gru [info] ssl: null,

 gru [info] _requestCert: true,

 gru [info] _rejectUnauthorized: true,

 gru [info] parser: null,

 gru [info] _httpMessage: [Circular *1],

 gru [info] write: [Function: writeAfterFIN],

 gru [info] [Symbol(res)]: null,

 gru [info] [Symbol(verified)]: true,

 gru [info] [Symbol(pendingSession)]: null,

 gru [info] [Symbol(async_id_symbol)]: 60,

 gru [info] [Symbol(kHandle)]: null,

 gru [info] [Symbol(lastWriteQueueSize)]: 0,

 gru [info] [Symbol(timeout)]: null,

 gru [info] [Symbol(kBuffer)]: null,

 gru [info] [Symbol(kBufferCb)]: null,

 gru [info] [Symbol(kBufferGen)]: null,

 gru [info] [Symbol(kCapture)]: false,

 gru [info] [Symbol(kSetNoDelay)]: false,

 gru [info] [Symbol(kSetKeepAlive)]: true,

 gru [info] [Symbol(kSetKeepAliveInitialDelay)]: 60,

 gru [info] [Symbol(kBytesRead)]: 602,

 gru [info] [Symbol(kBytesWritten)]: 636,

 gru [info] [Symbol(connect-options)]: [Object]

 gru [info] },

 gru [info] _header: 'POST /whatsapp/sendmessage HTTP/1.1\r\n' +

 gru [info] 'Accept: application/json, text/plain, */*\r\n' +

 gru [info] 'Content-Type: application/json\r\n' +

 gru [info] 'Authorization: Bearer ***\r\n' +

 gru [info] 'User-Agent: axios/1.4.0\r\n' +

 gru [info] 'Content-Length: 147\r\n' +

 gru [info] 'Accept-Encoding: gzip, compress, deflate, br\r\n' +

 gru [info] 'Host: apiwanodejs.fly.dev\r\n' +

 gru [info] 'Connection: close\r\n' +

 gru [info] '\r\n',

 gru [info] _keepAliveTimeout: 0,

 gru [info] _onPendingData: [Function: nop],

 gru [info] agent: Agent {

 gru [info] _events: [Object: null prototype],

 gru [info] _eventsCount: 2,

 gru [info] _maxListeners: undefined,

 gru [info] defaultPort: 443,

 gru [info] protocol: 'https:',

 gru [info] options: [Object: null prototype],

 gru [info] requests: [Object: null prototype] {},

 gru [info] sockets: [Object: null prototype] {},

 gru [info] freeSockets: [Object: null prototype] {},

 gru [info] keepAliveMsecs: 1000,

 gru [info] keepAlive: false,

 gru [info] maxSockets: Infinity,

 gru [info] maxFreeSockets: 256,

 gru [info] scheduling: 'lifo',

 gru [info] maxTotalSockets: Infinity,

 gru [info] totalSocketCount: 0,

 gru [info] maxCachedSessions: 100,

 gru [info] _sessionCache: [Object],

 gru [info] [Symbol(kCapture)]: false

 gru [info] },

 gru [info] socketPath: undefined,

 gru [info] method: 'POST',

 gru [info] maxHeaderSize: undefined,

 gru [info] insecureHTTPParser: undefined,

 gru [info] path: '/whatsapp/sendmessage',

 gru [info] _ended: true,

 gru [info] res: IncomingMessage {

 gru [info] _readableState: [ReadableState],

 gru [info] _events: [Object: null prototype],

 gru [info] _eventsCount: 4,

 gru [info] _maxListeners: undefined,

 gru [info] socket: [TLSSocket],

 gru [info] httpVersionMajor: 1,

 gru [info] httpVersionMinor: 1,

 gru [info] httpVersion: '1.1',

 gru [info] complete: true,

 gru [info] rawHeaders: [Array],

 gru [info] rawTrailers: [],

 gru [info] aborted: false,

 gru [info] upgrade: false,

 gru [info] url: '',

 gru [info] method: null,

 gru [info] statusCode: 404,

 gru [info] statusMessage: 'Not Found',

 gru [info] client: [TLSSocket],

 gru [info] _consuming: false,

 gru [info] _dumped: false,

 gru [info] req: [Circular *1],

 gru [info] responseUrl: 'https://apiwanodejs.fly.dev/whatsapp/sendmessage',

 gru [info] redirects: [],

 gru [info] [Symbol(kCapture)]: false,

 gru [info] [Symbol(kHeaders)]: [Object],

 gru [info] [Symbol(kHeadersCount)]: 26,

 gru [info] [Symbol(kTrailers)]: null,

 gru [info] [Symbol(kTrailersCount)]: 0

 gru [info] },

 gru [info] aborted: false,

 gru [info] timeoutCb: null,

 gru [info] upgradeOrConnect: false,

 gru [info] parser: null,

 gru [info] maxHeadersCount: null,

 gru [info] reusedSocket: false,

 gru [info] host: 'apiwanodejs.fly.dev',

 gru [info] protocol: 'https:',

 gru [info] _redirectable: Writable {

 gru [info] _writableState: [WritableState],

 gru [info] _events: [Object: null prototype],

 gru [info] _eventsCount: 3,

 gru [info] _maxListeners: undefined,

 gru [info] _options: [Object],

 gru [info] _ended: true,

 gru [info] _ending: true,

 gru [info] _redirectCount: 0,

 gru [info] _redirects: [],

 gru [info] _requestBodyLength: 147,

 gru [info] _requestBodyBuffers: [],

 gru [info] _onNativeResponse: [Function (anonymous)],

 gru [info] _currentRequest: [Circular *1],

 gru [info] _currentUrl: 'https://apiwanodejs.fly.dev/whatsapp/sendmessage',

 gru [info] [Symbol(kCapture)]: false

 gru [info] },

 gru [info] [Symbol(kCapture)]: false,

 gru [info] [Symbol(kBytesWritten)]: 0,

 gru [info] [Symbol(kEndCalled)]: true,

 gru [info] [Symbol(kNeedDrain)]: false,

 gru [info] [Symbol(corked)]: 0,

 gru [info] [Symbol(kOutHeaders)]: [Object: null prototype] {

 gru [info] accept: [Array],

 gru [info] 'content-type': [Array],

 gru [info] authorization: [Array],

 gru [info] 'user-agent': [Array],

 gru [info] 'content-length': [Array],

 gru [info] 'accept-encoding': [Array],

 gru [info] host: [Array]

 gru [info] },

 gru [info] [Symbol(errored)]: null,

 gru [info] [Symbol(kUniqueHeaders)]: null

 gru [info] },

 gru [info] response: {

 gru [info] status: 404,

 gru [info] statusText: 'Not Found',

 gru [info] headers: AxiosHeaders {

 gru [info] 'x-powered-by': 'Express',

 gru [info] 'access-control-allow-origin': '*',

 gru [info] 'content-security-policy': "default-src 'none'",

 gru [info] 'x-content-type-options': 'nosniff',

 gru [info] 'content-type': 'text/html; charset=utf-8',

 gru [info] date: 'Wed, 12 Jul 2023 16:31:39 GMT',

 gru [info] connection: 'keep-alive',

 gru [info] 'keep-alive': 'timeout=5',

 gru [info] server: 'Fly/e7e2283d (2023-06-28)',

 gru [info] via: '1.1 fly.io',

 gru [info] 'fly-request-id': '01H55F3AMWB6BYS7JDD0MWSX42-gru',

 gru [info] 'transfer-encoding': 'chunked'

 gru [info] },

 gru [info] config: {

 gru [info] transitional: [Object],

 gru [info] adapter: [Array],

 gru [info] transformRequest: [Array],

 gru [info] transformResponse: [Array],

 gru [info] timeout: 0,

 gru [info] xsrfCookieName: 'XSRF-TOKEN',

 gru [info] xsrfHeaderName: 'X-XSRF-TOKEN',

 gru [info] maxContentLength: -1,

 gru [info] maxBodyLength: Infinity,

 gru [info] env: [Object],

 gru [info] validateStatus: [Function: validateStatus],

 gru [info] headers: [AxiosHeaders],

 gru [info] method: 'post',

 gru [info] url: 'https://apiwanodejs.fly.dev/whatsapp/sendmessage',

 gru [info] data: '{"messaging_product":"whatsapp","recipient_type":"individual","to":541156987301,"type":"text","text":{"preview_url":true,"body":"Esto es un test"}}'

 gru [info] },

 gru [info] request: <ref *1> ClientRequest {

 gru [info] _events: [Object: null prototype],

 gru [info] _eventsCount: 7,

 gru [info] _maxListeners: undefined,

 gru [info] outputData: [],

 gru [info] outputSize: 0,

 gru [info] writable: true,

 gru [info] destroyed: true,

 gru [info] _last: true,

 gru [info] chunkedEncoding: false,

 gru [info] shouldKeepAlive: false,

 gru [info] maxRequestsOnConnectionReached: false,

 gru [info] _defaultKeepAlive: true,

 gru [info] useChunkedEncodingByDefault: true,

 gru [info] sendDate: false,

 gru [info] _removedConnection: false,

 gru [info] _removedContLen: false,

 gru [info] _removedTE: false,

 gru [info] strictContentLength: false,

 gru [info] _contentLength: '147',

 gru [info] _hasBody: true,

 gru [info] _trailer: '',

 gru [info] finished: true,

 gru [info] _headerSent: true,

 gru [info] _closed: true,

 gru [info] socket: [TLSSocket],

 gru [info] _header: 'POST /whatsapp/sendmessage HTTP/1.1\r\n' +

 gru [info] 'Accept: application/json, text/plain, */*\r\n' +

 gru [info] 'Content-Type: application/json\r\n' +

 gru [info] 'Authorization: Bearer ***\r\n' +

 gru [info] 'User-Agent: axios/1.4.0\r\n' +

 gru [info] 'Content-Length: 147\r\n' +

 gru [info] 'Accept-Encoding: gzip, compress, deflate, br\r\n' +

 gru [info] 'Host: apiwanodejs.fly.dev\r\n' +

 gru [info] 'Connection: close\r\n' +

 gru [info] '\r\n',

 gru [info] _keepAliveTimeout: 0,

 gru [info] _onPendingData: [Function: nop],

 gru [info] agent: [Agent],

 gru [info] socketPath: undefined,

 gru [info] method: 'POST',

 gru [info] maxHeaderSize: undefined,

 gru [info] insecureHTTPParser: undefined,

 gru [info] path: '/whatsapp/sendmessage',

 gru [info] _ended: true,

 gru [info] res: [IncomingMessage],

 gru [info] aborted: false,

 gru [info] timeoutCb: null,

 gru [info] upgradeOrConnect: false,

 gru [info] parser: null,

 gru [info] maxHeadersCount: null,

 gru [info] reusedSocket: false,

 gru [info] host: 'apiwanodejs.fly.dev',

 gru [info] protocol: 'https:',

 gru [info] _redirectable: [Writable],

 gru [info] [Symbol(kCapture)]: false,

 gru [info] [Symbol(kBytesWritten)]: 0,

 gru [info] [Symbol(kEndCalled)]: true,

 gru [info] [Symbol(kNeedDrain)]: false,

 gru [info] [Symbol(corked)]: 0,

 gru [info] [Symbol(kOutHeaders)]: [Object: null prototype],

 gru [info] [Symbol(errored)]: null,

 gru [info] [Symbol(kUniqueHeaders)]: null

 gru [info] },

 gru [info] data: '<!DOCTYPE html>\n' +

 gru [info] '<html lang="en">\n' +

 gru [info] '<head>\n' +

 gru [info] '<meta charset="utf-8">\n' +

 gru [info] '<title>Error</title>\n' +

 gru [info] '</head>\n' +

 gru [info] '<body>\n' +

 gru [info] '<pre>Cannot POST /whatsapp/sendmessage</pre>\n' +

 gru [info] '</body>\n' +

 gru [info] '</html>\n'

 gru [info] }

 gru [info] }

 gru [info] Send: {"messaging_product":"whatsapp","recipient_type":"individual","to":541156987301,"type":"text","text":{"preview_url":true,"body":"Esto es un test"}}

 gru [info] undefined

 gru [info] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

 gru [info] at new NodeError (node:internal/errors:400:5)

 gru [info] at ServerResponse.setHeader (node:_http_outgoing:663:11)

 gru [info] at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)

 gru [info] at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)

 gru [info] at /app/src/routes/routes.js:22:13

 gru [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

 gru [info] code: 'ERR_HTTP_HEADERS_SENT'

 gru [info] }

 gru [info] node:internal/errors:491

 gru [info] ErrorCaptureStackTrace(err);

 gru [info] ^

 gru [info] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

 gru [info] at new NodeError (node:internal/errors:400:5)

 gru [info] at ServerResponse.setHeader (node:_http_outgoing:663:11)

 gru [info] at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)

 gru [info] at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)

 gru [info] at /app/src/routes/routes.js:26:25

 gru [info] at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

 gru [info] code: 'ERR_HTTP_HEADERS_SENT'

 gru [info] }

**Comment by TomasS-R** [comment]
Cambie en la configuracion de las rutas lo siguiente:

```
.post(`/api/sendmessage`, (req, res) => {
    const datos = whatsappController.send(req, res)
    .then((datos) => {
        console.log(datos);
        res.send('Solicitud POST recibida: '+ datos);
    })
    .catch (e => {
        console.log(e);
        res.status(500).send('Error en la solicitud POST');
    });
});
```
y en las funciones lo modifique asi, ya que creia que habia infromacion para hacer el post que no era tan relevante

```
async function sendTextFront(textResponse, number){ 

    const data = JSON.stringify({
        "messaging_product": "whatsapp",    
        "recipient_type": "individual",
        "to": number,
        "type": "text",
        "text": {
            "preview_url": true,
            "body": textResponse
        }
    })
    whatsappService.SendMessageWhatsApp(data);
    await makeRequest(data);
    return Promise.resolve(data);
};

async function makeRequest(data) {
    let config = {
        method: 'post',
        maxBodyLength: Infinity,
        url: 'https://apiwanodejs.fly.dev/whatsapp/sendmessage',
        headers: { 
          'Content-Type': 'application/json', 
          'Authorization': `Bearer ${configENV.TOKEN}`
        },
        data : data
      };
    try {
        const response = await axios.request(config);
        console.log(JSON.stringify(response.data));
    }
    catch (error) {
        console.log(error);
    }
}
```

En el archivo controllers agregue una funcion
```
async function send (req, res) {
    try {
        const sendMessage = await waFront.sendTextFront("Esto es un test",54115689562);
        console.log("Send: " + sendMessage);
        res.status(200).json({
            success: true,
            data: sendMessage,
        });
    } catch (e) {
        res.status(500).json({
            success: false,
            error: error.sendMessage,
        });
        console.log(e);
    }
};
```

El error que mostre arriba es con este codigo, ya que con el otro codigo, no me mostraba ningun error y por eso lo tuve que modificar, el numero de telefono tambien esta modificado para este ejemplo

**Comment by TomasS-R** [comment]
Segun entiendo por la siguiente linea:
`gru [info] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`
No se puede colocar los headers despues de haber sido enviados al cliente

Y lo que busque me dio a entender que estoy mandando mas de 1 ves response al servidor

Por lo tanto comente esta linea el la parte de las rutas:
`res.send('Solicitud POST recibida: '+ datos);`
Ahora cuando envio la peticion por postman me llega al whatsapp, pero no me aparece en el navegador ninguna informacion

**Comment by TomasS-R** [comment]
No se por que me toma como que estoy queriendo hacer un metodo get cuando le estoy aclarando que es un post:

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/55171526/a77c54ee-8b55-4567-9189-eb3f9920be94)

**Comment by vinixcode** [comment]
@TomasS-R pues al menos en primera instancia podemos ver que el servidor está respondiendo con 404 lo cual indica claramente que estás intentando acceder a una ruta que el backend no reconoce y no existe.

Verifica en el frontend que estés estructurando bien la petición ya que si quieres que sea POST en vez de GET, entonces en el código debe haber algún lugar en el que no se esté especificando correctamente esto.

Mira dónde puede ser el error, y sino te pido que por favor grabes un corto video de tu pantalla, mostrando el código y reproduciendo el error.

Gracias

**Comment by TomasS-R** [comment]
Por el momento voy a cerrar el problema, estoy buscando una solución, en cuanto la encuentre lo subo, desde ya agradezco su ayuda!.

**Comment by TomasS-R** [comment]
Por el momento voy a cerrar el problema, estoy buscando una solución, en cuanto la encuentre lo subo, desde ya agradezco su ayuda!.

**Comment by TomasS-R** [comment]
Al final lo resolvi, fue un error mio al pensar que debia ver la solicitud post en el front, ya que tengo entendido que las que se muestran en el front son solo las solicitudes get, asi que lo puede solucionar sin mas problema

**Comment by vinixcode** [comment]
Excelente.
