### ISSUE TITLE
Dos lineas dentro del mismo business manager

### ISSUE THREAD

**Issue by jucagolo64** [Vinix-Code-Dev/curso-api-whatsapp-frontend#76]
Hola.

Tengo un inconveniente con un proyecto el cual requiere manejar dos lineas por la misma empresa.

Tengo dos apps en facebook diferentes y tengo asociada las dos lineas a la misma cuenta de negocio en facebook (Business manager), lo que sucede es que cuando le asigno el webhook, este recibe la información de las dos lineas así tenga dos apps diferentes en la misma empresa y necesito separar lo que llega por cada linea de forma independiente.

¿Qué configuración debo hacer para que el webhook sólo me mande información por línea?

Muchas gracias

**Comment by vinixcode** [comment]
Hola @jucagolo64 

Es posible solucionarlo de 2 maneras:

1. Es posible que tu sobreescribas la URL en la cual quieres recibir los webhooks para una cuenta de WhatsApp determinada. Aquí puedes ver cómo hacerlo: https://developers.facebook.com/docs/whatsapp/embedded-signup/webhooks/#overriding-the-callback-url
2. En el webhook viene el ID del teléfono específico que recibió el mensaje. Puedes usar esto para determinar a qué línea están llegando los mensajes y almacenarlo en la base de datos.

Avísanos cómo te va implementando alguna de estas soluciones! Gracias

**Comment by jucagolo64** [comment]
Hola @vinixcode muchas gracias.

Procederé a implementarlo y obviamente te comentaré cómo me va.

Saludos

**Comment by jucagolo64** [comment]
@vinixcode Ya lo pude implementar con lo que me enviaste, lo que hice en este caso fue del número de teléfono WABAID, desuscribir las apps y asi me funcionó perfectamente, Gracias por tu ayuda.

Me quedo una pequeña duda con el sobrescribir la url del webhook, ¿este sirve más que todo en el caso que yo quiera enviar a dos webhooks diferentes los mensajes que llegan a la misma línea?

**Comment by vinixcode** [comment]
Sí. Lo que pasa es que si tu tienes varias líneas dentro de un mismo WABA, se va a usar el mismo webhook para todas. Es decir que al mismo webhook va a llegar todos los mensajes de todas las líneas.

Entonces de esta manera puedes separar las URLs de los webhooks, para solo recibir información de una línea específica.

Me alegra que hayas solucionado el problema - procederé a cerrar este ticket!

**Comment by jucagolo64** [comment]
Muchas gracias @vinixcode 

Saludos
