### ISSUE TITLE
Despliegue AWS

### ISSUE THREAD

**Issue by SebasMoreno145** [Vinix-Code-Dev/curso-api-whatsapp-frontend#77]
Hola Juan, hace unos días te pregunte sobre la información para desplegar el proyecto, ya que había cambiado un poco la configuración, quería validar si esta información ya fue actualizada, para subir mi proyecto, gracias!.

**Comment by vinixcode** [comment]
Hola @SebasMoreno145 

No he revisado las actualizaciones de l guía AWS, pero me apuntaré dicha tarea para esta semana. Dejaré este ticket abierto y te mantendré informado.

**Comment by vinixcode** [comment]
@SebasMoreno145 he estado revisando el video, y definitivamente un cambio que había que hacer es que ya no se debe usar PHP 7.4 sino PHP 8.1 al momento de crear el ambiente. 

Esto ya quedó aclarado al comienzo del video, **y subí una nueva actualización en el minuto 1:09.**

No noté ningún otro cambio significativo entre el video y AWS. Podrías por favor avisarme si hay algún otro lugar en el que encuentres dudas?

Te lo agradezco de antemano.

**Comment by vinixcode** [comment]
Cerraré este ticket, pero reábrelo si tienes más comentarios.
