### ISSUE TITLE
Clase 15 obtener id del mensaje enviado hacia el usuario

### ISSUE THREAD

**Issue by TomasS-R** [Vinix-Code-Dev/curso-api-whatsapp-frontend#78]
Estoy con un problema sobre como obtengo el id del mensaje siendo que cuando lo envio solo recibo la respuesta json que solicite:

```
{
        "messaging_product": "whatsapp",    
        "recipient_type": "individual",
        "to": "*********",
        "type": "text",
        "text": {
            "preview_url": true,
            "body": "texto de prueba"
}
```

Asi es como tengo la funcion:

```
function sendTextFront(textResponse, number){

    const data = JSON.stringify({
        "messaging_product": "whatsapp",    
        "recipient_type": "individual",
        "to": number,
        "type": "text",
        "text": {
            "preview_url": true,
            "body": textResponse
        }
    });
    console.log(data);
    sendWhatsAppMessage(data);
    return data;
};
```

En el console log me muestra el mensaje enviado mediante la consola, y si envio otro mensaje recien ahí me muestra el id del mensaje

```
{"messaging_product":"whatsapp",
"recipient_type":"individual",
"to":"5411********",
"type":"text",
"text":{"preview_url":true,"body":"texto de prueba"}}
```

Cuando envió otro mensaje me muestra el id del mensaje del anterior envio y la informacion del nuevo mensaje:

```
{"messaging_product":"whatsapp",
"contacts":[{
"input":"5411********",
"wa_id":"54911********"}],
"messages":[{"id":"wamid.HBgNNTQ5MTE1NjkwMzQ1ORUCABEYEkRDQjk2RDgxN0EyRjM5NTFFNwA="}]}
{"messaging_product":"whatsapp",
"recipient_type":"individual",
"to":"5411********",
"type":"text",
"text":{"preview_url":true,"body":"texto de prueba2"}}
```

Como podría hacer para obtener el id del mensaje al mismo tiempo que lo envió? porque al recibirlo del usuario no hay problema, pero al yo enviarlo no entiendo como lo capturo ya que lo unico que puedo guardar seria la data que estoy enviando.

**Comment by TomasS-R** [comment]
Ya logre solucionarlo al modificar la función que manejaba la configuración de envío de los mensajes!

**Comment by vinixcode** [comment]
Que capo @TomasS-R excelente!
