### ISSUE TITLE
Solicitud verificación APP Meta

### ISSUE THREAD

**Issue by jucagolo64** [Vinix-Code-Dev/curso-api-whatsapp-frontend#79]
Hola @vinixcode 

He creado una app en META (Developers) para hace un bot básico acorde al curso, seguí los pasos que indican en los videos  y me ha llegado esta notificación

![image (53)](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/d91904cd-0cf5-470d-91c3-ec77e891e8d2)

La verdad no me quedaba muy claro el proceso  qué es lo que requeiren, me piden respuesta explicando para qué estoy usando la app para que no la bloqueen, pero solicitan que les de las credenciales de la app para acceder

![image (54)](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/f2f4a128-d331-4544-b850-eb31f36b8457)

¿Podrías indicarme qué hacer?,  ¿debo darles las credenciales de qué exactamente, o cómo es el proceso?, ¿qué envían otros usuarios que usan Wasapi cuando facebook solicita esta información?, pues he visto todos tus videos y la verdad no he encontrado alguno que hable sobre el tema

Muchas gracias

**Comment by vinixcode** [comment]
Hola @jucagolo64 

Según lo que enviaron, me da la impresión de que al momento de crear la app dejaste algo mal configurado.

Por favor podrías revisar este corto video que te grabé? https://www.awesomescreenshot.com/video/19350553?key=8c4314fd884d1167438f94f882fa2500

Revísalo y estaré atento a tus comentarios.

Gracias

**Comment by jucagolo64** [comment]
Hola @vinixcode 

Muchas gracias, estuve revisando por donde me dices y en realidad no estaba agregado el "Inicio de sesión con Facebook", procedí a instalarlo para ver encontraba algo y me aparece lo siguiente:

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/470a3a94-8ee7-46ae-9ae7-f4f686791e16)

Consulto los permisos y aquí lo encuentro, pero no me deja eliminarlo o hacer algo con este

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/c64877dd-4a0b-40f0-ba35-bcf231f7f12d)

Como puedes ver ahí en el mensaje "Desactivamos esta app por infringir las Normas de la plataforma de Facebook", esta esta deshabilitada.

La verdad no recuerdo haberlo habilitado en algún momento, solo utilizo facebook developers para mis ejercicios del curso, ¿Qué crees que podría hacer, eliminarlo?  ¿cómo podría proceder para habilitarla de nuevo ?  


Te mando imágenes de lo que tengo al momento en "Inicio de sesión en Facebbok"

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/4f7952a9-1b0f-46af-beac-290363fe0fa0)
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/755e703a-7ecc-46cb-b4de-ff5dc590dfe9)
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/5cb32940-18e0-4aef-a50d-1300e7788738)



![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/ae401b04-4d98-4831-ac5b-0012c157d418)

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/139480057/2acd01e4-143e-4a22-89a3-bc2aa4e632a1)

Muchas gracias por tu ayuda

**Comment by vinixcode** [comment]
Al parecer tu aplicación o cuenta fue bloqueada. Te recomiendo que apeles a FB usando el enlace que te dan, o simplemente abre una nueva cuenta en FB y crea una aplicación.

Aquí puedes ver un video de cómo lo hago: https://vimeo.com/838236477?share=copy

**Comment by vinixcode** [comment]
Cerraré este ticket, pero reábrelo si sigues experimentando el problema.
