### ISSUE TITLE
Varios webhook para una misma app Facbook

### ISSUE THREAD

**Issue by jucagolo64** [Vinix-Code-Dev/curso-api-whatsapp-frontend#82]
Hola.

Quisiera saber si hay alguna forma en que pueda configurar dos o más webhooks en facebook para la misma app?

Esto con el fin de replicar una información de varios puntos.

Muchas gracias

**Comment by vinixcode** [comment]
Hola @jucagolo64 

No es posible, pero tu puedes crear una ruta en tu aplicación, que reciba la petición del webhook y se encargue de redirigirla a los endpoints que quieras.

Espero haber resuelto tu duda, sino puedes reabrir el ticket.

**Comment by jucagolo64** [comment]
Perfecto muchas gracias.
