### ISSUE TITLE
No graba en tabla las autorespuestas de sendtext del processChatbotMessages

### ISSUE THREAD

**Issue by leomontano** [Vinix-Code-Dev/curso-api-whatsapp-frontend#83]
Todo ha ido bien, todo ha funcionado pero observo lo siguiente:

En la función de: processChatbotMessages del Controlador MessageController, concretamente cuando se hacen las auto respuestas  con el sendtext no se me graba en la tabla: messages la respuestas

Nota: Las auto respuestas si funcionan, todos los mensajes trabajan

código:

public function processChatbotMessages($text, $waId){
    // En text se recibe la palabra escrita en el chat y que se interpreta para procesar la respuesta automática
    $text = strtolower($text);
    $mensaje='Hola, soy tu bot. Estoy para ayudarte, selecciona una opción';
    $grabar=false;
    $wp = new WhatsApp();
    $waId=$wp->quita($waId);
    $respuesta=null;

    // busca el último mensaje

//    $message=Message::where('outgoing',false)->where('wa_id',$waId)->orderByDesc('id')->first();

//    if(!empty($message) && strtolower($message->body)=='hola'){
        if($text=='menu'){
            // Un botón debe tener máximo 20 caracteres
            // Máximo 3 botones
            $buttons = ['Formulario', 'cafes', 'Ubicación'];
            $respuesta = $wp->sendButton($waId, $mensaje, $buttons);
        }elseif($text=='lista'){
            // Un botón debe tener máximo 20 caracteres
            $respuesta = $wp->sendButtonList($waId, $mensaje);
        }elseif($text=='cafes'){
            $url='https://api.sampleapis.com/coffee/hot';
            $response= Http::get($url)->throw()->json();
            $body='';
            foreach ($response as $item) {
                $body.=$item['title'].', ';                  
            }
            $respuesta = $wp->sendText($waId,$body);
        }else{
            $respuesta = $wp->sendText($waId,'No entiendo la respuesta');        
        } 
/*    }else{
        $respuesta = $wp->sendText($waId,'¿En que te puedo ayudar?'); 
    }
*/
    return $respuesta;
}

Código:

	public function sendText($to,$text){
		$payload=[
	      "messaging_product" => "whatsapp",
	      "recipient_type"=> "individual",
	      "to"=> $to,
	      "type"=> "text",
	      "text"=> [ 
	        "preview_url"=> false,
	        "body"=> $text
	        ]
	   ];
	    $url=$this->baseUrl.$this->version.'/'.$this->phoneID.'/messages';
        return Http::withToken($this->accessToken)->
        post($url,$payload)->
        throw()->
        json();
	}

**Comment by vinixcode** [comment]
Hola @leomontano 

No entiendo bien el problema. Según lo que entiendo y veo en el código, no hay ninguna función que esté almacenando el código en la base de datos. Debes verificar esa parte.

¿Podrías de pronto enviarme un pantallazo o un video corto reproduciendo el error?

Recuerda también que el código del curso está dentro del área de miembros, y ahí puedes revisar para confirmar qué te puede estar haciendo falta.

**Comment by leomontano** [comment]
Ok, Muchas Gracias. Efectivamente, no lo estaba grabando. ¡ Solucionado !

**Comment by vinixcode** [comment]
Excelente! Cerrando ticket.
