### ISSUE TITLE
Problemas con respuestas intercatvias.

### ISSUE THREAD

**Issue by SebasMoreno145** [Vinix-Code-Dev/curso-api-whatsapp-frontend#84]
Hola Juan, siguiendo con la construcción de mi Bot me he encontrado el siguiente problema. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/1eb7790a-351f-47cc-b026-a8d439456bef)

Si escribo el contenido del botón, el flujo funciona sin problemas, pero respondiendo desde el botón, me envía este error.

**Comment by vinixcode** [comment]
@SebasMoreno145 

Ocurre porque estás accediendo a un campo que no existe dentro de un array. Puedes verificar que el atributo si exista en el array antes de acceder a él.

En vez de hacer por ejemplo $data['button_reply'] primero verificas si existe:

`if (!empty($data['button_reply']))`

o

`if (isset($data['button_reply']))`

**Comment by SebasMoreno145** [comment]
Hola Juan, te comparto la linea de código en donde estoy encontrando el error. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/88a2fad6-4987-4995-a259-b4abdf7dbbfc)

Este es el mensaje que le estoy enviando. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/53a8d54b-f8f5-42c1-bc33-092f725e746e)

Comprendo que estoy buscando un atributo que no existe, que seria button_reply. Por estar enviando en la petición list_reply

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/6b099e48-cbed-4264-b219-252d4a3421e1)

Asi que he cambiado ese parámetro para consultar el que se esta enviando. 

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/66187015-600f-49a9-88c4-20ff6af0f5fb)

Pero obtengo un error, al acceder a ese valor

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/38218454/0c331417-5735-41e2-8b7f-1e3fcb89a15c)


¿Podrías explicarme como puedo mantener la validación para los botones? Y además integrar correctamente el de listas. Muchas gracias.

**Comment by vinixcode** [comment]
@SebasMoreno145 alcanzo a ver un par de cosas:

1. Estás accediendo a $value['messages'][0]['interactive']['list_reply']['title']['title'] pero deberia ser a $value['messages'][0]['interactive']['list_reply']['title']['title'] sin el ['title'] adicional que tienes al final, pues no existe.
2. Puedes verificar siempre si es un mensaje tipo lista o boton, utilizando la funcion isset (https://www.php.net/manual/en/function.isset.php)

Por ejemplo:

```
if (isset($value['messages'][0]['interactive']['list_reply'])) {
// Código para mensaje lista
} elseif (isset($value['messages'][0]['interactive']['button_reply']))
// Código para botón
}
```

Espero que esto resuelva tu problema, sino avísame.

**Comment by vinixcode** [comment]
Cerraré este ticket, pero reábrelo si sigues experimentando el problema.
