### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by jjaimes** [Vinix-Code-Dev/curso-api-whatsapp-frontend#85]
Hola Vinix

Estoy en un punto del curso en que:

1) Me gustaría usar el debug, pero no logro activarlo. ¿Sirve cualquier video de Xdebug con Laravel en youtube para poderlo instalar?

2) Estoy llevando a cabo el procedimiento de usar la URL http://localhost:8000/api/messages en Postman. Sin embargo, a pesar de estar llegando los mensajes, estoy viendo en el ngrok que el resultado del POST es un espantoso 500 (imagen adjunta). Por este, motivo, me gustaría ver qué está pasando a nivel de Debug.

Cualquier otra recomendación, bienvenida sea!

![Err_500](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/15263362/b3f372a1-127c-4305-97e2-ca0661a4d9fb)

**Comment by vinixcode** [comment]
Hola @jjaimes disculpa la demora para responderte. Estaba de viaje y estoy poniéndome al día con todos mis mensajes.

Sí te recomiendo al 100% instalar xDebug. Es una herramienta que yo personalmente uso cada vez que estoy desarrollando, y hará tu vida más fácil.

En teoría cualquier video te debería servir, ya que xDebug funciona a nivel de PHP y no a nivel de Laravel. Solo asegúrate de que el video te explique como hacerlo con la versión de PHP que estás usando.

Si no logras hacerlo, avísame que versiones usas y trataré de grabar un video explicando cómo hacerlo.

De nuevo disculpa la demora! Estaré atento a tus comentarios.
