### ISSUE TITLE
Problemas de envio de Imagenes y Audio

### ISSUE THREAD

**Issue by BigtronicaSAS** [Vinix-Code-Dev/curso-api-whatsapp-frontend#86]
Dios te bendiga juan!! jeje he retomado el curso. Tengo el siguiente problema. Las imagenes no se cargan en el frontend. 

Asi se ve en mi backend 
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/adf98661-bab9-4244-9ba6-af5d6ee3b215)
y el laravel.log me dice lo siguiente
[2023-09-11 21:27:31] local.ERROR: Error sending message: HTTP request returned status code 400:
{"error":{"message":"(#100) Invalid parameter","type":"OAuthException","code":100,"error_data":{"messaging_product":"wha (truncated...)
  
[2023-09-11 21:28:10] local.ERROR: Error sending message: HTTP request returned status code 400:
{"error":{"message":"(#100) Invalid parameter","type":"OAuthException","code":100,"error_data":{"messaging_product":"wha (truncated...)
  
[2023-09-11 21:28:22] local.ERROR: Error sending message: HTTP request returned status code 400:
{"error":{"message":"(#100) Invalid parameter","type":"OAuthException","code":100,"error_data":{"messaging_product":"wha (truncated...) quedaria muy agradecido si puedes ayudar, gracias!!! Dios te bendiga

**Comment by BigtronicaSAS** [comment]
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/26a382fd-9309-4325-8f47-3f7566844a4a)

**Comment by vinixcode** [comment]
Amen @BigtronicaSAS bienvenido de vuelta!

Veo que la imagen no se está guardando. Verifica que estés haciendo la petición correctamente porque los errores en el laravel.log muestran que al hacer la petición a Meta para descargar la imagen, no se está haciendo bien. 

Recuerda que el código del curso también está en el area de miembros de forma gratuita, y lo puedes revisar y comparar.

Te agregaré al grupo de Telegram también.

Saludos!

**Comment by BigtronicaSAS** [comment]
Juan, es que de hecho tome el codigo del curso lo descargue, y solamente lo  puse a correr ayer.. Pero nada no encuentro el error.

**Comment by vinixcode** [comment]
Podés por favor hacer un video grabando la pantalla y mostrando el código y cómo lo estás reproduciendo?

**Comment by BigtronicaSAS** [comment]
https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/091f16d5-3a0c-473f-91c6-2a382a325dc7

**Comment by BigtronicaSAS** [comment]
Noto que es muy lento, me imagino que en produccion es mas rapido jajaj. Por que si envio un mensaje y se demora.

**Comment by BigtronicaSAS** [comment]
[2023-09-12 16:21:04] local.ERROR: SQLSTATE[HY000] [2002] No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.
 {"exception":"[object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.

 at C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php:70)
[stacktrace]
#0 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(70): PDO->__construct('mysql:host=127....', 'root', '', Array)
#1 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'root', '', Array)
#2 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)
#3 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connectors\\ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(1064): call_user_func(Object(Closure))
#6 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(139): Illuminate\\Database\\Connection->getPdo()
#7 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(115): Illuminate\\Database\\Connection->createTransaction()
#8 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(23): Illuminate\\Database\\Connection->beginTransaction()
#9 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\DatabaseQueue.php(223): Illuminate\\Database\\Connection->transaction(Object(Closure))
#10 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(345): Illuminate\\Queue\\DatabaseQueue->pop('default')
#11 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(354): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}('default')
#12 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Worker.php(159): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\DatabaseQueue), 'default')
#13 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon('database', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#14 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Queue\\Console\\WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'default')
#15 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#16 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#18 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(653): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#21 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\symfony\\console\\Command\\Command.php(298): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\symfony\\console\\Application.php(1040): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\symfony\\console\\Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\symfony\\console\\Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(94): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 C:\\Users\\revision\\Desktop\\chatbot\\server\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 C:\\Users\\revision\\Desktop\\chatbot\\server\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 {main}
"} 
algo que acabo de anotar es la hora que aparece esto como lo puedo configurar? gracias

**Comment by BigtronicaSAS** [comment]
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/b239d850-67b8-4ee1-b0dc-8d3945eed97b)
Mira que aqui si me esta enviando correctamente la imagen

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/f2426c8a-3634-453a-80dc-cd921735fc45)
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/31a5dd6e-5931-4251-bbab-7a024c6bb886)

**Comment by vinixcode** [comment]
@BigtronicaSAS Camilo, parece ser problema al descargar la imagen.

Podrías por favor seguir los pasos de este video y verificar que puedas descargar cualquiera de las imágenes que recibes?

https://www.youtube.com/watch?v=ORMXygP5fxI

Si logras hacerlo, escríbeme por aquí o el grupo de Telegram para determinar siguientes pasos.

**Comment by BigtronicaSAS** [comment]
Juan Dios te bendiga, si claro los pasos del videos estan bien, a mi llega la imagen y de hecho se me guardan en el storage pero a la hora de verlo en el frontend ahi esta el problema. Por que la imagen si se descarga, pero al enviarlo al frontend  llega con la url y la imagen el audio y el video,  pero no carga. Gracias por tu respuesta.
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/107426353/ba721a92-2150-4d2c-a492-2ad37029ea67)

**Comment by vinixcode** [comment]
El problema se resolvió por telegram.

Los archivos no cargaban porque faltó ejecutar el comando `php artisan storage:link`

Cerrando ticket
