### ISSUE TITLE
No puedo ingresar a la Plataforma del curso

### ISSUE THREAD

**Issue by usyeimar** [Vinix-Code-Dev/curso-api-whatsapp-frontend#88]
Hola Juan Esteban, tengo inconvenientes para acceder al curso.

cambiaron algo?
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/71295346/14adcd3d-6f08-4f00-b65b-93667eeb4ab6)

**Comment by vinixcode** [comment]
Hola @usyeimar 

Hace un par de semanas movimos nuestra plataforma educativa a https://academia.wasapi.io/

Allí podras ingresar al curso.

Si no logras acceder con tu correo (el mismo que tenías cuando hiciste la compra), intenta resetear la contraseña o escríbenos a info@vinixcode.com con el recibo de pago y te ayudamos.

Disculpa el inconveniente!
