### ISSUE TITLE
Duda clase 5

### ISSUE THREAD

**Issue by luisfernando2022** [Vinix-Code-Dev/curso-api-whatsapp-frontend#9]
Que tal, ya tengo todo instalado: xampp, mysql, laravel, composer, solo que la configuración que hace en la siguiente pantalla:
![image](https://user-images.githubusercontent.com/119472003/204703977-9ef1dab2-f677-4442-89af-bd4d1e4eed1e.png)

Ese archivo vim.env no logro identificarlo, no sé donde se encuentra. ¿Alguien podría darme información?

**Comment by RAGUDIG** [comment]
> Que tal, ya tengo todo instalado: xampp, mysql, laravel, composer, solo que la configuración que hace en la siguiente pantalla: ![image](https://user-images.githubusercontent.com/119472003/204703977-9ef1dab2-f677-4442-89af-bd4d1e4eed1e.png)
> 
> Ese archivo vim.env no logro identificarlo, no sé donde se encuentra. ¿Alguien podría darme información?

Si no manejas la consola, hazlo desde el Visual studio code, ahi edita ese archivo.

**Comment by luisfernando2022** [comment]
Gracias amigo, pero mi duda es esa, ¿**dónde** esta ese archivo? Según entiendo, es un archivo que permite conectar la base de datos con Laravel, ¿es correcto?

**Comment by luisfernando2022** [comment]
Ya entendí lo que se tiene que hacer, se trata de buscar el archivo .env de la carpeta creada para el proyecto de Laravel y abrirlo con un editor de código como VSC o incluso el bloc de notas. Gracias.

**Comment by vinixcode** [comment]
Es exactamente lo que acabas de decir Luis! Es un archivo en el que Laravel guarda la configuración de la aplicación. Aquí puedes ver la documentación en detalle de cómo funciona todo: https://laravel.com/docs/8.x/configuration
