### ISSUE TITLE
Error Respuesta Mensajes

### ISSUE THREAD

**Issue by valvena** [Vinix-Code-Dev/curso-api-whatsapp-frontend#90]
Saludos, estoy en el video "Enviar Mensajes desde el Chat", pero tengo un error

En la visual si me carga los mensajes recibidos, pero para responder, solo me deja con un número que es el que escribi en:

 public function sendMessages()
    {
        try {

            $wp = new Whatsapp(); 
            $message = $wp->sendText('5735068xxxxx', 'Is this working?');

                return response()->json([
                'success'=> true,
                'data'=> $message,
                ],200);
        }
        catch (Exception $e) {
            return response()->json([
            'success'=> false,
            'error'=> $e->getMessage(),
            ],500);
        }
    }

revise el video varias veces, pensando que olvide quitar o poner algo pero tengo el codigo okay

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/317479/51e3f24f-7a80-48d5-8735-3acbdf23501e)

Alguien me podria ayudar...

**Comment by vinixcode** [comment]
@valvena podrías explicarme en más detalle por favor cuál es el problema?

A qué te refieres con que solo te deja responder con el que número que escribiste?

**Comment by vinixcode** [comment]
Cerrando ticket por inactividad.
