### ISSUE TITLE
Problema con carga de mensaje en el index URGENTE

### ISSUE THREAD

**Issue by Santiagovaron1318** [Vinix-Code-Dev/curso-api-whatsapp-frontend#91]
Hola, tengo el siguiente problema: mi codigo frontend no funciona correctamente y he intentando de todo para solucionarlo, pero no queda mas que recurrir a ayuda. Mi codigo: `<template>
  <v-row>
    
    <v-col sm="3">
      <v-card elevation="7" class="chat-list">
        <v-list class="py-0" two-line>
          <v-list-item-group v-model="selected" active-class="green--text">
            <template v-for="(item, index) in items">
              <v-list-item :key="item.wa_id">
                <template>
                  <v-list-item-content>
                    <v-list-item-title v-text="item.wa_id"></v-list-item-title>

                    <v-list-item-subtitle
                      v-text="item.body"
                    ></v-list-item-subtitle>
                  </v-list-item-content>
                </template>
              </v-list-item>

              <v-divider
                v-if="index < items.length - 1"
                :key="index"
              ></v-divider>
            </template>
          </v-list-item-group>
        </v-list>
      </v-card>
    </v-col>

    
    <v-col md="9">
      <v-card elevation="7">
        <v-card class="chat-box wpp-bg" color="#efeae2">
          <v-card class="pa-2" color="#424242" dark>Ali Connors</v-card>
          <div
            v-for="(message, index) in messages"
            :key="index"
            :class="[
              'pa-1',
              'd-flex',
              { 'justify-start': !message.outgoing },
              { 'justify-end': message.outgoing },
            ]"
          >
            <v-card
              class="pa-2 ma-2 message-card"
              :color="message.outgoing ? 'green accent-1' : 'white'"
            >
              <div>
                <div>{{ message.body }}</div>
                <p class="text-right text-subtitle-2 font-italic">
                  {{ message.created_at }}
                  
                </p>
              </div>
            </v-card>
          </div>
        </v-card>
        <v-divider></v-divider>
        <div class="pa-3">
          <v-text-field
            v-model="message"
            dense
            outlined
            background-color="white"
            :append-outer-icon="'mdi-send'"
            filled
            clear-icon="mdi-close-circle"
            clearable
            label="Type a message..."
            type="text"
            class="message-box"
            @click:append-outer="sendMessage"
            @keydown.enter.exact.prevent="sendMessage"
          ></v-text-field>
        </div>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
export default {
  data: () => ({
    selected: [2],
    items: [
      {
        body:
          'Hola',
        wa_id: 'Ali Connors',
      },
      {
        body:
          'Hola',
        wa_id: 'Jennifer',
      },
    ],
    messages: [
      {
        outgoing: false,
        body: 'hola hola ',
        created_at: '05/02/22',
        status: 'sent',
      },
      {
        outgoing: true,
        body: 'todo bien',
        created_at: '05/02/22',
        status: 'read',
      },
    ],
    message: '',
    
  }),
  created() {
    this.loadMessage()
  },
  methods: {
    loadMessage() {
    try {
      this.$axios.get('http://localhost:8000/api/messages')
        .then(({ data }) => {
          console.log('Todo salio en orden', data)
          this.items=  data.data

          
        })
        .catch(error => {
          console.error('Error loading messages:', error);
        });
    } catch (error) {
      console.error('An unexpected error occurred:', error);
    }
  },
  sendMessage() {
      this.messages.push({
        outgoing: true,
        body: this.message,
        created_at: this.$moment().format('L'),
        status:'sent',
      })
      this.message=''
    },
    formatReadStatus(status) {
      const statuses = {
        read: {
          color: 'blue',
          icon: 'mdi-check-all',
          tooltip: 'Read',
        },
        delivered: {
          color: 'grey',
          icon: 'mdi-check-all',
          tooltip: 'Delivered',
        },
        sent: {
          color: 'grey',
          icon: 'mdi-check',
          tooltip: 'Sent',
        },
        failed: {
          color: 'red',
          icon: 'mdi-alert-circle',
          tooltip: 'Failed',
        },
      }

      if (statuses?.[status]) {
        return statuses[status]
      } else {
        return {
          color: 'grey',
          icon: 'mdi-cards-diamond-outline',
          tooltip: '',
        }
      }
    },
  },
}
</script>

<style>
.message-box .v-text-field__details {
  display: none;
}
.chat-box {
  height: 80vh;
  overflow-y: scroll;
}
.message-card {
  max-width: 60%;
}
.chat-list {
  height: 85vh;
}
.wpp-bg {
  background-image: url('/bg-whatsapp.png');
  background-repeat: repeat;
  border-color: #efeae2;
}
.img-msg {
  max-width: 300px;
}
</style>` 
 En la consola funciona correctamente, y la conexion con la API no tiene problema. Sin embargo en el momento de mostrar el wa_id en pantalla, no se muestra, y eso que con el try se agrega un console.log diciendo que todo salio bien, y aunque se muestra en consola, junto con la data, el problema es que no se cargan en la pagina y literalmente se queda en blanco. Espero haber sido claro, espero pronta comunicación. Exitos

**Comment by vinixcode** [comment]
@Santiagovaron1318 Buenos dias.

La verdad es un poco dificil diagnosticar el problema de esta manera. Podrias por favor grabar un video compartiendo tu pantalla, mostrando el codigo y reproduciendo el error?

Tambien si puedes hacer un gist (https://gist.github.com/) y compartir el codigo del archivo especifico, seria muy util.

Estare atento, gracias.

**Comment by Santiagovaron1318** [comment]
Vale, muchas gracias, tan pronto pueda subiré el vídeo.

**Comment by Santiagovaron1318** [comment]
https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/93489176/0a51ff5e-4c34-4654-91c8-4f04c77b200d

Aqui esta el video de mi codigo. Como puedes ver los datos realmente llegan, la conexión con la API es correcta. Sin embargo los datos no se actualizan, en la pagína. Espero pronta respuesta, muchas gracias.

**Comment by Santiagovaron1318** [comment]
@vinixcode 
Tambien me gustaria comentar un problema que tuve hace poco y no lo he podido solucionar aunque lo he intentado de varias maneras. Es con el webhook. En el siguiente video se puede observar que es lo que pasa: 

https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/93489176/814eccb7-b580-4ac5-acf3-a7bf2834f463

Agradezco la ayuda.

**Comment by vinixcode** [comment]
@Santiagovaron1318 me gustaría que sacaramos unos minutos en llamada para ayudarte. Escríbeme por favor a juan@vinixcode.com y coordinamos un espacio entre hoy y mañana.

Saludos.

**Comment by vinixcode** [comment]
Se solucionó el problema en sesión de Google Meet. Cerrando ticket.

**Comment by Santiagovaron1318** [comment]
Hola, tengo una duda acerca del curso, respecto a la información de un
negocio, en lo que compete a contactos e historial de chats.Cuando se pone
un número en producción esta información si o si se pierde?, o de qué
manera se puede recuperar y almacenar para poder seguir teniéndola, por
ejemplo algo como los contactos, que es muy importante, yo había pensado en
el almacenaje de esa información utilizando archivos CSV y luego
formateando y almacenando, sin embargo como la obtengo la data?, o hay un
mejor método?. Muchas gracias, quedo atento

**Comment by Santiagovaron1318** [comment]
---------- Forwarded message ---------
De: Santiago Varon ***@***.***>
Date: vie, 26 ene 2024 a la(s) 3:23 p.m.
Subject: Pregunta acerca del curso de la API Cloud
To: Vinix-Code-Dev/curso-api-whatsapp-frontend <
***@***.***>


Hola, tengo una duda acerca del curso, respecto a la información de un
negocio, en lo que compete a contactos e historial de chats.Cuando se pone
un número en producción esta información si o si se pierde?, o de qué
manera se puede recuperar y almacenar para poder seguir teniéndola, por
ejemplo algo como los contactos, que es muy importante, yo había pensado en
el almacenaje de esa información utilizando archivos CSV y luego
formateando y almacenando, sin embargo como la obtengo la data?, o hay un
mejor método?. Muchas gracias, quedo atento
