### ISSUE TITLE
Error al guardar mensaje entrante.

### ISSUE THREAD

**Issue by Santiagovaron1318** [Vinix-Code-Dev/curso-api-whatsapp-frontend#92]
[

https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/93489176/90591e9d-a719-424a-a4c9-330d8fd76d9b

](url)

En el video se adjunta la información claramente. Espero pronta respuesta, muchas gracias.

**Comment by vinixcode** [comment]
Hola Santiago,

La verdad no comprendo bien el problema (el video no tiene audio, cierto?)

Por favor revisa el código del frontend y del backend que hay en el curso y trata de identificar en dónde está el problema, o en donde estás haciendo algo distinto. De seguro así encontrarás la solución, como lo vimos en la sesión remota que tuvimos.

Saludos
