### ISSUE TITLE
No lista catálogos Whatsapp

### ISSUE THREAD

**Issue by jucagolo** [Vinix-Code-Dev/curso-api-whatsapp-frontend#93]
Cordial saludo, tengo dificultades tratando de llamar los catálogos de WhatsApp.

Estos ya fueron creados según el tutorial

Estoy usando los siguientes endpoints: 

 "https://graph.facebook.com/LATEST-VERSION/WHATSAPP-BUSINESS-ACCOUNT-ID/product_catalogs?access_token=USERS-ACCESS-TOKEN"

 Este primero me retorna el campo data vacío y esta cuenta tiene dos catálogos creados y asociados a esa app con el WHATSAPP-BUSINESS-ACCOUNT-ID que le paso.

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/7596872/cfa63078-fdeb-45d0-be26-4e5aa10090e2)

  "https://graph.facebook.com/<API_VERSION>/<BUSINESS_ID>/owned_product_catalogs"

Con este, me retorna el siguiente error:  {"error":{"message":"(#100) Tried accessing nonexisting field (owned_product_catalogs) on node type (WhatsAppBusinessAccount)","type":"OAuthException","code":100,"fbtrace_id":"AfmJ69X-WUaEOJivMfrK99V"}}

![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/7596872/4a201766-9183-4d23-81e8-f0d39fa96d1b)

Agradezco su apoyo, no sé si falta configurar algo o porque no puedo obtener mis catálogos mediante el API.

**Comment by jucagolo** [comment]
![image](https://github.com/Vinix-Code-Dev/curso-api-whatsapp-frontend/assets/7596872/8286bcc7-d98d-410e-aca6-e2fab1aec638)

**Comment by vinixcode** [comment]
@jucagolo pareciera como si el catálogo no está asignado o conectado a la línea de WhatsApp. ¿Podrías confirmar si ya está conectado? Grabé un video mostrando como hacerlo:

https://www.awesomescreenshot.com/video/23623783?key=371d5e7006e04cba3d2b4f331816c96f

**Comment by jucagolo** [comment]
Hola.

Super, muchas gracias, volví y lo generé con los pasos que me enviaste y todo correcto.

Saludos
