### ISSUE TITLE
YA no se puede validar URL de validación del Webhook

### ISSUE THREAD

**Issue by Richard07061965** [Vinix-Code-Dev/curso-api-whatsapp-frontend#96]
Buenas noches, mi aplicación de WhatsApp funcionó perfectamente por algunos meses y ahora me sale el siguiente error al querer validar la URL de validación del webhook
**[No se pudo validar la URL de devolución de llamada o el token de verificación. Verifica la información proporcionada o vuelve a intentarlo más tarde.]**
QUe pudo haber pasado?, Cómo o soluciono?

**Comment by vinixcode** [comment]
Hola Richard.
Hemos notado internamente que ocurre solo con la version gratuita de ngrok, pero con la version paga si funciona sin problema.
Intenta con otra solucion como por ejemplo localtunnel u otras alternativas.
